// Contenido adicional B2–C2: lecturas, escenarios, audios de examen y preguntas de negocios. Original.

export const ADV_READINGS = [
  { id: "r.b2-ai-jobs", level: "B2", title: "Will AI take our jobs?", icon: "🤖", topic: "technology",
    text: "Few topics generate as much anxiety as the impact of artificial intelligence on employment. Historically, new technologies have destroyed some jobs while creating others, and economists expect a similar pattern this time. However, the pace of change may be faster. Routine tasks such as data entry, basic customer service and simple translation are already being automated. At the same time, demand is growing for people who can work alongside AI: analysts who can question its outputs, technicians who maintain the systems and managers who redesign processes around them. The workers most at risk, experts argue, are not those in a particular sector but those who stop learning.",
    q: [["What do economists expect?", "Some jobs will disappear and others will be created.", ["All jobs will disappear.", "Nothing will change."]], ["What may be different this time?", "The speed of change.", ["The type of workers.", "The cost of technology."]], ["Who is most at risk, according to experts?", "People who stop learning.", ["People in customer service only.", "Managers."]]] },
  { id: "r.b2-feedback", level: "B2", title: "Giving feedback that works", icon: "💬", topic: "hr",
    text: "Most managers agree that feedback is essential, yet many avoid giving it, fearing conflict or damaged relationships. Research suggests that the problem is not feedback itself but the way it is delivered. Effective feedback is specific, timely and focused on behaviour rather than personality. Saying 'Your report was late and missed two key figures' is far more useful than 'You're disorganised'. It also helps to explain the impact of the behaviour and to invite the employee to suggest solutions. Finally, positive feedback should not be forgotten: recognising good work increases motivation and makes critical comments easier to accept.",
    q: [["Why do many managers avoid feedback?", "They fear conflict.", ["They have no time.", "Employees don't want it."]], ["What should feedback focus on?", "Behaviour, not personality.", ["Personality traits.", "Salary."]], ["Why is positive feedback important?", "It increases motivation and helps people accept criticism.", ["It replaces critical feedback.", "It is required by law."]]] },
  { id: "r.c1-urban", level: "C1", title: "The 15-minute city", icon: "🏙️", topic: "society",
    text: "The concept of the '15-minute city' — an urban model in which residents can reach work, schools, shops and healthcare within a quarter of an hour on foot or by bicycle — has moved rapidly from academic journals to mayoral manifestos. Proponents argue that it reduces emissions, revitalises local economies and restores a sense of community. Critics, however, contend that the model presupposes a density and mix of services that many suburbs simply lack, and warn that, without careful planning, rising property values in well-served neighbourhoods may displace the very residents the policy was intended to benefit. The debate illustrates a recurring tension in urban policy between desirable outcomes and the uneven means of achieving them.",
    q: [["What is a '15-minute city'?", "A city where daily needs are within 15 minutes on foot or by bike.", ["A city with a 15-minute train service.", "A city built in 15 years."]], ["What is one criticism?", "Many suburbs lack the necessary density and services.", ["It increases emissions.", "It is too expensive to discuss."]], ["What risk do critics mention?", "Rising property prices could displace residents.", ["People will walk too much.", "Shops will close."]], ["What does the debate illustrate?", "A tension between goals and how to achieve them fairly.", ["That cities should stop growing.", "That the idea is universally accepted."]]] },
  { id: "r.c1-sleep", level: "C1", title: "Why sleep is a performance tool", icon: "😴", topic: "health",
    text: "In many workplaces, sleeping little is still worn as a badge of honour. Yet the evidence against this culture is compelling. Even moderate sleep deprivation impairs attention, memory and emotional regulation to a degree comparable with mild intoxication. Crucially, people who are chronically short of sleep tend to underestimate their own impairment, which makes the problem self-perpetuating. Organisations that have taken the research seriously — by discouraging late-night emails or scheduling fewer early meetings — report not only healthier employees but better decision-making. Sleep, in other words, is less a luxury than a performance tool.",
    q: [["How is sleeping little often seen at work?", "As something to be proud of.", ["As a medical problem.", "As illegal."]], ["What does sleep deprivation affect?", "Attention, memory and emotions.", ["Only physical strength.", "Nothing important."]], ["Why is the problem 'self-perpetuating'?", "Tired people underestimate their impairment.", ["Companies pay for overtime.", "Sleep cannot be measured."]], ["What is the author's main point?", "Sleep improves performance.", ["Sleep is a luxury.", "Late emails are efficient."]]] },
  { id: "r.c2-trust", level: "C2", title: "The economics of trust", icon: "🤝", topic: "business",
    text: "Economists have long recognised that trust functions as a kind of invisible infrastructure. Where it is abundant, transactions can be sealed with a handshake, contracts can remain brief and disputes are settled informally; where it is scarce, every exchange must be buttressed by guarantees, audits and litigation, all of which impose costs that are rarely itemised yet invariably borne. Paradoxically, the very mechanisms designed to compensate for a deficit of trust — exhaustive compliance procedures, for instance — may erode it further, signalling suspicion and crowding out the discretionary goodwill on which cooperation ultimately depends. The challenge for institutions, then, is not merely to police misconduct but to cultivate the conditions under which trust can be reasonably extended.",
    q: [["What is trust compared to?", "An invisible infrastructure.", ["A legal contract.", "A financial product."]], ["What happens where trust is scarce?", "Exchanges require guarantees, audits and litigation.", ["Contracts become shorter.", "Transactions become free."]], ["What paradox does the author describe?", "Controls meant to compensate for low trust can reduce it further.", ["More trust creates more lawsuits.", "Audits always increase goodwill."]], ["What does 'crowding out' mean here?", "Pushing aside / replacing.", ["Attracting more people.", "Counting precisely."]]] },
  { id: "r.c2-language-ai", level: "C2", title: "Machines and meaning", icon: "🧠", topic: "academic",
    text: "Whether large language models can be said to 'understand' language remains a matter of considerable dispute. Sceptics maintain that such systems merely manipulate statistical regularities in text, producing fluent output without any grounding in the world to which the words refer. Their opponents counter that the distinction between 'mere' pattern-matching and understanding is itself poorly defined, and that human comprehension may rely on statistical learning to a greater extent than we care to admit. What is less contested is that the question has practical consequences: the degree of trust we place in these systems ought to be calibrated not to how articulate they sound, but to how reliably their outputs can be verified.",
    q: [["What is the main point of dispute?", "Whether language models truly understand language.", ["Whether language models are fast.", "Whether humans use statistics."]], ["What do sceptics claim?", "The systems lack grounding in the real world.", ["The systems understand better than humans.", "The systems cannot produce fluent text."]], ["According to the author, trust in these systems should depend on…", "how reliably their outputs can be verified.", ["how articulate they sound.", "how popular they are."]]] },
];

const S = (id, title, es, cat, level, character, emoji, goal, steps, extra = {}) => ({ id, title, es, cat, level, character, emoji, goal, steps, ...extra });
export const ADV_SCENARIOS = [
  S("performance-review", "Performance review conversation", "Conversación de evaluación de desempeño", "pro", "B2", "sarah", "📊", "Discuss your achievements, accept feedback and agree on objectives.", [
    { ai: "Thanks for coming. Let's start with you: how do you feel this year has gone?", es: "Gracias por venir. Empecemos contigo: ¿cómo sientes que te fue este año?", h: ["achieved, proud, challenging, improved", "Overall, I think it went… I'm particularly proud of…", "Overall,…", "Overall, I think it went well. I'm particularly proud of reducing rework by 20%."] },
    { ai: "That's a great result. One area I'd like you to work on is delegating more. What do you think?", es: "Gran resultado. Un área que quiero que trabajes es delegar más. ¿Qué opinas?", h: ["fair point, tend to, support, training", "That's a fair point. I tend to… Could I get some support with…?", "That's a fair point…", "That's a fair point. I tend to do things myself. Could I get some coaching on delegation?"] },
    { ai: "Absolutely. Now, what objectives would you like to set for next year?", es: "Claro. ¿Qué objetivos te gustaría fijar para el próximo año?", h: ["lead, certification, reduce, by the end of", "I'd like to… by the end of the year.", "I'd like to…", "I'd like to lead the new supplier audit program and get my ISO lead auditor certification by the end of the year."] },
    { ai: "Sounds ambitious but achievable. Is there anything you need from me?", es: "Suena ambicioso pero alcanzable. ¿Necesitas algo de mi parte?", h: ["budget, time, visibility, regular check-ins", "It would really help if…", "It would really help if…", "It would really help if we could have monthly check-ins and a small training budget."] },
    { ai: "Agreed. I'll put it all in writing and send it to you this week.", es: "De acuerdo. Lo pondré por escrito y te lo enviaré esta semana.", h: ["thank you, appreciate, feedback", "Thank you, I really appreciate the feedback.", "Thank you…", "Thank you, Sarah. I really appreciate the feedback."], end: true },
  ], { pro: "hr" }),
  S("crisis-call", "Crisis management call", "Llamada de gestión de crisis", "pro", "C1", "ceo", "🚨", "Brief the CEO on an incident, explain actions and manage expectations.", [
    { ai: "I've just heard there's been a leak at the terminal. What exactly happened?", es: "Acabo de enterarme de una fuga en la terminal. ¿Qué pasó exactamente?", h: ["at approximately, detected, contained, no injuries", "At approximately … a leak was detected… It has been contained.", "At approximately…", "At approximately 6 a.m., a leak was detected in line 3. It has been contained and there were no injuries."] },
    { ai: "Good. What's the likely cause?", es: "Bien. ¿Cuál es la causa probable?", h: ["preliminary, appears, corrosion, too early", "It's too early to say for sure, but it appears that…", "It's too early…", "It's too early to say for sure, but it appears that a corroded flange failed."] },
    { ai: "The press are already calling. What should we say?", es: "La prensa ya está llamando. ¿Qué deberíamos decir?", h: ["statement, transparent, investigation, update", "I'd recommend a brief statement confirming… and that we will…", "I'd recommend…", "I'd recommend a brief, transparent statement confirming the incident is contained and that a full investigation is under way."] },
    { ai: "And the impact on operations?", es: "¿Y el impacto en las operaciones?", h: ["reduced capacity, rerouting, estimate, hours", "We're operating at reduced capacity… We estimate…", "We're operating…", "We're operating at reduced capacity while we reroute through line 2. We estimate full recovery within 48 hours."] },
    { ai: "Keep me posted every two hours, please.", es: "Manténme informado cada dos horas, por favor.", h: ["will do, next update, noon", "Will do. You'll have my next update at…", "Will do…", "Will do. You'll have my next update at noon."], end: true },
  ], { pro: "oilgas" }),
  S("board-presentation", "Presenting to the board", "Presentación ante el directorio", "pro", "C1", "ceo", "🏛️", "Present a proposal, handle tough questions and secure approval.", [
    { ai: "You have ten minutes. What are you asking the board to approve?", es: "Tiene diez minutos. ¿Qué le pide al directorio que apruebe?", h: ["seeking approval, investment, return, payback", "We're seeking approval for… which would deliver…", "We're seeking…", "We're seeking approval for a two-million-dollar investment in predictive maintenance, with a payback period of under three years."] },
    { ai: "Why now? Couldn't this wait until next year?", es: "¿Por qué ahora? ¿No puede esperar al próximo año?", h: ["cost of delay, failures, rising, window", "The cost of waiting is… Moreover,…", "The cost of waiting…", "The cost of waiting is significant: unplanned failures cost us 800,000 dollars last year. Moreover, supplier prices are expected to rise."] },
    { ai: "What are the main risks?", es: "¿Cuáles son los principales riesgos?", h: ["adoption, data quality, mitigate, pilot", "The main risks are… We'd mitigate them by…", "The main risks are…", "The main risks are low adoption and poor data quality. We'd mitigate them with a six-month pilot and dedicated training."] },
    { ai: "I'm not fully convinced by your savings estimate.", es: "No me convence del todo su estimación de ahorro.", h: ["understand, conservative, benchmark, happy to share", "I understand your concern. Our estimate is conservative… I'd be happy to…", "I understand…", "I understand your concern. Our estimate is conservative and benchmarked against two similar plants. I'd be happy to share the detailed model."] },
    { ai: "Very well. We'll approve the pilot phase first.", es: "Muy bien. Aprobaremos primero la fase piloto.", h: ["thank you, report back, results", "Thank you. We'll report back with the results in…", "Thank you…", "Thank you. We'll report back with the pilot results in six months."], end: true },
  ], { pro: "business" }),
  S("conference-qa", "Conference Q&A", "Preguntas y respuestas en una conferencia", "pro", "C1", "professor", "🎙️", "Answer challenging questions after a talk with precision and diplomacy.", [
    { ai: "Thank you for your talk. How generalisable are your findings beyond your sample?", es: "Gracias por su charla. ¿Qué tan generalizables son sus resultados más allá de su muestra?", h: ["good question, limitation, caution, further research", "That's a very good question. One limitation is… so I'd be cautious…", "That's a very good…", "That's a very good question. One limitation is that our sample came from a single region, so I'd be cautious about generalising."] },
    { ai: "Didn't you consider the effect of seasonality?", es: "¿No consideró el efecto de la estacionalidad?", h: ["accounted for, controlled, however, admittedly", "We did account for… Admittedly, however,…", "We did account…", "We did account for seasonality by comparing the same months. Admittedly, however, two years of data is a relatively short period."] },
    { ai: "What would you do differently next time?", es: "¿Qué haría diferente la próxima vez?", h: ["in hindsight, would have, broader, longer", "In hindsight, we would have…", "In hindsight,…", "In hindsight, we would have used a broader sample and a longer time frame."] },
    { ai: "Thank you, that's very helpful.", es: "Gracias, muy útil.", h: ["pleasure, happy to discuss, after the session", "My pleasure. I'd be happy to discuss it further after the session.", "My pleasure…", "My pleasure. I'd be happy to discuss it further after the session."], end: true },
  ], { pro: "career" }),
];

export const ADV_LISTENINGS = [
  { level: "B2", lines: ["A: How did the negotiation go yesterday?", "B: Better than expected, actually. They wouldn't budge on price, but they agreed to extend the warranty to three years.", "A: That's worth quite a lot.", "B: Exactly. And they'll cover shipping, which they flatly refused last time."], q: [["What didn't the supplier change?", "The price.", ["The warranty.", "The shipping."]], ["What did they agree to?", "A three-year warranty and free shipping.", ["A lower price.", "Faster delivery only."]]] },
  { level: "C1", lines: ["A: I gather the merger's been called off.", "B: Postponed rather than called off, officially. The regulators raised concerns about competition in two regional markets.", "A: So it could still go ahead?", "B: In principle, yes — provided both companies agree to sell off some assets. But that's a big 'if'."], q: [["What is the official status of the merger?", "Postponed.", ["Completed.", "Cancelled forever."]], ["Why was it delayed?", "Regulators had competition concerns.", ["The CEOs disagreed.", "Financing failed."]], ["What does 'a big if' suggest?", "The condition may not be met.", ["The deal is certain.", "The deal is large."]]] },
  { level: "C2", lines: ["A: The report is meticulous, but I can't help feeling it sidesteps the central question.", "B: Which is?", "A: Whether the programme represents value for money, as opposed to merely meeting its targets. Hitting every milestone tells us nothing if the milestones themselves were set too low.", "B: Fair. Though to be even-handed, the authors did acknowledge that in the appendix — albeit rather obliquely."], q: [["What is A's main criticism?", "The report avoids the key question of value for money.", ["The report is inaccurate.", "The report is too short."]], ["Why does meeting targets not satisfy A?", "The targets may have been too easy.", ["The targets were impossible.", "There were no targets."]], ["What does B concede about the authors?", "They mentioned the issue indirectly.", ["They ignored it completely.", "They discussed it at length."]]] },
  { level: "C2", lines: ["A: Did you catch the minister's speech?", "B: I did. Remarkably little substance for forty minutes.", "A: I thought the section on housing was fairly concrete.", "B: Concrete in tone, perhaps. But strip away the rhetoric and there wasn't a single costed commitment."], q: [["What is B's opinion of the speech?", "It lacked real content.", ["It was too short.", "It was very detailed."]], ["What does B mean by 'costed commitment'?", "A promise with a stated budget.", ["An expensive promise.", "A promise about housing prices."]]] },
];

export const ADV_BUSINESS = [
  { level: "C1", q: "Which phrase best softens a refusal to a client?", a: "Unfortunately, we're not in a position to offer that at this stage.", d: ["No, we won't do that.", "That's impossible, sorry."] },
  { level: "C1", q: "“Let's take this offline” in a meeting means:", a: "Let's discuss this separately later.", d: ["Let's turn off our computers.", "Let's cancel the project."] },
  { level: "C1", q: "Best opening for an executive summary:", a: "This report evaluates three options and recommends Option B.", d: ["In this report I'm going to tell you some things.", "Hello, here is the report."] },
  { level: "C1", q: "“We need to manage expectations” means:", a: "We should make sure people don't expect too much.", d: ["We need a new manager.", "We should promise more."] },
  { level: "C2", q: "Most diplomatic way to point out a colleague's error in front of others:", a: "I wonder if we might double-check that figure — I have a slightly different number.", d: ["Your number is wrong.", "You made a mistake again."] },
  { level: "C2", q: "Choose the most precise verb: “The audit ___ several weaknesses in internal controls.”", a: "revealed", d: ["said", "made"] },
  { level: "C2", q: "“The proposal is a non-starter” means it:", a: "has no chance of being accepted.", d: ["hasn't started yet.", "is the first proposal."] },
  { level: "C2", q: "Which sentence is the most appropriate for a formal apology to a client?", a: "Please accept our sincere apologies for the inconvenience caused.", d: ["Sorry about the mess!", "It wasn't really our fault, but sorry."] },
];
