// Gramática A2 — contenido original.
export default [
  {
    id: "g.past-simple", level: "A2", title: "Past Simple", es: "Pasado simple", icon: "⏪",
    situation: { emoji: "🧳", en: "Monday morning: 'How was your weekend?'", es: "Lunes por la mañana: «¿Qué tal tu fin de semana?»" },
    examples: [["I visited my parents on Saturday.", "Visité a mis padres el sábado."], ["We went to the beach.", "Fuimos a la playa."], ["She didn't call me.", "Ella no me llamó."], ["Did you finish the report?", "¿Terminaste el informe?"], ["The inspector rejected the weld yesterday.", "El inspector rechazó la soldadura ayer."]],
    pattern: "verb-ed / irregular (went, had, saw) · didn't + base · Did…+ base?",
    rule: {
      es: ["Acciones terminadas en un momento del pasado (yesterday, last week, in 2020, two days ago).", "Regulares: + ed (work → worked, stop → stopped, study → studied).", "Irregulares hay que aprenderlos: go → went, have → had, see → saw, make → made, take → took.", "Negativo: didn't + verbo base (I didn't go). Pregunta: Did + sujeto + verbo base (Did you go?).", "Was / were es el pasado de be: I was, they were."],
      en: ["Use it for finished actions at a specific past time.", "Regular verbs add -ed; irregular verbs have special forms.", "didn't / Did + base verb. Past of be: was/were."],
    },
    simple: { es: "Para algo que ya terminó. Después de did/didn't, el verbo vuelve a su forma normal.", en: "Finished actions. After did/didn't, use the base verb." },
    more: [["The meeting started late.", "La reunión empezó tarde."], ["We signed the agreement last week.", "Firmamos el acuerdo la semana pasada."], ["Where did you go on vacation?", "¿A dónde fuiste de vacaciones?"]],
    items: [
      ["I ___ to the beach last weekend.", "went", ["go", "goed"], "travel", "Fui a la playa el fin de semana pasado."],
      ["She ___ the report yesterday.", "finished", ["finish", "finishes"], "work", "Ella terminó el informe ayer."],
      ["We didn't ___ the email.", "see", ["saw", "seen"], "work", "No vimos el correo."],
      ["___ you call the supplier?", "Did", ["Do", "Were"], "biz", "¿Llamaste al proveedor?"],
      ["The inspector ___ the weld two days ago.", "rejected", ["rejects", "reject"], "qa", "El inspector rechazó la soldadura hace dos días."],
      ["They ___ the agreement in May.", "signed", ["sign", "have signed"], "law", "Firmaron el acuerdo en mayo."],
      ["The pump ___ at 3 a.m. last night.", "stopped", ["stoped", "stops"], "oil", "La bomba se detuvo a las 3 a. m. anoche."],
      ["I ___ very tired yesterday.", "was", ["were", "am"], "daily", "Estaba muy cansado ayer."],
      ["We ___ three candidates last week.", "interviewed", ["interview", "interviewing"], "hr", "Entrevistamos a tres candidatos la semana pasada."],
      ["What time ___ the meeting end?", "did", ["was", "does"], "meeting", "¿A qué hora terminó la reunión?"],
      ["He ___ a mistake in the drawing.", "made", ["did", "maked"], "eng", "Él cometió un error en el plano."],
    ],
    challenge: { en: "Tell me about your last weekend in three sentences.", es: "Cuéntame tu último fin de semana en tres frases.", check: "\\b\\w+ed\\b|\\b(went|had|was|were|saw|made|took|got|ate|met)\\b" },
    errors: ["did-past", "did-question-past", "past-time-present", "present-time-past"],
  },
  {
    id: "g.past-continuous", level: "A2", title: "Past Continuous", es: "Pasado continuo", icon: "🎞️",
    situation: { emoji: "⚡", en: "An incident report: what was happening when the power failed?", es: "Un informe de incidente: ¿qué estaba pasando cuando falló la energía?" },
    examples: [["I was working when the alarm went off.", "Estaba trabajando cuando sonó la alarma."], ["They were checking the tank at 10 a.m.", "Estaban revisando el tanque a las 10 a. m."], ["What were you doing?", "¿Qué estabas haciendo?"], ["While she was driving, it started to rain.", "Mientras ella manejaba, empezó a llover."]],
    pattern: "was / were + verb-ing · when + past simple · while + past continuous",
    rule: {
      es: ["Acción en progreso en un momento del pasado: At 8 p.m. I was cooking.", "Forma: was / were + -ing.", "Se combina con el Past Simple: la acción larga (past continuous) es interrumpida por una corta (past simple): I was sleeping when the phone rang.", "While + acción larga; when + acción corta."],
      en: ["Use it for an action in progress at a past moment.", "Often combined with the Past Simple for an interruption.", "while + long action; when + short action."],
    },
    simple: { es: "«Estaba haciendo algo» = was/were + -ing.", en: "was / were + -ing = in progress in the past." },
    more: [["The operator was monitoring the pressure when the valve failed.", "El operador estaba monitoreando la presión cuando falló la válvula."]],
    items: [
      ["I ___ when the alarm went off.", "was working", ["worked", "were working"], "oil", "Estaba trabajando cuando sonó la alarma."],
      ["They ___ the tank at 10 a.m.", "were checking", ["was checking", "checked"], "eng", "Estaban revisando el tanque a las 10 a. m."],
      ["What ___ you doing at 9 last night?", "were", ["was", "did"], "daily", "¿Qué estabas haciendo anoche a las 9?"],
      ["While we were having lunch, the client ___.", "called", ["was calling", "calls"], "biz", "Mientras almorzábamos, llamó el cliente."],
      ["She was presenting the results when the projector ___.", "stopped", ["was stopping", "stops"], "meeting", "Ella estaba presentando los resultados cuando el proyector se apagó."],
      ["It ___ when we left the hotel.", "was raining", ["rained", "is raining"], "travel", "Estaba lloviendo cuando salimos del hotel."],
      ["The auditor ___ the files when I arrived.", "was reviewing", ["reviewed", "were reviewing"], "qa", "El auditor estaba revisando los archivos cuando llegué."],
    ],
    challenge: { en: "Describe what you were doing yesterday at 8 p.m.", es: "Describe qué estabas haciendo ayer a las 8 p. m.", check: "\\b(was|were)\\s+\\w+ing\\b" },
    errors: [],
  },
  {
    id: "g.going-to", level: "A2", title: "Going to (plans)", es: "Going to: planes e intenciones", icon: "🗺️",
    situation: { emoji: "✈️", en: "Talking about your plans for next year.", es: "Hablando de tus planes para el próximo año." },
    examples: [["I'm going to study for the IELTS.", "Voy a estudiar para el IELTS."], ["We're going to visit Spain in July.", "Vamos a visitar España en julio."], ["Look at those clouds! It's going to rain.", "¡Mira esas nubes! Va a llover."], ["Are you going to apply for the job?", "¿Vas a postular al trabajo?"]],
    pattern: "am / is / are + going to + base verb",
    rule: {
      es: ["Planes e intenciones ya decididos: I'm going to change jobs.", "Predicciones con evidencia: It's going to rain (hay nubes).", "Forma: be + going to + verbo base."],
      en: ["Use going to for plans decided before speaking and predictions based on evidence.", "Form: be + going to + base verb."],
    },
    simple: { es: "«Voy a…» = I'm going to…", en: "A plan you already have: be going to + verb." },
    more: [["The company is going to open a new plant.", "La empresa va a abrir una nueva planta."], ["We're going to hire two engineers.", "Vamos a contratar a dos ingenieros."]],
    items: [
      ["I'm going ___ study tonight.", "to", ["for", "at"], "daily", "Voy a estudiar esta noche."],
      ["We ___ visit Spain in July.", "are going to", ["going to", "are go to"], "travel", "Vamos a visitar España en julio."],
      ["Look at the sky! It ___ rain.", "is going to", ["going to", "goes to"], "daily", "¡Mira el cielo! Va a llover."],
      ["___ you going to apply for the position?", "Are", ["Do", "Will"], "hr", "¿Vas a postular al puesto?"],
      ["The company ___ open a new plant next year.", "is going to", ["are going to", "going"], "biz", "La empresa va a abrir una nueva planta el próximo año."],
      ["They're going to ___ the pipeline next month.", "replace", ["replacing", "replaced"], "oil", "Van a reemplazar la tubería el próximo mes."],
      ["I'm not going to ___ the contract without reading it.", "sign", ["signing", "signed"], "law", "No voy a firmar el contrato sin leerlo."],
    ],
    challenge: { en: "Write three plans for next month.", es: "Escribe tres planes para el próximo mes.", check: "\\bgoing to\\b" },
    errors: [],
  },
  {
    id: "g.will", level: "A2", title: "Will (future)", es: "Will: decisiones y predicciones", icon: "🔮",
    situation: { emoji: "☎️", en: "A client needs help urgently.", es: "Un cliente necesita ayuda urgente." },
    examples: [["I'll call you back in five minutes.", "Te devuelvo la llamada en cinco minutos."], ["Don't worry, I'll help you.", "No te preocupes, te ayudo."], ["I think prices will go up.", "Creo que los precios subirán."], ["Will you be at the meeting?", "¿Estarás en la reunión?"]],
    pattern: "will ('ll) + base verb · won't",
    rule: {
      es: ["Decisiones en el momento: The phone's ringing — I'll answer it.", "Promesas y ofrecimientos: I'll send it today.", "Predicciones y opiniones sobre el futuro: I think it will be difficult.", "Igual para todas las personas; después va el verbo base. Negativo: won't."],
      en: ["Use will for instant decisions, offers, promises and opinions about the future.", "will / won't + base verb."],
    },
    simple: { es: "Decides ahora o prometes algo → I'll…", en: "Decide now or promise → I'll…" },
    more: [["I'll send you the report today.", "Te envío el informe hoy."], ["The project won't finish on time.", "El proyecto no terminará a tiempo."]],
    items: [
      ["The phone's ringing. I ___ answer it.", "will", ["am", "will to"], "work", "Suena el teléfono. Yo contesto."],
      ["Don't worry. I ___ send you the report today.", "will", ["am", "going"], "biz", "No te preocupes. Te envío el informe hoy."],
      ["I think the project ___ finish on time.", "won't", ["doesn't", "isn't"], "eng", "Creo que el proyecto no terminará a tiempo."],
      ["___ you be at the meeting tomorrow?", "Will", ["Do", "Are"], "meeting", "¿Estarás en la reunión mañana?"],
      ["I'm sure you ___ enjoy the trip.", "will", ["are", "going"], "travel", "Estoy seguro de que disfrutarás el viaje."],
      ["We will ___ the results next week.", "review", ["reviewing", "to review"], "qa", "Revisaremos los resultados la próxima semana."],
      ["HR ___ contact the successful candidates.", "will", ["is", "going"], "hr", "RR. HH. contactará a los candidatos seleccionados."],
    ],
    challenge: { en: "Make two promises and one prediction about your job.", es: "Haz dos promesas y una predicción sobre tu trabajo.", check: "\\b(will|'ll|won't)\\b" },
    errors: ["if-will"],
  },
  {
    id: "g.comparatives", level: "A2", title: "Comparatives", es: "Comparativos", icon: "⚖️",
    situation: { emoji: "🏷️", en: "Comparing two supplier offers.", es: "Comparando dos ofertas de proveedores." },
    examples: [["Supplier A is cheaper than Supplier B.", "El proveedor A es más barato que el B."], ["This model is more reliable.", "Este modelo es más confiable."], ["The new process is better.", "El nuevo proceso es mejor."], ["Today is hotter than yesterday.", "Hoy hace más calor que ayer."]],
    pattern: "short adj + -er + than · more + long adj + than · good→better, bad→worse, far→farther",
    rule: {
      es: ["Adjetivos cortos (1 sílaba, o 2 terminadas en -y): + er (cheap → cheaper, easy → easier, big → bigger).", "Adjetivos largos: more + adjetivo (more expensive, more reliable).", "Irregulares: good → better, bad → worse, far → farther/further.", "Se usa than para comparar: than = que.", "Nunca more + -er: better (no «more better»)."],
      en: ["Short adjectives: -er; long adjectives: more + adjective; then than.", "Irregular: better, worse, farther/further. Never more + -er."],
    },
    simple: { es: "Corto: -er (bigger). Largo: more (more expensive). Luego than.", en: "short → -er, long → more, then than." },
    more: [["The second option is less risky.", "La segunda opción es menos riesgosa."], ["This laptop is as fast as that one.", "Esta laptop es tan rápida como aquella."]],
    items: [
      ["Supplier A is ___ than Supplier B.", "cheaper", ["more cheap", "cheapest"], "biz", "El proveedor A es más barato que el B."],
      ["This model is ___ reliable than the old one.", "more", ["most", "-er"], "eng", "Este modelo es más confiable que el anterior."],
      ["The new procedure is ___ than the old one.", "better", ["more better", "gooder"], "qa", "El nuevo procedimiento es mejor que el anterior."],
      ["Today is ___ than yesterday.", "hotter", ["more hot", "hoter"], "daily", "Hoy hace más calor que ayer."],
      ["The hotel is ___ expensive than the hostel.", "more", ["much", "most"], "travel", "El hotel es más caro que el hostal."],
      ["The results are ___ than last year. (bad)", "worse", ["badder", "more bad"], "report", "Los resultados son peores que el año pasado."],
      ["Contract B is ___ than contract A. (flexible)", "more flexible", ["flexibler", "most flexible"], "law", "El contrato B es más flexible que el A."],
      ["The pipeline is ___ than we expected. (long)", "longer", ["more long", "longest"], "oil", "La tubería es más larga de lo que esperábamos."],
    ],
    challenge: { en: "Compare two cities or two jobs in three sentences.", es: "Compara dos ciudades o dos trabajos en tres frases.", check: "\\b(\\w+er|more \\w+|better|worse) than\\b" },
    errors: ["more-er", "more-short-adj"],
  },
  {
    id: "g.superlatives", level: "A2", title: "Superlatives", es: "Superlativos", icon: "🏆",
    situation: { emoji: "🏙️", en: "Recommending places in your city to a visitor.", es: "Recomendando lugares de tu ciudad a un visitante." },
    examples: [["It's the tallest building in the city.", "Es el edificio más alto de la ciudad."], ["This is the most important point.", "Este es el punto más importante."], ["She's the best engineer on the team.", "Es la mejor ingeniera del equipo."], ["It was the worst day of the year.", "Fue el peor día del año."]],
    pattern: "the + adj-est · the most + long adj · the best / the worst",
    rule: {
      es: ["Cortos: the + -est (the cheapest, the biggest, the easiest).", "Largos: the most + adjetivo (the most expensive).", "Irregulares: the best, the worst, the farthest.", "Después: in + lugar/grupo (in the world, on the team) u of + período (of the year)."],
      en: ["the + -est / the most + adjective.", "Irregular: the best, the worst.", "Use in with places/groups and of with periods."],
    },
    simple: { es: "El más… = the -est o the most…", en: "Number one: the -est or the most." },
    more: [["It's the safest option.", "Es la opción más segura."], ["This is the most common mistake.", "Este es el error más común."]],
    items: [
      ["It's the ___ building in the city. (tall)", "tallest", ["most tall", "taller"], "travel", "Es el edificio más alto de la ciudad."],
      ["This is the ___ important point.", "most", ["more", "-est"], "meeting", "Este es el punto más importante."],
      ["She's the ___ engineer on the team.", "best", ["goodest", "better"], "eng", "Es la mejor ingeniera del equipo."],
      ["It was the ___ day of my life. (bad)", "worst", ["baddest", "worse"], "daily", "Fue el peor día de mi vida."],
      ["This is the ___ option. (safe)", "safest", ["most safe", "safer"], "oil", "Es la opción más segura."],
      ["He's the ___ experienced candidate.", "most", ["more", "much"], "hr", "Es el candidato con más experiencia."],
      ["It's the ___ nonconformity. (common)", "most common", ["more common", "commoner"], "qa", "Es la no conformidad más común."],
    ],
    challenge: { en: "Describe the best and the worst thing about your job or studies.", es: "Describe lo mejor y lo peor de tu trabajo o estudios.", check: "\\bthe (best|worst|most \\w+|\\w+est)\\b" },
    errors: [],
  },
  {
    id: "g.quantifiers", level: "A2", title: "Countable & uncountable", es: "Contables e incontables: some, any, much, many", icon: "🧮",
    situation: { emoji: "🛒", en: "Checking the stock before a shutdown.", es: "Revisando el inventario antes de una parada." },
    examples: [["We have some spare parts.", "Tenemos algunos repuestos."], ["Is there any water?", "¿Hay agua?"], ["How many people are coming?", "¿Cuántas personas vienen?"], ["We don't have much time.", "No tenemos mucho tiempo."], ["There's a lot of information.", "Hay mucha información."]],
    pattern: "many + plural · much + uncountable · a lot of + both · some (+) / any (− ?)",
    rule: {
      es: ["Contables (se pueden contar: valve, person) e incontables (water, time, information, equipment, advice, money).", "Many + plural contable; much + incontable (en negativas y preguntas). A lot of sirve para ambos.", "Some en frases afirmativas y ofrecimientos; any en negativas y preguntas.", "Las incontables no llevan -s ni a/an: some information, a piece of advice.", "No uses doble negación: I don't know anything."],
      en: ["many + plural countable nouns; much + uncountable nouns; a lot of for both.", "some in affirmative sentences and offers; any in negatives and questions.", "Uncountable nouns: no plural, no a/an."],
    },
    simple: { es: "Se cuentan → many. No se cuentan → much. Si dudas → a lot of.", en: "Can you count it? many. If not, much. Or just a lot of." },
    more: [["Would you like some coffee?", "¿Quieres café?"], ["We need a lot of equipment.", "Necesitamos mucho equipo."]],
    items: [
      ["How ___ people work in the plant?", "many", ["much", "any"], "oil", "¿Cuántas personas trabajan en la planta?"],
      ["We don't have ___ time.", "much", ["many", "some"], "work", "No tenemos mucho tiempo."],
      ["Is there ___ water in the tank?", "any", ["some", "many"], "eng", "¿Hay agua en el tanque?"],
      ["Would you like ___ coffee?", "some", ["any", "many"], "daily", "¿Quieres café?"],
      ["I need some ___ about the process.", "information", ["informations", "an information"], "qa", "Necesito información sobre el proceso."],
      ["There are ___ of candidates for this job.", "a lot", ["much", "many of"], "hr", "Hay muchos candidatos para este trabajo."],
      ["She gave me good ___.", "advice", ["advices", "an advice"], "daily", "Ella me dio un buen consejo."],
      ["I don't know ___ about the new policy.", "anything", ["nothing", "something"], "hr", "No sé nada sobre la nueva política."],
      ["How ___ does the equipment cost?", "much", ["many", "any"], "biz", "¿Cuánto cuesta el equipo?"],
    ],
    challenge: { en: "Describe what's in your fridge using some, any and a lot of.", es: "Describe qué hay en tu refrigerador con some, any y a lot of.", check: "\\b(some|any|a lot of|many|much)\\b" },
    errors: ["much-countable", "uncountable-plural", "double-negative"],
  },
  {
    id: "g.modals-obligation", level: "A2", title: "Must, have to, should", es: "Obligación y consejo: must, have to, should", icon: "⚠️",
    situation: { emoji: "🦺", en: "Safety induction at a new site.", es: "Inducción de seguridad en una obra nueva." },
    examples: [["You must wear a helmet.", "Debes usar casco."], ["I have to finish this today.", "Tengo que terminar esto hoy."], ["You don't have to come.", "No hace falta que vengas."], ["You mustn't smoke here.", "Está prohibido fumar aquí."], ["You should rest.", "Deberías descansar."]],
    pattern: "must / mustn't · have to / don't have to · should / shouldn't + base verb",
    rule: {
      es: ["Must = obligación fuerte (reglas, lo que el hablante considera necesario).", "Have to = obligación externa (horarios, leyes, el jefe). He has to.", "Mustn't = prohibido. Don't have to = no es necesario (¡significados diferentes!).", "Should = consejo, recomendación: You should call him.", "Después: verbo base sin to (excepto have to)."],
      en: ["must: strong obligation; have to: external obligation.", "mustn't = prohibited; don't have to = not necessary.", "should for advice. Base verb after modals."],
    },
    simple: { es: "Must/have to = tienes que. Mustn't = no puedes. Don't have to = no hace falta. Should = deberías.", en: "must = required, mustn't = forbidden, don't have to = optional, should = good idea." },
    more: [["Employees must report all incidents.", "Los empleados deben reportar todos los incidentes."], ["You should read the contract carefully.", "Deberías leer el contrato con cuidado."]],
    items: [
      ["You ___ wear a helmet on site.", "must", ["mustn't", "don't have to"], "oil", "Debes usar casco en la obra."],
      ["You ___ smoke near the tanks. It's dangerous.", "mustn't", ["don't have to", "should"], "oil", "Está prohibido fumar cerca de los tanques."],
      ["It's Saturday. I ___ work today.", "don't have to", ["mustn't", "must"], "daily", "Es sábado. No tengo que trabajar hoy."],
      ["She ___ finish the report by Friday.", "has to", ["have to", "must to"], "work", "Ella tiene que terminar el informe para el viernes."],
      ["You look tired. You ___ rest.", "should", ["must to", "have"], "daily", "Te ves cansado. Deberías descansar."],
      ["All employees ___ report incidents immediately.", "must", ["should to", "has to"], "hr", "Todos los empleados deben reportar los incidentes inmediatamente."],
      ["You ___ read the clause carefully before signing.", "should", ["must to", "has"], "law", "Deberías leer la cláusula con cuidado antes de firmar."],
      ["Inspectors ___ sign every report.", "have to", ["has to", "must to"], "qa", "Los inspectores tienen que firmar cada informe."],
    ],
    challenge: { en: "Write three rules of your workplace or home.", es: "Escribe tres reglas de tu trabajo o casa.", check: "\\b(must|have to|has to|should|mustn't)\\b" },
    errors: [],
  },
  {
    id: "g.present-perfect", level: "A2", title: "Present Perfect (experiences)", es: "Presente perfecto: experiencias", icon: "🌍",
    situation: { emoji: "🧭", en: "Sharing life experiences with a new friend.", es: "Compartiendo experiencias con un nuevo amigo." },
    examples: [["I've been to Mexico.", "He estado en México."], ["Have you ever worked abroad?", "¿Alguna vez has trabajado en el extranjero?"], ["She has never seen snow.", "Ella nunca ha visto nieve."], ["We've finished the first phase.", "Hemos terminado la primera fase."]],
    pattern: "have / has + past participle · ever / never",
    rule: {
      es: ["Experiencias de vida sin decir cuándo: I've visited Spain.", "Forma: have / has + participio (worked, been, seen, done, written).", "Ever (alguna vez) en preguntas; never (nunca) en afirmativas.", "Si dices cuándo (yesterday, in 2019), usa Past Simple: I visited Spain in 2019.", "Been to = he ido y vuelto."],
      en: ["Use it for life experiences without a specific time.", "have/has + past participle; ever in questions, never for 'no experience'.", "With a finished time (yesterday, in 2019) use the Past Simple."],
    },
    simple: { es: "Experiencias sin fecha: I have + participio.", en: "Experience, no date: have + past participle." },
    more: [["Have you ever been to an audit?", "¿Alguna vez has estado en una auditoría?"], ["I've never used this software.", "Nunca he usado este software."]],
    items: [
      ["I ___ to Mexico twice.", "have been", ["have go", "went to"], "travel", "He estado en México dos veces."],
      ["Have you ever ___ abroad?", "worked", ["work", "working"], "work", "¿Alguna vez has trabajado en el extranjero?"],
      ["She has ___ seen snow.", "never", ["ever", "not ever"], "daily", "Ella nunca ha visto nieve."],
      ["___ you ever used this software?", "Have", ["Did", "Do"], "eng", "¿Alguna vez has usado este software?"],
      ["He ___ worked in the oil industry for many years. (experiencia)", "has", ["have", "is"], "oil", "Él ha trabajado en la industria petrolera muchos años."],
      ["I visited London ___. (fecha concreta)", "in 2019", ["ever", "never"], "travel", "Visité Londres en 2019."],
      ["We have ___ three audits this year.", "done", ["did", "do"], "qa", "Hemos hecho tres auditorías este año."],
      ["Have you ever ___ a contract in English?", "negotiated", ["negotiate", "negotiating"], "law", "¿Alguna vez has negociado un contrato en inglés?"],
    ],
    challenge: { en: "Write three experiences you have had (and one you have never had).", es: "Escribe tres experiencias que has tenido (y una que nunca).", check: "\\b(have|has|'ve|'s)\\s+(never\\s+|ever\\s+)?\\w+(ed|en|wn|ne|t)\\b" },
    errors: [],
  },
  {
    id: "g.conjunctions", level: "A2", title: "Conjunctions", es: "Conectores: and, but, because, so", icon: "🔗",
    situation: { emoji: "✉️", en: "Writing a short message to explain a delay.", es: "Escribiendo un mensaje corto para explicar un retraso." },
    examples: [["I called him, but he didn't answer.", "Lo llamé, pero no contestó."], ["I'm late because the traffic was terrible.", "Llego tarde porque el tráfico estaba terrible."], ["It was raining, so we stayed inside.", "Estaba lloviendo, así que nos quedamos dentro."], ["We can meet on Monday or Tuesday.", "Podemos reunirnos el lunes o el martes."]],
    pattern: "and (+) · but (contrast) · or (option) · because (reason) · so (result)",
    rule: {
      es: ["And = y (añadir). But = pero (contraste). Or = o (opción).", "Because = porque (causa). So = así que / por eso (resultado).", "Because of + sustantivo: because of the rain.", "Although = aunque (más formal, B1)."],
      en: ["and adds, but contrasts, or offers options.", "because gives a reason; so gives a result.", "because of + noun."],
    },
    simple: { es: "Because = por qué pasó. So = qué pasó después.", en: "because → reason. so → result." },
    more: [["The flight was delayed because of the weather.", "El vuelo se retrasó por el clima."], ["The test failed, so we repeated it.", "La prueba falló, así que la repetimos."]],
    items: [
      ["I called him, ___ he didn't answer.", "but", ["so", "because"], "work", "Lo llamé, pero no contestó."],
      ["I'm late ___ the traffic was terrible.", "because", ["so", "but"], "daily", "Llego tarde porque el tráfico estaba terrible."],
      ["It was raining, ___ we stayed at the hotel.", "so", ["because", "but"], "travel", "Estaba lloviendo, así que nos quedamos en el hotel."],
      ["The flight was delayed because ___ the weather.", "of", ["to", "for"], "travel", "El vuelo se retrasó por el clima."],
      ["The pressure test failed, ___ we repeated it.", "so", ["but", "or"], "qa", "La prueba de presión falló, así que la repetimos."],
      ["Do you prefer a call ___ an email?", "or", ["and", "but"], "biz", "¿Prefieres una llamada o un correo?"],
      ["The candidate has experience ___ good references.", "and", ["but", "so"], "hr", "El candidato tiene experiencia y buenas referencias."],
    ],
    challenge: { en: "Explain why you are learning English. Use because and so.", es: "Explica por qué aprendes inglés. Usa because y so.", check: "\\bbecause\\b" },
    errors: [],
  },
];
