// Gramática B1 — contenido original. Explicaciones bilingües.
export default [
  {
    id: "g.present-perfect-2", level: "B1", title: "Present Perfect: for, since, just, already, yet", es: "Presente perfecto: for, since, just, already, yet", icon: "⏳",
    situation: { emoji: "📊", en: "A project update: what have we done so far?", es: "Actualización de proyecto: ¿qué hemos hecho hasta ahora?" },
    examples: [["I've worked here for five years.", "Trabajo aquí desde hace cinco años."], ["We've known each other since 2018.", "Nos conocemos desde 2018."], ["I've just sent the email.", "Acabo de enviar el correo."], ["Have you finished yet?", "¿Ya terminaste?"], ["They've already approved the budget.", "Ya aprobaron el presupuesto."]],
    pattern: "have/has + participle + for (period) / since (start) · just · already · yet",
    rule: {
      es: ["Situación que empezó en el pasado y sigue ahora: I've lived here for ten years (en español: «vivo aquí desde hace diez años»).", "For + duración (for two weeks); since + punto de inicio (since Monday, since 2020).", "Just = acabo de. Already = ya (afirmativa). Yet = ya (pregunta) / todavía (negativa, al final).", "Pregunta típica: How long have you worked here?"],
      en: ["Use it for situations that started in the past and continue now, and for recent results.", "for + a period; since + a starting point.", "just (very recently), already (sooner than expected), yet (questions/negatives, at the end)."],
    },
    simple: { es: "«Hace X que…» o «desde…» en inglés va con I have + participio.", en: "Started in the past, still true: have + past participle + for/since." },
    more: [["How long have you been an engineer?", "¿Cuánto tiempo llevas siendo ingeniero?"], ["We haven't received the certificate yet.", "Todavía no hemos recibido el certificado."]],
    items: [
      ["I've worked here ___ five years.", "for", ["since", "during"], "work", "Trabajo aquí desde hace cinco años."],
      ["We've known each other ___ 2018.", "since", ["for", "from"], "daily", "Nos conocemos desde 2018."],
      ["I've ___ sent the email. Check your inbox.", "just", ["yet", "since"], "work", "Acabo de enviar el correo. Revisa tu bandeja."],
      ["Have you finished the report ___?", "yet", ["already", "just"], "report", "¿Ya terminaste el informe?"],
      ["We haven't received the material certificate ___.", "yet", ["already", "since"], "qa", "Todavía no hemos recibido el certificado de material."],
      ["How long ___ you lived in Quito?", "have", ["do", "are"], "daily", "¿Cuánto tiempo llevas viviendo en Quito?"],
      ["The board has ___ approved the merger.", "already", ["yet", "since"], "law", "La junta ya aprobó la fusión."],
      ["She ___ in HR since 2021.", "has worked", ["works", "is working"], "hr", "Ella trabaja en RR. HH. desde 2021."],
      ["The platform has been offline ___ Tuesday.", "since", ["for", "from"], "oil", "La plataforma está fuera de servicio desde el martes."],
    ],
    challenge: { en: "Write about your job: how long you have done it and what you have already achieved.", es: "Escribe sobre tu trabajo: cuánto tiempo llevas y qué has logrado.", check: "\\b(have|has|'ve|'s)\\s+(already\\s+|just\\s+)?\\w+(ed|en|wn|ne|t)\\b" },
    errors: ["since-duration", "present-since"],
  },
  {
    id: "g.present-perfect-continuous", level: "B1", title: "Present Perfect Continuous", es: "Presente perfecto continuo", icon: "🔄",
    situation: { emoji: "😓", en: "Why are you tired? You've been working all day.", es: "¿Por qué estás cansado? Has estado trabajando todo el día." },
    examples: [["I've been waiting for an hour.", "Llevo una hora esperando."], ["She's been studying English since March.", "Ella estudia inglés desde marzo."], ["What have you been doing?", "¿Qué has estado haciendo?"], ["It's been raining all morning.", "Ha estado lloviendo toda la mañana."]],
    pattern: "have / has been + verb-ing",
    rule: {
      es: ["Actividad que empezó en el pasado y continúa (o acaba de terminar), con énfasis en la duración: I've been working all day.", "Forma: have / has + been + -ing.", "«Llevo X haciendo…» = I've been …ing for X.", "Con verbos de estado se usa el present perfect simple: I've known him for years."],
      en: ["Use it for ongoing activities with emphasis on duration, or recent activities with visible results.", "have/has been + -ing. State verbs use the simple form."],
    },
    simple: { es: "«Llevo … haciendo» = I've been + -ing.", en: "How long an activity has been going on: have been + -ing." },
    more: [["We've been testing the system for two weeks.", "Llevamos dos semanas probando el sistema."]],
    items: [
      ["I've been ___ for an hour.", "waiting", ["wait", "waited"], "travel", "Llevo una hora esperando."],
      ["She ___ English since March.", "has been studying", ["is studying", "studies"], "daily", "Ella estudia inglés desde marzo."],
      ["What have you ___ doing all day?", "been", ["being", "be"], "daily", "¿Qué has estado haciendo todo el día?"],
      ["We've been ___ the system for two weeks.", "testing", ["tested", "test"], "eng", "Llevamos dos semanas probando el sistema."],
      ["The team has been ___ the incident since Monday.", "investigating", ["investigated", "investigate"], "hr", "El equipo investiga el incidente desde el lunes."],
      ["I ___ him for ten years. (estado)", "have known", ["have been knowing", "know"], "daily", "Lo conozco desde hace diez años."],
      ["They've been ___ with the supplier all morning.", "negotiating", ["negotiated", "negotiate"], "biz", "Han estado negociando con el proveedor toda la mañana."],
    ],
    challenge: { en: "Describe something you have been doing lately and for how long.", es: "Describe algo que has estado haciendo últimamente y desde cuándo.", check: "\\b(have|has|'ve|'s) been \\w+ing\\b" },
    errors: ["present-since"],
  },
  {
    id: "g.past-perfect", level: "B1", title: "Past Perfect", es: "Pasado perfecto", icon: "⏮️",
    situation: { emoji: "🚆", en: "When we arrived, the train had already left.", es: "Cuando llegamos, el tren ya se había ido." },
    examples: [["When I arrived, the meeting had started.", "Cuando llegué, la reunión había empezado."], ["She had never flown before 2020.", "Ella nunca había volado antes de 2020."], ["We realized we had made a mistake.", "Nos dimos cuenta de que habíamos cometido un error."]],
    pattern: "had + past participle",
    rule: {
      es: ["Una acción anterior a otra acción pasada: When I arrived, they had left.", "Forma: had + participio (igual para todas las personas).", "Muy útil en informes de incidentes y narraciones."],
      en: ["Use it for an action that happened before another past action.", "had + past participle for all persons."],
    },
    simple: { es: "El «pasado del pasado»: había + -ado = had + participio.", en: "The earlier of two past actions: had + past participle." },
    more: [["The operator noticed that the valve had failed.", "El operador notó que la válvula había fallado."]],
    items: [
      ["When I arrived, the meeting ___ started.", "had", ["has", "was"], "meeting", "Cuando llegué, la reunión había empezado."],
      ["She had never ___ before 2020.", "flown", ["flew", "fly"], "travel", "Ella nunca había volado antes de 2020."],
      ["We realized we had ___ a mistake.", "made", ["make", "did"], "work", "Nos dimos cuenta de que habíamos cometido un error."],
      ["The operator noticed that the valve ___ failed.", "had", ["has", "was"], "oil", "El operador notó que la válvula había fallado."],
      ["By the time the auditor arrived, we ___ all the documents.", "had prepared", ["prepared", "have prepared"], "qa", "Cuando llegó el auditor, ya habíamos preparado todos los documentos."],
      ["The employee said he ___ the policy.", "had not read", ["has not read", "did not read"], "hr", "El empleado dijo que no había leído la política."],
    ],
    challenge: { en: "Describe a situation where something had already happened when you arrived.", es: "Describe una situación en la que algo ya había pasado cuando llegaste.", check: "\\bhad\\s+(already\\s+|never\\s+)?\\w+(ed|en|wn|ne|t)\\b" },
    errors: [],
  },
  {
    id: "g.first-conditional", level: "B1", title: "First Conditional", es: "Primer condicional (posibilidades reales)", icon: "🔀",
    situation: { emoji: "🌧️", en: "Planning an outdoor inspection with uncertain weather.", es: "Planificando una inspección al aire libre con clima incierto." },
    examples: [["If it rains, we'll postpone the inspection.", "Si llueve, posponemos la inspección."], ["If you send it today, I'll review it tomorrow.", "Si lo envías hoy, lo reviso mañana."], ["We won't finish unless we get more people.", "No terminaremos a menos que tengamos más gente."]],
    pattern: "If + present simple, will + base verb",
    rule: {
      es: ["Situaciones reales o probables en el futuro.", "If + presente simple, will + verbo: If it rains, we'll stay.", "¡No uses will después de if! (If it will rain ✗).", "Unless = if not. When = cuando es seguro que pasará."],
      en: ["Use it for real, likely future situations.", "If + present, will + base verb. No will after if.", "unless = if not."],
    },
    simple: { es: "Si pasa esto (presente), pasará aquello (will).", en: "If + present → will." },
    more: [["If the pressure drops, the system will shut down.", "Si baja la presión, el sistema se apagará."], ["If you accept the offer, we'll send the contract.", "Si acepta la oferta, le enviaremos el contrato."]],
    items: [
      ["If it ___, we'll postpone the inspection.", "rains", ["will rain", "rain"], "qa", "Si llueve, posponemos la inspección."],
      ["If you send it today, I ___ it tomorrow.", "will review", ["review", "reviewed"], "work", "Si lo envías hoy, lo reviso mañana."],
      ["If the pressure drops, the system ___ down.", "will shut", ["shuts will", "shut"], "oil", "Si baja la presión, el sistema se apagará."],
      ["We won't finish ___ we get more people.", "unless", ["if", "when"], "eng", "No terminaremos a menos que tengamos más gente."],
      ["If you accept the offer, we ___ you the contract.", "will send", ["send will", "sent"], "hr", "Si acepta la oferta, le enviaremos el contrato."],
      ["If the supplier ___ the deadline, we will apply the penalty clause.", "misses", ["will miss", "miss"], "law", "Si el proveedor incumple el plazo, aplicaremos la cláusula de penalidad."],
      ["If you ___ early, you'll get a good seat.", "arrive", ["will arrive", "arrived"], "travel", "Si llegas temprano, tendrás un buen asiento."],
    ],
    challenge: { en: "Write two 'if' sentences about your plans for this weekend.", es: "Escribe dos frases con if sobre tus planes del fin de semana.", check: "\\bif\\b[^.]*\\b(will|'ll|won't)\\b" },
    errors: ["if-will"],
  },
  {
    id: "g.second-conditional", level: "B1", title: "Second Conditional", es: "Segundo condicional (situaciones imaginarias)", icon: "💭",
    situation: { emoji: "🎰", en: "What would you do if you won the lottery?", es: "¿Qué harías si ganaras la lotería?" },
    examples: [["If I had more time, I would learn Italian.", "Si tuviera más tiempo, aprendería italiano."], ["If I were you, I'd accept the offer.", "Yo que tú, aceptaría la oferta."], ["What would you do if you lost your job?", "¿Qué harías si perdieras tu trabajo?"]],
    pattern: "If + past simple, would + base verb · If I were you…",
    rule: {
      es: ["Situaciones imaginarias o poco probables en el presente/futuro.", "If + pasado simple, would + verbo base.", "Con be se prefiere were para todas las personas: If I were you…", "If I were you, I'd… = yo que tú… (para dar consejos)."],
      en: ["Use it for imaginary or unlikely situations.", "If + past simple, would + base verb. If I were you… for advice."],
    },
    simple: { es: "Si tuviera… (pasado), haría… (would).", en: "Imagine: if + past → would." },
    more: [["If we had a bigger budget, we would hire more engineers.", "Si tuviéramos más presupuesto, contrataríamos más ingenieros."]],
    items: [
      ["If I ___ more time, I would learn Italian.", "had", ["have", "would have"], "daily", "Si tuviera más tiempo, aprendería italiano."],
      ["If I were you, I ___ accept the offer.", "would", ["will", "am"], "hr", "Yo que tú, aceptaría la oferta."],
      ["If I ___ you, I'd call the client.", "were", ["am", "would be"], "biz", "Yo que tú, llamaría al cliente."],
      ["What would you do if you ___ your job?", "lost", ["lose", "would lose"], "daily", "¿Qué harías si perdieras tu trabajo?"],
      ["If we had a bigger budget, we ___ more engineers.", "would hire", ["will hire", "hired"], "eng", "Si tuviéramos más presupuesto, contrataríamos más ingenieros."],
      ["If the contract ___ clearer, we wouldn't have this dispute.", "were", ["is", "will be"], "law", "Si el contrato fuera más claro, no tendríamos esta disputa."],
    ],
    challenge: { en: "What would you do if you could work in any country?", es: "¿Qué harías si pudieras trabajar en cualquier país?", check: "\\bwould\\b|'d\\b" },
    errors: [],
  },
  {
    id: "g.used-to", level: "B1", title: "Used to", es: "Used to: hábitos del pasado", icon: "📼",
    situation: { emoji: "🏫", en: "Remembering your first job.", es: "Recordando tu primer trabajo." },
    examples: [["I used to work in a bank.", "Antes trabajaba en un banco."], ["We didn't use to have computers.", "Antes no teníamos computadoras."], ["Did you use to live here?", "¿Vivías aquí antes?"]],
    pattern: "used to + base verb · didn't use to · Did … use to?",
    rule: {
      es: ["Hábitos o situaciones del pasado que ya no ocurren: I used to smoke.", "Negativo y pregunta: didn't use to / Did you use to (sin -d).", "No confundir con be used to + -ing (estar acostumbrado): I'm used to working late."],
      en: ["Past habits and states that are no longer true.", "didn't use to / Did … use to. Different from be used to + -ing."],
    },
    simple: { es: "«Antes solía…» = used to + verbo.", en: "Something true before, not now: used to + verb." },
    more: [["The plant used to produce 500 barrels a day.", "Antes la planta producía 500 barriles al día."]],
    items: [
      ["I ___ work in a bank.", "used to", ["use to", "was used to"], "work", "Antes trabajaba en un banco."],
      ["We didn't ___ have computers.", "use to", ["used to", "using"], "daily", "Antes no teníamos computadoras."],
      ["Did you ___ live here?", "use to", ["used to", "using to"], "daily", "¿Vivías aquí antes?"],
      ["The plant ___ produce 500 barrels a day.", "used to", ["was used to", "uses to"], "oil", "Antes la planta producía 500 barriles al día."],
      ["I'm used to ___ late. (costumbre actual)", "working", ["work", "worked"], "work", "Estoy acostumbrado a trabajar hasta tarde."],
    ],
    challenge: { en: "Write three things you used to do when you were a child.", es: "Escribe tres cosas que hacías de niño.", check: "\\bused to\\b" },
    errors: [],
  },
  {
    id: "g.passive", level: "B1", title: "Passive Voice", es: "Voz pasiva", icon: "🏭",
    situation: { emoji: "⚙️", en: "Describing a process in a technical report.", es: "Describiendo un proceso en un informe técnico." },
    examples: [["The equipment was inspected yesterday.", "El equipo fue inspeccionado ayer."], ["The candidate was interviewed yesterday.", "El candidato fue entrevistado ayer."], ["The agreement was signed yesterday.", "El acuerdo fue firmado ayer."], ["English is spoken here.", "Aquí se habla inglés."], ["The results will be published next week.", "Los resultados se publicarán la próxima semana."]],
    pattern: "be (am/is/are/was/were/will be/has been) + past participle (+ by…)",
    rule: {
      es: ["Se usa cuando importa la acción o el objeto, no quién la hace: The valve was replaced.", "Forma: be (en el tiempo que corresponda) + participio.", "Para decir quién: by + agente (The report was written by Ana).", "Muy común en informes, procedimientos, contratos y textos técnicos.", "«Se habla inglés» = English is spoken."],
      en: ["Use the passive when the action or object matters more than the doer.", "be + past participle; add by + agent only if relevant.", "Very common in reports, procedures and contracts."],
    },
    simple: { es: "El objeto pasa al principio: be + participio.", en: "Focus on the thing: be + past participle." },
    more: [["All welds must be inspected.", "Todas las soldaduras deben ser inspeccionadas."], ["The policy has been updated.", "La política ha sido actualizada."]],
    items: [
      ["The equipment ___ inspected yesterday.", "was", ["is", "were"], "eng", "El equipo fue inspeccionado ayer."],
      ["The candidate was ___ yesterday.", "interviewed", ["interview", "interviewing"], "hr", "El candidato fue entrevistado ayer."],
      ["The agreement ___ signed yesterday.", "was", ["were", "has"], "law", "El acuerdo fue firmado ayer."],
      ["English ___ spoken in many countries.", "is", ["are", "was"], "travel", "El inglés se habla en muchos países."],
      ["All welds must ___ inspected.", "be", ["been", "being"], "qa", "Todas las soldaduras deben ser inspeccionadas."],
      ["The policy ___ been updated.", "has", ["have", "was"], "hr", "La política ha sido actualizada."],
      ["The results will ___ published next week.", "be", ["been", "being"], "report", "Los resultados se publicarán la próxima semana."],
      ["The pipeline ___ built in 2015.", "was", ["is", "were"], "oil", "La tubería se construyó en 2015."],
      ["The report was written ___ the lead auditor.", "by", ["from", "for"], "qa", "El informe fue escrito por el auditor líder."],
    ],
    challenge: { en: "Describe a process at your work using the passive (e.g. 'The samples are tested…').", es: "Describe un proceso de tu trabajo con voz pasiva.", check: "\\b(is|are|was|were|be|been)\\s+\\w+(ed|en|wn|ne|t)\\b" },
    errors: [],
  },
  {
    id: "g.relative-clauses", level: "B1", title: "Relative Clauses", es: "Oraciones de relativo: who, which, that, where", icon: "🧷",
    situation: { emoji: "🔎", en: "Explaining which document or person you mean.", es: "Explicando a qué documento o persona te refieres." },
    examples: [["The engineer who designed the bridge is here.", "El ingeniero que diseñó el puente está aquí."], ["This is the report that I mentioned.", "Este es el informe que mencioné."], ["The plant where I work is near the coast.", "La planta donde trabajo está cerca de la costa."], ["The supplier whose offer was the lowest won.", "Ganó el proveedor cuya oferta fue la más baja."]],
    pattern: "who (people) · which (things) · that (people/things) · where (places) · whose (possession)",
    rule: {
      es: ["Who = que/quien (personas). Which = que/el cual (cosas). That = que (personas o cosas, informal).", "Where = donde. Whose = cuyo/cuya.", "Si el relativo es objeto se puede omitir: the report (that) I sent.", "Con comas (información extra) no se usa that: My boss, who is from Chile, …"],
      en: ["who for people, which for things, that for both (defining clauses).", "where for places, whose for possession.", "Object relative pronouns can be omitted. No that in non-defining clauses."],
    },
    simple: { es: "Persona → who. Cosa → which/that. Lugar → where.", en: "people → who, things → which/that, places → where." },
    more: [["The clause which covers liability is 12.3.", "La cláusula que cubre la responsabilidad es la 12.3."]],
    items: [
      ["The engineer ___ designed the bridge is here.", "who", ["which", "where"], "eng", "El ingeniero que diseñó el puente está aquí."],
      ["This is the report ___ I mentioned.", "that", ["who", "where"], "report", "Este es el informe que mencioné."],
      ["The plant ___ I work is near the coast.", "where", ["which", "who"], "oil", "La planta donde trabajo está cerca de la costa."],
      ["The supplier ___ offer was the lowest won the contract.", "whose", ["who", "which"], "biz", "Ganó el proveedor cuya oferta fue la más baja."],
      ["The clause ___ covers liability is 12.3.", "which", ["who", "where"], "law", "La cláusula que cubre la responsabilidad es la 12.3."],
      ["We need someone ___ speaks English fluently.", "who", ["which", "whose"], "hr", "Necesitamos a alguien que hable inglés con fluidez."],
      ["The hotel ___ we stayed was excellent.", "where", ["which", "who"], "travel", "El hotel donde nos alojamos fue excelente."],
    ],
    challenge: { en: "Describe a person and a place that are important to you using who and where.", es: "Describe una persona y un lugar importantes para ti usando who y where.", check: "\\b(who|which|that|where|whose)\\b" },
    errors: [],
  },
  {
    id: "g.gerunds-infinitives", level: "B1", title: "Gerunds & Infinitives", es: "Gerundio (-ing) e infinitivo (to)", icon: "🎯",
    situation: { emoji: "🗣️", en: "Talking about your career plans and preferences.", es: "Hablando de tus planes de carrera y preferencias." },
    examples: [["I enjoy working with people.", "Disfruto trabajar con gente."], ["I want to improve my English.", "Quiero mejorar mi inglés."], ["She's interested in learning Python.", "Ella está interesada en aprender Python."], ["I'd like you to send the report.", "Me gustaría que enviaras el informe."], ["Smoking is not allowed.", "No se permite fumar."]],
    pattern: "enjoy / finish / avoid / suggest + -ing · want / need / decide / plan + to · preposition + -ing",
    rule: {
      es: ["Algunos verbos van con -ing: enjoy, finish, avoid, suggest, consider, mind, keep.", "Otros con to + verbo: want, need, decide, plan, hope, agree, expect, would like.", "Después de preposición siempre -ing: interested in learning, good at solving, before leaving.", "«Quiero que tú…» = I want you to… (no «I want that you…»).", "Para expresar propósito: to + verbo (I study to get a better job)."],
      en: ["Some verbs take -ing (enjoy, avoid, finish); others take to-infinitive (want, need, decide).", "After prepositions use -ing.", "want / would like + object + to-infinitive."],
    },
    simple: { es: "Después de preposición, -ing. Después de want/need/decide, to.", en: "preposition + -ing; want/need + to." },
    more: [["We avoided making the same mistake.", "Evitamos cometer el mismo error."], ["I'm looking forward to meeting you.", "Tengo muchas ganas de conocerte."]],
    items: [
      ["I enjoy ___ with people.", "working", ["to work", "work"], "hr", "Disfruto trabajar con gente."],
      ["I want ___ my English.", "to improve", ["improving", "improve"], "daily", "Quiero mejorar mi inglés."],
      ["She's interested in ___ Python.", "learning", ["to learn", "learn"], "work", "Ella está interesada en aprender Python."],
      ["I'd like you ___ the report today.", "to send", ["send", "sending"], "biz", "Me gustaría que enviaras el informe hoy."],
      ["We should avoid ___ the same mistake.", "making", ["to make", "make"], "qa", "Deberíamos evitar cometer el mismo error."],
      ["I'm looking forward to ___ you.", "meeting", ["meet", "to meet"], "biz", "Tengo muchas ganas de conocerte."],
      ["They decided ___ the contract.", "to terminate", ["terminating", "terminate"], "law", "Decidieron rescindir el contrato."],
      ["I study English ___ a better job.", "to get", ["for to get", "for get"], "daily", "Estudio inglés para conseguir un mejor trabajo."],
    ],
    challenge: { en: "Write about what you enjoy doing and what you want to do in the future.", es: "Escribe qué disfrutas hacer y qué quieres hacer en el futuro.", check: "\\b(enjoy|like|love)\\s+\\w+ing\\b|\\bwant to\\b" },
    errors: ["want-that", "for-to"],
  },
  {
    id: "g.phrasal-verbs", level: "B1", title: "Phrasal Verbs at work", es: "Phrasal verbs en el trabajo", icon: "🧗",
    situation: { emoji: "💼", en: "Following up after a meeting.", es: "Haciendo seguimiento después de una reunión." },
    examples: [["Can you set up a meeting?", "¿Puedes organizar una reunión?"], ["I'll follow up with the client.", "Haré seguimiento con el cliente."], ["We need to figure out the problem.", "Tenemos que averiguar el problema."], ["The meeting was called off.", "La reunión fue cancelada."], ["Please fill in the form.", "Por favor llena el formulario."]],
    pattern: "verb + particle (up, out, off, on, in…) = new meaning",
    rule: {
      es: ["Un phrasal verb es verbo + partícula con un significado nuevo: call off = cancelar.", "Muchos se pueden separar con un objeto: turn the machine off / turn it off (con pronombre, siempre separado).", "Son muy frecuentes en el inglés hablado; en textos formales a veces se prefiere un verbo latino (cancel, investigate, postpone)."],
      en: ["Verb + particle creates a new meaning.", "Separable phrasal verbs: put the pronoun in the middle (turn it off).", "Common in speech; formal writing may prefer single verbs."],
    },
    simple: { es: "Verbo + palabrita = significado nuevo. Apréndelos como vocabulario.", en: "Learn them as new words: call off = cancel." },
    more: [["Let's go over the figures.", "Revisemos las cifras."], ["We ran out of spare parts.", "Nos quedamos sin repuestos."]],
    items: [
      ["Can you ___ up a meeting with the client?", "set", ["put", "make"], "meeting", "¿Puedes organizar una reunión con el cliente?"],
      ["I'll follow ___ with the supplier tomorrow.", "up", ["on", "out"], "biz", "Haré seguimiento con el proveedor mañana."],
      ["We need to figure ___ what caused the failure.", "out", ["up", "off"], "eng", "Tenemos que averiguar qué causó la falla."],
      ["The meeting was called ___ because of the storm.", "off", ["out", "up"], "meeting", "La reunión fue cancelada por la tormenta."],
      ["Please fill ___ the application form.", "in", ["on", "off"], "hr", "Por favor llena el formulario de solicitud."],
      ["We ran ___ of spare parts.", "out", ["off", "up"], "oil", "Nos quedamos sin repuestos."],
      ["Let's go ___ the findings before the closing meeting.", "over", ["off", "up"], "qa", "Revisemos los hallazgos antes de la reunión de cierre."],
      ["Please turn ___ the pump before maintenance.", "off", ["out", "down"], "eng", "Por favor apaga la bomba antes del mantenimiento."],
    ],
    challenge: { en: "Write a short message using follow up, set up and figure out.", es: "Escribe un mensaje corto usando follow up, set up y figure out.", check: "\\b(follow|set|figure|call|fill|run|go|turn)\\s+(\\w+\\s+)?(up|out|off|in|over)\\b" },
    errors: [],
  },
];
