// Ampliación B2–C2: nuevos temas + ítems adicionales para los temas avanzados existentes. Contenido original.

// Ítems extra para temas existentes (se suman a sus ítems originales)
export const EXTRA_ITEMS = {
  "g.reported-speech": [
    ["He told me ___ wait outside.", "to", ["that", "for"], "work", "Me dijo que esperara afuera."],
    ["She asked me what time the meeting ___.", "started", ["did start", "does it start"], "meeting", "Me preguntó a qué hora empezaba la reunión."],
    ["The manager said the report ___ ready the next day.", "would be", ["will be", "is"], "report", "El gerente dijo que el informe estaría listo al día siguiente."],
    ["They told us they ___ the contract the week before.", "had signed", ["signed", "have signed"], "law", "Nos dijeron que habían firmado el contrato la semana anterior."],
    ["The auditor asked ___ we kept training records.", "whether", ["that", "what"], "qa", "El auditor preguntó si guardábamos registros de capacitación."],
    ["The candidate said she ___ start in two weeks.", "could", ["can", "will can"], "hr", "La candidata dijo que podía empezar en dos semanas."],
  ],
  "g.third-conditional": [
    ["If you ___ me, I would have helped you.", "had asked", ["asked", "would ask"], "work", "Si me hubieras preguntado, te habría ayudado."],
    ["We ___ the flight if we had left earlier.", "wouldn't have missed", ["didn't miss", "won't miss"], "travel", "No habríamos perdido el vuelo si hubiéramos salido antes."],
    ["If the contract had been clearer, there ___ no dispute.", "would have been", ["would be", "had been"], "law", "Si el contrato hubiera sido más claro, no habría habido disputa."],
    ["She might have got the job if she ___ better.", "had prepared", ["prepared", "would prepare"], "hr", "Quizás habría conseguido el trabajo si se hubiera preparado mejor."],
    ["If they had tested the software, they ___ the bug.", "would have found", ["would find", "found"], "eng", "Si hubieran probado el software, habrían encontrado el error."],
    ["I ___ you if I had known you were in town.", "would have called", ["called", "will call"], "daily", "Te habría llamado si hubiera sabido que estabas en la ciudad."],
  ],
  "g.wish": [
    ["I wish I ___ afford a new car.", "could", ["can", "will"], "daily", "Ojalá pudiera comprarme un auto nuevo."],
    ["She wishes she ___ accepted the other offer.", "had", ["has", "would"], "hr", "Ella desearía haber aceptado la otra oferta."],
    ["I wish it ___ raining. I want to go out.", "would stop", ["stops", "stopped to"], "daily", "Ojalá dejara de llover."],
    ["If only I ___ his advice!", "had followed", ["followed", "follow"], "work", "¡Si tan solo hubiera seguido su consejo!"],
    ["I wish we ___ more engineers on this project.", "had", ["have", "would have"], "eng", "Ojalá tuviéramos más ingenieros en este proyecto."],
    ["He wishes he ___ so much at the party last night.", "hadn't eaten", ["didn't eat", "wouldn't eat"], "daily", "Desearía no haber comido tanto anoche."],
  ],
  "g.modals-deduction": [
    ["She isn't answering. She ___ be in a meeting.", "might", ["must not", "can"], "work", "No contesta. Puede que esté en una reunión."],
    ["You've been travelling all day. You ___ be exhausted.", "must", ["can't", "might not"], "travel", "Has viajado todo el día. Debes de estar agotado."],
    ["He ___ have seen the email. He was on holiday.", "can't", ["must", "should"], "work", "No puede haber visto el correo. Estaba de vacaciones."],
    ["The test results look strange. The sample ___ have been contaminated.", "may", ["can't", "must not"], "qa", "Puede que la muestra se haya contaminado."],
    ["The lights are on. Someone ___ be in the office.", "must", ["can't", "mustn't"], "work", "Las luces están encendidas. Debe de haber alguien."],
  ],
  "g.linking": [
    ["The project was delayed. ___, it stayed within budget.", "Nevertheless", ["Because", "Although"], "report", "El proyecto se retrasó. Sin embargo, no superó el presupuesto."],
    ["___ being tired, she finished the report.", "Despite", ["Although", "However"], "work", "A pesar de estar cansada, terminó el informe."],
    ["We need to cut costs; ___, we must protect quality.", "at the same time", ["because of", "despite"], "biz", "Tenemos que reducir costes; al mismo tiempo, proteger la calidad."],
    ["Sales increased. ___, profits fell because of higher costs.", "However", ["Although", "Despite"], "report", "Las ventas subieron. Sin embargo, las ganancias bajaron."],
    ["The procedure is simple. ___, it saves time.", "Moreover", ["Whereas", "Despite"], "qa", "El procedimiento es sencillo. Además, ahorra tiempo."],
    ["___ the fact that it rained, the inspection went ahead.", "Despite", ["Although", "However"], "oil", "A pesar de que llovió, la inspección se realizó."],
  ],
  "g.causative": [
    ["I'm going to have my eyes ___ next week.", "tested", ["test", "to test"], "daily", "La próxima semana me voy a hacer un examen de la vista."],
    ["She got her laptop ___ by IT.", "fixed", ["fix", "fixing"], "work", "IT le arregló la laptop."],
    ["We'll have the technician ___ the pump tomorrow.", "check", ["checked", "to check"], "oil", "Haremos que el técnico revise la bomba mañana."],
    ["Where do you get your hair ___?", "cut", ["cutting", "to cut"], "daily", "¿Dónde te cortas el pelo?"],
    ["The company had the documents ___ by a certified translator.", "translated", ["translate", "translating"], "law", "La empresa hizo traducir los documentos por un traductor certificado."],
  ],
  "g.inversion": [
    ["Seldom ___ such a clear presentation.", "have I heard", ["I have heard", "I heard"], "meeting", "Rara vez he escuchado una presentación tan clara."],
    ["No sooner ___ arrived than the meeting started.", "had we", ["we had", "did we"], "meeting", "Apenas llegamos, empezó la reunión."],
    ["Only after the audit ___ the problem.", "did we realise", ["we realised", "we did realise"], "qa", "Solo después de la auditoría nos dimos cuenta del problema."],
    ["___ I known about the delay, I would have told you.", "Had", ["If", "Have"], "work", "Si hubiera sabido del retraso, te lo habría dicho."],
    ["Hardly ___ started when the power went off.", "had we", ["we had", "did we"], "eng", "Apenas habíamos empezado cuando se fue la luz."],
  ],
  "g.mixed-conditionals": [
    ["If I spoke Mandarin, I ___ that job in Shanghai last year.", "would have taken", ["would take", "took"], "work", "Si hablara mandarín, habría aceptado ese trabajo en Shanghái."],
    ["If she hadn't missed the flight, she ___ here now.", "would be", ["would have been", "is"], "travel", "Si no hubiera perdido el vuelo, ahora estaría aquí."],
    ["You can use the lab ___ you follow the safety rules.", "as long as", ["unless", "despite"], "qa", "Puedes usar el laboratorio siempre que sigas las normas."],
    ["___ the supplier refuses, what's our plan B?", "Supposing", ["Provided", "Unless"], "biz", "Suponiendo que el proveedor se niegue, ¿cuál es el plan B?"],
    ["Hurry up, ___ we'll miss the train.", "otherwise", ["unless", "provided"], "travel", "Date prisa; si no, perderemos el tren."],
  ],
  "g.cleft": [
    ["___ I like about this job is the variety.", "What", ["That", "It"], "work", "Lo que me gusta de este trabajo es la variedad."],
    ["It was in 2019 ___ we opened our first office.", "that", ["what", "when it"], "biz", "Fue en 2019 cuando abrimos nuestra primera oficina."],
    ["All I need ___ a quiet place to work.", "is", ["it is", "are"], "work", "Lo único que necesito es un lugar tranquilo."],
    ["It's not the price ___ worries me; it's the delivery time.", "that", ["what", "which it"], "biz", "No es el precio lo que me preocupa; es el plazo."],
    ["What happened ___ that the system crashed.", "was", ["it was", "is that"], "eng", "Lo que pasó fue que el sistema se cayó."],
  ],
  "g.participle-clauses": [
    ["___ the email, she called the client immediately.", "Having read", ["Read", "Have read"], "work", "Tras leer el correo, llamó al cliente."],
    ["The report ___ yesterday contains several errors.", "published", ["publishing", "having published"], "report", "El informe publicado ayer contiene varios errores."],
    ["___ by the results, the team celebrated.", "Encouraged", ["Encouraging", "Having encourage"], "biz", "Animado por los resultados, el equipo celebró."],
    ["Employees ___ overtime must record their hours.", "working", ["worked", "having work"], "hr", "Los empleados que hagan horas extra deben registrarlas."],
    ["Not ___ what to do, he asked his supervisor.", "knowing", ["known", "having know"], "work", "Sin saber qué hacer, preguntó a su supervisor."],
  ],
  "g.academic": [
    ["These findings ___ that further research is needed.", "indicate", ["are indicating that", "indicates"], "report", "Estos hallazgos indican que se necesita más investigación."],
    ["It is widely ___ that exercise improves mental health.", "accepted", ["accept", "accepting"], "report", "Se acepta ampliamente que el ejercicio mejora la salud mental."],
    ["The data ___ to support the hypothesis.", "appear", ["appears it", "appearing"], "report", "Los datos parecen apoyar la hipótesis."],
    ["The new method is ___ more efficient than the old one.", "arguably", ["argue", "arguing"], "eng", "El nuevo método es posiblemente más eficiente."],
    ["There is ___ evidence to suggest a link.", "some", ["any", "much of"], "report", "Hay ciertos indicios de una relación."],
  ],
  "g.advanced-writing": [
    ["Of particular concern ___ the lack of maintenance records.", "is", ["it is", "are"], "qa", "Es especialmente preocupante la falta de registros de mantenimiento."],
    ["The ___ of the plant took three years. (construct)", "construction", ["constructing of", "construct"], "oil", "La construcción de la planta tomó tres años."],
    ["So complex ___ the problem that we hired consultants.", "was", ["it was", "were"], "biz", "Tan complejo era el problema que contratamos consultores."],
    ["There was a significant ___ in costs. (reduce)", "reduction", ["reducing", "reduce"], "report", "Hubo una reducción significativa de costes."],
    ["___ the company to expand, it would need more capital.", "Were", ["If", "Should"], "biz", "Si la empresa se expandiera, necesitaría más capital."],
  ],
  "g.subjunctive": [
    ["The doctor recommended that he ___ more rest.", "get", ["gets", "got"], "daily", "El médico recomendó que descansara más."],
    ["It is vital that the valve ___ checked daily.", "be", ["is", "was"], "oil", "Es vital que la válvula se revise a diario."],
    ["The board demanded that the CEO ___.", "resign", ["resigns", "resigned"], "law", "La junta exigió que el CEO renunciara."],
    ["We suggest that the meeting ___ postponed.", "be", ["is", "will be"], "meeting", "Sugerimos que se posponga la reunión."],
    ["It is essential that every visitor ___ a helmet.", "wear", ["wears", "wore"], "oil", "Es esencial que todo visitante use casco."],
  ],
};

const T = (o) => o;

// Nuevos temas B2–C2
export const NEW_TOPICS = [
  T({
    id: "g.future-adv", level: "B2", title: "Future Continuous & Future Perfect", es: "Futuro continuo y futuro perfecto", icon: "🚀",
    situation: { emoji: "📆", en: "Planning a long project: where will we be in six months?", es: "Planificando un proyecto largo: ¿dónde estaremos en seis meses?" },
    examples: [["This time tomorrow I'll be flying to Madrid.", "Mañana a esta hora estaré volando a Madrid."], ["By June we'll have finished the installation.", "Para junio habremos terminado la instalación."], ["Will you be using the car tonight?", "¿Vas a usar el auto esta noche?"], ["By 2030 I'll have been working here for ten years.", "Para 2030 llevaré diez años trabajando aquí."]],
    pattern: "will be + -ing · will have + participle · will have been + -ing",
    rule: { en: ["Future continuous: an action in progress at a future moment (This time next week I'll be…).", "Future perfect: an action completed before a future moment (By Friday, I'll have…).", "Future perfect continuous: duration up to a future moment.", "Will you be …ing? is a polite way to ask about plans."], es: ["Futuro continuo = estaré haciendo. Futuro perfecto = habré hecho (antes de un momento futuro)."] },
    simple: { es: "Estaré + -ando = will be -ing. Habré + -ado = will have + participio.", en: "will be doing = in progress; will have done = finished before then." },
    more: [["Don't call at 8 — we'll be having dinner.", "No llames a las 8: estaremos cenando."], ["The shipment will have arrived by then.", "El envío habrá llegado para entonces."]],
    items: [
      ["This time tomorrow I ___ to Madrid.", "will be flying", ["will fly", "will have flown"], "travel", "Mañana a esta hora estaré volando a Madrid."],
      ["By June we ___ the installation.", "will have finished", ["will be finishing", "finish"], "eng", "Para junio habremos terminado la instalación."],
      ["Don't call at eight. We ___ dinner.", "will be having", ["will have had", "have"], "daily", "No llames a las ocho. Estaremos cenando."],
      ["By the time you arrive, the meeting ___.", "will have started", ["will be starting", "starts"], "meeting", "Cuando llegues, la reunión ya habrá empezado."],
      ["___ you be using the projector this afternoon?", "Will", ["Do", "Are"], "work", "¿Vas a usar el proyector esta tarde?"],
      ["By 2030 I ___ here for ten years.", "will have been working", ["will be working", "work"], "work", "Para 2030 llevaré diez años trabajando aquí."],
      ["The auditors ___ our records all next week.", "will be reviewing", ["will have reviewed", "review"], "qa", "Los auditores estarán revisando nuestros registros toda la próxima semana."],
      ["By the end of the year, HR ___ 50 new employees.", "will have hired", ["will be hiring", "hires"], "hr", "Para fin de año, RR. HH. habrá contratado a 50 empleados."],
    ],
    challenge: { en: "Describe where you will be and what you will have achieved in five years.", es: "Describe dónde estarás y qué habrás logrado en cinco años.", check: "\\bwill (be \\w+ing|have \\w+)" },
    errors: [],
  }),
  T({
    id: "g.modals-past", level: "B2", title: "Past modals: should have, could have", es: "Modales en pasado: should have, could have", icon: "🔙",
    situation: { emoji: "🧾", en: "Reviewing what went wrong in a project.", es: "Analizando qué salió mal en un proyecto." },
    examples: [["We should have tested it earlier.", "Deberíamos haberlo probado antes."], ["You could have told me!", "¡Me lo podrías haber dicho!"], ["They needn't have waited.", "No hacía falta que esperaran."], ["I shouldn't have sent that email.", "No debería haber enviado ese correo."]],
    pattern: "should / shouldn't / could / needn't / would + have + past participle",
    rule: { en: ["should have + pp: criticism or regret about the past (it was a good idea, but it didn't happen).", "shouldn't have + pp: it happened, but it was a bad idea.", "could have + pp: a past possibility that didn't happen.", "needn't have + pp: it was done, but it wasn't necessary."], es: ["should have = debería haber; could have = podría haber; needn't have = no hacía falta."] },
    simple: { es: "Hablar de lo que debió o pudo pasar: modal + have + participio.", en: "Talk about the past that could/should have been: modal + have + past participle." },
    more: [["You could have been hurt.", "Podrías haberte lastimado."], ["We would have finished if we had had more time.", "Habríamos terminado si hubiéramos tenido más tiempo."]],
    items: [
      ["We ___ tested the valve before installation.", "should have", ["should", "must"], "eng", "Deberíamos haber probado la válvula antes de instalarla."],
      ["You ___ told me about the meeting!", "could have", ["can have", "could"], "work", "¡Me podrías haber avisado de la reunión!"],
      ["I ___ sent that email. It caused problems.", "shouldn't have", ["mustn't have", "couldn't"], "work", "No debería haber enviado ese correo."],
      ["They needn't have ___. The flight was delayed.", "hurried", ["hurry", "hurrying"], "travel", "No hacía falta que se apuraran. El vuelo se retrasó."],
      ["The accident ___ been avoided with better training.", "could have", ["should", "can have"], "oil", "El accidente podría haberse evitado con mejor capacitación."],
      ["The inspector should ___ the certificate.", "have checked", ["checked", "has checked"], "qa", "El inspector debería haber revisado el certificado."],
      ["She ___ applied for the job. She was perfect for it.", "should have", ["should", "would"], "hr", "Debería haberse postulado al trabajo."],
    ],
    challenge: { en: "Write two things you should have done differently last year.", es: "Escribe dos cosas que deberías haber hecho diferente el año pasado.", check: "\\b(should|could|shouldn't|needn't) have\\b" },
    errors: [],
  }),
  T({
    id: "g.passive-adv", level: "B2", title: "Advanced passive: it is said that…", es: "Pasiva avanzada: se dice que…", icon: "📰",
    situation: { emoji: "🗞️", en: "Reporting news and information formally.", es: "Informando noticias e información de forma formal." },
    examples: [["It is said that the company will expand.", "Se dice que la empresa se expandirá."], ["The CEO is believed to be resigning.", "Se cree que el CEO va a renunciar."], ["The bridge is thought to have been built in 1900.", "Se cree que el puente se construyó en 1900."], ["The report needs to be checked.", "El informe tiene que revisarse."]],
    pattern: "It is said/believed/reported that… · Subject + is said/believed + to + verb / to have + pp",
    rule: { en: ["Impersonal passive: It is said / believed / reported / expected that + clause.", "Personal passive: Subject + is said / believed + to-infinitive (present) or to have + pp (past).", "Passive with modals and perfect: must be done, should have been done, has been done.", "Passive infinitive and gerund: needs to be repaired, avoid being seen."], es: ["«Se dice que» = It is said that… o Sujeto + is said to…"] },
    simple: { es: "Para noticias y rumores formales: It is said that… / X is believed to…", en: "Formal reporting: It is said that… / X is said to…" },
    more: [["Prices are expected to rise.", "Se espera que los precios suban."]],
    items: [
      ["It ___ that the plant will close next year.", "is said", ["says", "is saying"], "oil", "Se dice que la planta cerrará el próximo año."],
      ["The new model is expected ___ launched in May.", "to be", ["being", "be"], "biz", "Se espera que el nuevo modelo se lance en mayo."],
      ["The fire is thought to ___ by a faulty cable.", "have been caused", ["be caused", "has been caused"], "eng", "Se cree que el incendio fue causado por un cable defectuoso."],
      ["All visitors must ___ at reception.", "be registered", ["register by", "been registered"], "hr", "Todos los visitantes deben ser registrados en recepción."],
      ["The documents should ___ before the audit.", "have been sent", ["be sending", "sent"], "qa", "Los documentos deberían haberse enviado antes de la auditoría."],
      ["The suspect is reported ___ the country.", "to have left", ["leaving", "that left"], "law", "Se informa que el sospechoso ha salido del país."],
      ["I don't like ___ what to do.", "being told", ["be told", "telling"], "work", "No me gusta que me digan qué hacer."],
    ],
    challenge: { en: "Report a piece of news formally using 'It is believed that…' or 'X is said to…'.", es: "Informa una noticia formalmente con «It is believed that…» o «X is said to…».", check: "\\b(it is (said|believed|reported|expected|thought)|is (said|believed|reported|expected|thought) to)\\b" },
    errors: [],
  }),
  T({
    id: "g.relative-adv", level: "B2", title: "Advanced relative clauses", es: "Relativas avanzadas: whom, preposiciones, reducidas", icon: "🔗",
    situation: { emoji: "📄", en: "Writing precise, formal descriptions.", es: "Escribiendo descripciones precisas y formales." },
    examples: [["The person to whom I spoke was very helpful.", "La persona con quien hablé fue muy amable."], ["The contract, which was signed in May, expires in 2027.", "El contrato, que se firmó en mayo, vence en 2027."], ["Several employees, most of whom work remotely, attended.", "Asistieron varios empleados, la mayoría de los cuales trabaja en remoto."], ["The candidates interviewed yesterday were excellent.", "Los candidatos entrevistados ayer fueron excelentes."]],
    pattern: "preposition + whom/which · some/most/all of whom/which · reduced clauses (-ing / -ed)",
    rule: { en: ["Formal: preposition + whom / which (the company for which I work). Informal: preposition at the end (the company I work for).", "Quantifier + of whom / of which: most of whom, some of which.", "which can refer to a whole clause: He arrived late, which annoyed everyone.", "Reduced relative clauses: the man sitting there (= who is sitting), the car made in Japan (= which was made)."], es: ["«Con quien» formal = with whom. «La mayoría de los cuales» = most of whom / which."] },
    simple: { es: "En inglés formal, la preposición va antes de whom/which.", en: "Formal style: preposition + whom / which." },
    more: [["She passed the exam, which surprised nobody.", "Aprobó el examen, lo cual no sorprendió a nadie."]],
    items: [
      ["The person to ___ I spoke was very helpful.", "whom", ["who", "which"], "work", "La persona con quien hablé fue muy amable."],
      ["The company for ___ she works is based in Chile.", "which", ["that", "whom"], "biz", "La empresa para la que trabaja está en Chile."],
      ["We interviewed ten candidates, most of ___ had experience.", "whom", ["them", "who"], "hr", "Entrevistamos a diez candidatos, la mayoría con experiencia."],
      ["He arrived late, ___ annoyed the client.", "which", ["that", "what"], "meeting", "Llegó tarde, lo cual molestó al cliente."],
      ["The pipes ___ in the warehouse are new.", "stored", ["storing", "which stored"], "oil", "Las tuberías almacenadas en el depósito son nuevas."],
      ["Anyone ___ to attend must register.", "wishing", ["wished", "wishes"], "hr", "Quien desee asistir debe registrarse."],
      ["The clauses, some of ___ are unclear, need revision.", "which", ["them", "what"], "law", "Las cláusulas, algunas de las cuales no están claras, necesitan revisión."],
    ],
    challenge: { en: "Describe your team using 'most of whom' or 'some of which'.", es: "Describe tu equipo usando «most of whom» o «some of which».", check: "\\b(of whom|of which|to whom|for which|with whom)\\b" },
    errors: [],
  }),
  T({
    id: "g.emphasis", level: "B2", title: "Emphasis: so, such, do/does", es: "Énfasis: so, such, do / does", icon: "❗",
    situation: { emoji: "🎤", en: "Expressing strong feelings and correcting misunderstandings.", es: "Expresar sentimientos fuertes y aclarar malentendidos." },
    examples: [["It was so cold that we stayed inside.", "Hacía tanto frío que nos quedamos dentro."], ["It was such a good presentation!", "¡Fue una presentación tan buena!"], ["I do understand your concern.", "De verdad entiendo tu preocupación."], ["She did send the email — I saw it.", "Sí envió el correo; yo lo vi."]],
    pattern: "so + adjective/adverb · such (a/an) + (adjective) + noun · do/does/did + base verb",
    rule: { en: ["so + adjective / adverb: so expensive, so quickly.", "such + (a/an) + adjective + noun: such a big mistake, such good results.", "so … that / such … that for results.", "Emphatic do / does / did + base verb to insist or contrast: I do like it."], es: ["So + adjetivo; such + sustantivo. Do/does/did para enfatizar."] },
    simple: { es: "So va con adjetivos; such va con sustantivos.", en: "so + adjective, such + noun." },
    more: [["They were such kind people.", "Eran personas tan amables."]],
    items: [
      ["The presentation was ___ good that everyone clapped.", "so", ["such", "such a"], "meeting", "La presentación fue tan buena que todos aplaudieron."],
      ["It was ___ difficult exam!", "such a", ["so", "such"], "daily", "¡Fue un examen tan difícil!"],
      ["I ___ understand your concern, but we must follow the policy.", "do", ["am", "did"], "hr", "Entiendo tu preocupación, pero debemos seguir la política."],
      ["They made ___ progress that the client was impressed.", "such", ["so", "such a"], "biz", "Hicieron tanto progreso que el cliente quedó impresionado."],
      ["She ___ send the report — I have it here.", "did", ["does", "was"], "work", "Sí envió el informe; lo tengo aquí."],
      ["The pump runs ___ quietly that you can't hear it.", "so", ["such", "such a"], "eng", "La bomba funciona tan silenciosamente que no se oye."],
    ],
    challenge: { en: "Describe a great experience using 'so…that' and 'such a…'.", es: "Describe una gran experiencia usando «so…that» y «such a…».", check: "\\b(so \\w+ that|such an? )" },
    errors: [],
  }),
  T({
    id: "g.reporting-verbs", level: "C1", title: "Reporting verbs", es: "Verbos de reporte: suggest, warn, deny…", icon: "📢",
    situation: { emoji: "📝", en: "Writing precise meeting minutes.", es: "Redactando actas precisas." },
    examples: [["She suggested postponing the launch.", "Sugirió posponer el lanzamiento."], ["He warned us not to touch the valve.", "Nos advirtió que no tocáramos la válvula."], ["The supplier denied receiving the order.", "El proveedor negó haber recibido el pedido."], ["They accused him of leaking the data.", "Lo acusaron de filtrar los datos."]],
    pattern: "verb + -ing · verb + to · verb + object + to · verb + preposition + -ing · verb + that",
    rule: { en: ["+ -ing: suggest, deny, admit, recommend, regret (She suggested waiting).", "+ to-infinitive: agree, refuse, offer, promise, threaten (He refused to sign).", "+ object + to: advise, warn, remind, persuade, encourage (She advised me to wait).", "+ preposition + -ing: apologise for, accuse sb of, blame sb for, insist on, congratulate sb on.", "suggest never takes an object + to: ✗ She suggested me to go → She suggested that I go / suggested going."], es: ["Cada verbo tiene su patrón: apréndelo con su estructura."] },
    simple: { es: "Los verbos de reporte resumen lo que alguien dijo con más precisión que say.", en: "Reporting verbs summarise what someone said more precisely than say." },
    more: [["The manager apologised for the delay.", "El gerente se disculpó por el retraso."]],
    items: [
      ["She suggested ___ the launch.", "postponing", ["to postpone", "postpone"], "biz", "Sugirió posponer el lanzamiento."],
      ["He warned us ___ touch the valve.", "not to", ["to not", "don't"], "oil", "Nos advirtió que no tocáramos la válvula."],
      ["The supplier denied ___ the order.", "receiving", ["to receive", "receive"], "biz", "El proveedor negó haber recibido el pedido."],
      ["They accused him ___ leaking the data.", "of", ["for", "about"], "law", "Lo acusaron de filtrar los datos."],
      ["The contractor refused ___ the extra costs.", "to pay", ["paying", "pay"], "law", "El contratista se negó a pagar los costos extra."],
      ["The manager apologised ___ the delay.", "for", ["of", "to"], "work", "El gerente se disculpó por el retraso."],
      ["She persuaded the board ___ the proposal.", "to approve", ["approving", "approve"], "biz", "Convenció a la junta de aprobar la propuesta."],
      ["He insisted ___ checking every document himself.", "on", ["to", "for"], "qa", "Insistió en revisar cada documento él mismo."],
    ],
    challenge: { en: "Summarise a recent meeting using three reporting verbs (suggest, agree, warn…).", es: "Resume una reunión reciente con tres verbos de reporte.", check: "\\b(suggested|agreed|warned|refused|denied|admitted|recommended|advised|insisted|apologised|apologized)\\b" },
    errors: ["say-me"],
  }),
  T({
    id: "g.ellipsis", level: "C1", title: "Ellipsis & substitution", es: "Elipsis y sustitución", icon: "✂️",
    situation: { emoji: "💬", en: "Sounding natural by avoiding repetition.", es: "Sonar natural evitando repeticiones." },
    examples: [["Are you coming? — I hope so.", "¿Vienes? — Espero que sí."], ["She can speak French and so can I.", "Ella habla francés y yo también."], ["I didn't like it and neither did he.", "No me gustó y a él tampoco."], ["I'd like to help, but I'm not able to.", "Me gustaría ayudar, pero no puedo."]],
    pattern: "so / not · so do I / neither do I · auxiliary alone · to (without verb) · one / ones",
    rule: { en: ["so / not replace a clause after think, hope, expect, suppose, afraid: I think so. I hope not.", "so + auxiliary + subject (agreement with positive) / neither/nor + auxiliary + subject (negative).", "Use the auxiliary alone to avoid repeating the verb: He works harder than I do.", "Keep 'to' without repeating the verb: I'd love to.", "one / ones replace countable nouns: the red one, the new ones."], es: ["Así el inglés evita repetir: I think so = creo que sí; so do I = yo también."] },
    simple: { es: "Yo también = so do I; yo tampoco = neither do I; creo que sí = I think so.", en: "Avoid repetition: so do I, neither do I, I think so." },
    more: [["Will it rain? — I'm afraid so.", "¿Lloverá? — Me temo que sí."]],
    items: [
      ["Is the report ready? — I think ___.", "so", ["it", "yes"], "report", "¿Está listo el informe? — Creo que sí."],
      ["I love this city. — So ___ I.", "do", ["am", "have"], "travel", "Me encanta esta ciudad. — A mí también."],
      ["She hasn't finished. — Neither ___ I.", "have", ["do", "am"], "work", "Ella no ha terminado. — Yo tampoco."],
      ["Will the supplier be late again? — I hope ___.", "not", ["no", "don't"], "biz", "¿El proveedor llegará tarde otra vez? — Espero que no."],
      ["He works harder than I ___.", "do", ["work it", "am"], "work", "Él trabaja más que yo."],
      ["Would you like to join us? — I'd love ___.", "to", ["it", "to join it"], "daily", "¿Quieres acompañarnos? — Me encantaría."],
      ["I don't need the old manuals, just the new ___.", "ones", ["one", "them ones"], "eng", "No necesito los manuales viejos, solo los nuevos."],
    ],
    challenge: { en: "Write a short dialogue using 'I think so', 'so do I' and 'neither do I'.", es: "Escribe un diálogo corto con «I think so», «so do I» y «neither do I».", check: "\\b(think so|hope (so|not)|so (do|am|have|can) i|neither (do|am|have|can) i)\\b" },
    errors: [],
  }),
  T({
    id: "g.discourse-markers", level: "C1", title: "Discourse markers", es: "Marcadores del discurso", icon: "🧭",
    situation: { emoji: "🗣️", en: "Organising what you say in meetings and presentations.", es: "Organizar lo que dices en reuniones y presentaciones." },
    examples: [["Anyway, let's get back to the main point.", "En fin, volvamos al tema principal."], ["As far as I'm concerned, the plan is solid.", "En lo que a mí respecta, el plan es sólido."], ["Having said that, we need more data.", "Dicho esto, necesitamos más datos."], ["In other words, we're over budget.", "En otras palabras, nos pasamos del presupuesto."]],
    pattern: "Opinion · Contrast · Clarifying · Changing topic · Concluding",
    rule: { en: ["Giving opinion: as far as I'm concerned, in my view, to my mind.", "Contrast / concession: having said that, mind you, admittedly, even so.", "Clarifying: in other words, that is to say, to put it another way.", "Changing topic / returning: anyway, by the way, as I was saying, moving on.", "Concluding: all in all, to sum up, at the end of the day."], es: ["Son las «señales de tráfico» de una conversación: indican opinión, contraste, aclaración o cambio de tema."] },
    simple: { es: "Palabras que organizan lo que dices: anyway, in other words, having said that…", en: "Words that organise speech: anyway, in other words, having said that…" },
    more: [["All in all, it was a successful year.", "En general, fue un año exitoso."]],
    items: [
      ["___, let's get back to the budget.", "Anyway", ["Although", "Unless"], "meeting", "En fin, volvamos al presupuesto."],
      ["The plan is good. ___ that, it's very expensive.", "Having said", ["As far as", "In spite"], "biz", "El plan es bueno. Dicho esto, es muy caro."],
      ["We're over budget. In other ___, we need more money.", "words", ["way", "terms of"], "report", "Nos pasamos del presupuesto. En otras palabras, necesitamos más dinero."],
      ["As far as I'm ___, the proposal is acceptable.", "concerned", ["concerning", "concern"], "meeting", "En lo que a mí respecta, la propuesta es aceptable."],
      ["___ in all, the audit went very well.", "All", ["Over", "After"], "qa", "En general, la auditoría fue muy bien."],
      ["By the ___, have you seen the new policy?", "way", ["time", "means"], "hr", "Por cierto, ¿has visto la nueva política?"],
    ],
    challenge: { en: "Give your opinion on remote work using three discourse markers.", es: "Opina sobre el trabajo remoto usando tres marcadores del discurso.", check: "\\b(anyway|having said that|in other words|as far as i'?m concerned|all in all|by the way|to sum up|admittedly)\\b" },
    errors: [],
  }),
  T({
    id: "g.register", level: "C2", title: "Register & nuance", es: "Registro y matiz (formal vs informal)", icon: "🎩",
    situation: { emoji: "✉️", en: "Adapting the same message to a friend, a colleague and the board.", es: "Adaptar el mismo mensaje a un amigo, un colega y la junta directiva." },
    examples: [["Informal: Can you send it over?", "Informal: ¿Me lo mandas?"], ["Neutral: Could you send it to me, please?", "Neutral: ¿Me lo podrías enviar, por favor?"], ["Formal: I would be grateful if you could forward it.", "Formal: Le agradecería que me lo remitiera."], ["Formal: We regret to inform you that…", "Formal: Lamentamos informarle que…"]],
    pattern: "Informal ↔ Neutral ↔ Formal: vocabulary, grammar and length change",
    rule: { en: ["Formal register prefers Latin-based verbs (obtain, require, commence) over phrasal verbs (get, need, start).", "Indirect requests are more formal: I would be grateful if…, Would it be possible to…?", "Passive and impersonal structures create distance: It has been decided that…", "Informal register uses contractions, phrasal verbs, ellipsis and direct questions.", "Nuance: 'I'm afraid…', 'slightly', 'somewhat' soften bad news."], es: ["El mismo contenido cambia de palabras y estructura según a quién escribes."] },
    simple: { es: "Formal = palabras más largas y frases indirectas; informal = contracciones y phrasal verbs.", en: "Formal = longer words, indirect structures; informal = contractions, phrasal verbs." },
    more: [["Informal: We need to put off the meeting. → Formal: The meeting will need to be postponed.", "Pospondremos la reunión."]],
    items: [
      ["Formal version of 'get': We need to ___ approval from the board.", "obtain", ["get hold", "grab"], "biz", "Necesitamos obtener la aprobación de la junta."],
      ["Formal: I would be ___ if you could send the invoice.", "grateful", ["happy to", "thankful that"], "biz", "Le agradecería que enviara la factura."],
      ["Formal version of 'start': The works will ___ on Monday.", "commence", ["kick off", "get going"], "eng", "Las obras comenzarán el lunes."],
      ["Softening bad news: I'm ___ we cannot accept the offer.", "afraid", ["sorry that", "scared"], "biz", "Me temo que no podemos aceptar la oferta."],
      ["Formal version of 'need': Visitors ___ to wear protective equipment.", "are required", ["have got", "gotta"], "oil", "Los visitantes deben usar equipo de protección."],
      ["Formal: We ___ to inform you that your application was unsuccessful.", "regret", ["are sad", "feel bad"], "hr", "Lamentamos informarle que su solicitud no fue seleccionada."],
      ["Formal version of 'find out': The committee will ___ the cause.", "determine", ["figure out", "work out"], "law", "El comité determinará la causa."],
    ],
    challenge: { en: "Rewrite 'Hey, can you send me the report ASAP?' in formal English.", es: "Reescribe «Hey, can you send me the report ASAP?» en inglés formal.", check: "\\b(would|could|grateful|kindly|appreciate|possible)\\b" },
    errors: [],
  }),
];
