// Gramática B2–C2 — explicaciones principalmente en inglés (sección 22). Ítems de muestra; se amplían desde el CMS.
export default [
  {
    id: "g.reported-speech", level: "B2", title: "Reported Speech", es: "Estilo indirecto", icon: "🗨️",
    situation: { emoji: "📝", en: "Writing meeting minutes: what did the client say?", es: "Redactando el acta: ¿qué dijo el cliente?" },
    examples: [["She said (that) she was busy.", "Dijo que estaba ocupada."], ["He told me he had sent the file.", "Me dijo que había enviado el archivo."], ["They asked if we could deliver earlier.", "Preguntaron si podíamos entregar antes."], ["The auditor asked where the records were.", "El auditor preguntó dónde estaban los registros."]],
    pattern: "say (that) / tell + person · tense back-shift: am→was, will→would, have done→had done",
    rule: {
      en: ["Reporting verbs: say (something), tell (someone), ask (if / wh-).", "Tenses usually move back: present → past, past → past perfect, will → would, can → could.", "Reported questions use statement word order: She asked where I worked (not where did I work).", "Time words change: tomorrow → the next day, here → there."],
      es: ["Say + lo dicho; tell + persona. Los tiempos suelen retroceder un paso (is → was, will → would).", "En preguntas indirectas no hay inversión: asked where I worked."],
    },
    simple: { es: "Contar lo que alguien dijo: el verbo retrocede al pasado.", en: "Move the tense one step back and use say / tell." },
    more: [["The client said the delivery would be late.", "El cliente dijo que la entrega llegaría tarde."]],
    items: [
      ["She said she ___ busy.", "was", ["is", "be"], "work", "Dijo que estaba ocupada."],
      ["He ___ me he had sent the file.", "told", ["said", "says"], "work", "Me dijo que había enviado el archivo."],
      ["They asked ___ we could deliver earlier.", "if", ["that", "what"], "biz", "Preguntaron si podíamos entregar antes."],
      ["The auditor asked where the records ___.", "were", ["are they", "were they"], "qa", "El auditor preguntó dónde estaban los registros."],
      ["The client said the delivery ___ be late.", "would", ["will", "is"], "meeting", "El cliente dijo que la entrega llegaría tarde."],
      ["The employee said he ___ the policy before.", "had read", ["has read", "reads"], "hr", "El empleado dijo que había leído la política antes."],
    ],
    challenge: { en: "Report three things someone said to you this week.", es: "Reporta tres cosas que alguien te dijo esta semana.", check: "\\b(said|told|asked)\\b" },
    errors: ["say-me"],
  },
  {
    id: "g.third-conditional", level: "B2", title: "Third Conditional", es: "Tercer condicional (pasado imaginario)", icon: "↩️",
    situation: { emoji: "🧯", en: "Lessons learned after an incident.", es: "Lecciones aprendidas tras un incidente." },
    examples: [["If we had checked the valve, the leak wouldn't have happened.", "Si hubiéramos revisado la válvula, la fuga no habría ocurrido."], ["If I had known, I would have called you.", "Si lo hubiera sabido, te habría llamado."]],
    pattern: "If + past perfect, would have + past participle",
    rule: {
      en: ["Imaginary situations in the past — things that did not happen.", "If + had + participle, would have + participle.", "Useful for regrets, criticism and lessons learned."],
      es: ["Situaciones imaginarias en el pasado. If + had + participio, would have + participio."],
    },
    simple: { es: "Si hubiera…, habría…", en: "Past that didn't happen: if + had done → would have done." },
    more: [["We would have won the tender if our price had been lower.", "Habríamos ganado la licitación si nuestro precio hubiera sido más bajo."]],
    items: [
      ["If we had checked the valve, the leak ___ have happened.", "wouldn't", ["won't", "didn't"], "oil", "Si hubiéramos revisado la válvula, la fuga no habría ocurrido."],
      ["If I had ___, I would have called you.", "known", ["knew", "know"], "daily", "Si lo hubiera sabido, te habría llamado."],
      ["We would have won the tender if our price ___ lower.", "had been", ["was", "would be"], "biz", "Habríamos ganado la licitación si nuestro precio hubiera sido más bajo."],
      ["If the inspector had seen the defect, he would have ___ the part.", "rejected", ["reject", "rejecting"], "qa", "Si el inspector hubiera visto el defecto, habría rechazado la pieza."],
    ],
    challenge: { en: "Write about a past decision and what would have happened otherwise.", es: "Escribe sobre una decisión pasada y qué habría pasado si no.", check: "\\bwould have\\b|\\bwould've\\b" },
    errors: [],
  },
  {
    id: "g.wish", level: "B2", title: "Wish / If only", es: "Wish: deseos y lamentos", icon: "🌠",
    situation: { emoji: "😔", en: "Talking about regrets and things you want to change.", es: "Hablando de lamentos y cosas que quieres cambiar." },
    examples: [["I wish I spoke English fluently.", "Ojalá hablara inglés con fluidez."], ["I wish I had studied more.", "Ojalá hubiera estudiado más."], ["If only we had more time!", "¡Si tan solo tuviéramos más tiempo!"]],
    pattern: "wish + past simple (present) · wish + past perfect (past) · wish + would (annoyance)",
    rule: {
      en: ["wish + past simple: a present situation you'd like to be different.", "wish + past perfect: a past regret.", "wish + would: annoying behaviour you want to change."],
      es: ["Wish + pasado = presente imaginario; wish + had + participio = lamento del pasado."],
    },
    simple: { es: "«Ojalá…» = I wish + un tiempo hacia atrás.", en: "wish = one tense back." },
    more: [["I wish my colleagues would answer emails faster.", "Ojalá mis colegas respondieran los correos más rápido."]],
    items: [
      ["I wish I ___ English fluently.", "spoke", ["speak", "will speak"], "daily", "Ojalá hablara inglés con fluidez."],
      ["I wish I ___ more at university.", "had studied", ["studied", "study"], "daily", "Ojalá hubiera estudiado más en la universidad."],
      ["If only we ___ more time for the project!", "had", ["have", "will have"], "eng", "¡Si tan solo tuviéramos más tiempo para el proyecto!"],
      ["I wish the supplier ___ reply faster.", "would", ["will", "does"], "biz", "Ojalá el proveedor respondiera más rápido."],
    ],
    challenge: { en: "Write two wishes about the present and one regret about the past.", es: "Escribe dos deseos sobre el presente y un lamento del pasado.", check: "\\b(wish|if only)\\b" },
    errors: [],
  },
  {
    id: "g.modals-deduction", level: "B2", title: "Modals of Deduction", es: "Modales de deducción: must, might, can't", icon: "🕵️",
    situation: { emoji: "🔧", en: "Troubleshooting: what caused the failure?", es: "Diagnóstico: ¿qué causó la falla?" },
    examples: [["The seal must be damaged.", "El sello debe de estar dañado."], ["It might be a software issue.", "Podría ser un problema de software."], ["It can't be the pump — we replaced it yesterday.", "No puede ser la bomba: la cambiamos ayer."], ["Someone must have left the valve open.", "Alguien debe de haber dejado la válvula abierta."]],
    pattern: "must / might / could / can't + base verb (present) · + have + participle (past)",
    rule: {
      en: ["must = I'm almost sure it's true. can't = I'm almost sure it's not true.", "might / may / could = it's possible.", "For the past: must have / might have / can't have + past participle."],
      es: ["Must = seguramente sí; can't = seguramente no; might/could = quizás. En pasado: + have + participio."],
    },
    simple: { es: "Must = casi seguro. Might = quizás. Can't = imposible.", en: "must (sure), might (maybe), can't (impossible)." },
    more: [["The client might not have received the email.", "Puede que el cliente no haya recibido el correo."]],
    items: [
      ["The seal ___ be damaged. There's oil everywhere.", "must", ["can't", "should"], "eng", "El sello debe de estar dañado. Hay aceite por todas partes."],
      ["It ___ be the pump. We replaced it yesterday.", "can't", ["must", "might"], "oil", "No puede ser la bomba. La cambiamos ayer."],
      ["I'm not sure. It ___ be a software issue.", "might", ["must", "can't"], "eng", "No estoy seguro. Podría ser un problema de software."],
      ["Someone must have ___ the valve open.", "left", ["leave", "leaving"], "oil", "Alguien debe de haber dejado la válvula abierta."],
      ["The client might not ___ received the email.", "have", ["has", "had"], "biz", "Puede que el cliente no haya recibido el correo."],
    ],
    challenge: { en: "Make three deductions about why a colleague is late.", es: "Haz tres deducciones sobre por qué llega tarde un colega.", check: "\\b(must|might|could|can't|may)\\b" },
    errors: [],
  },
  {
    id: "g.linking", level: "B2", title: "Linking: contrast & addition", es: "Conectores de contraste y adición", icon: "🌉",
    situation: { emoji: "📑", en: "Writing a balanced recommendation in a report.", es: "Escribiendo una recomendación equilibrada en un informe." },
    examples: [["Although the cost is high, the benefits are clear.", "Aunque el coste es alto, los beneficios son claros."], ["Despite the delay, we met the deadline.", "A pesar del retraso, cumplimos el plazo."], ["The design is safe. However, it is expensive.", "El diseño es seguro. Sin embargo, es caro."], ["In addition, the supplier offers training.", "Además, el proveedor ofrece capacitación."]],
    pattern: "although + clause · despite / in spite of + noun / -ing · however, (new sentence) · whereas · moreover / in addition",
    rule: {
      en: ["although / even though + subject + verb.", "despite / in spite of + noun or -ing (never + clause).", "However starts a new sentence or clause and is followed by a comma.", "whereas compares two facts; moreover / in addition add a point."],
      es: ["Although + oración; despite + sustantivo / -ing; however va al inicio de una nueva oración con coma."],
    },
    simple: { es: "Although + frase. Despite + cosa.", en: "although + clause; despite + noun." },
    more: [["Whereas Option A is cheaper, Option B is more durable.", "Mientras que la opción A es más barata, la B es más duradera."]],
    items: [
      ["___ the cost is high, the benefits are clear.", "Although", ["Despite", "However"], "report", "Aunque el coste es alto, los beneficios son claros."],
      ["___ the delay, we met the deadline.", "Despite", ["Although", "However"], "eng", "A pesar del retraso, cumplimos el plazo."],
      ["The design is safe. ___, it is expensive.", "However", ["Although", "Despite"], "report", "El diseño es seguro. Sin embargo, es caro."],
      ["In spite of ___ the procedure, he made a mistake.", "following", ["he followed", "follow"], "qa", "A pesar de seguir el procedimiento, cometió un error."],
      ["Option A is cheaper, ___ Option B is more durable.", "whereas", ["despite", "moreover"], "biz", "La opción A es más barata, mientras que la B es más duradera."],
    ],
    challenge: { en: "Write a short recommendation with although, however and in addition.", es: "Escribe una recomendación corta con although, however e in addition.", check: "\\b(although|however|despite|whereas|moreover|in addition)\\b" },
    errors: [],
  },
  {
    id: "g.causative", level: "B2", title: "Causative: have / get something done", es: "Causativo: have / get something done", icon: "🛠️",
    situation: { emoji: "🚗", en: "You don't repair things yourself — you pay someone.", es: "No reparas las cosas tú mismo: pagas a alguien." },
    examples: [["I had my car repaired.", "Me repararon el auto (pagué para que lo repararan)."], ["We're getting the pump serviced next week.", "Nos van a revisar la bomba la próxima semana."], ["She had the contract translated.", "Hizo traducir el contrato."]],
    pattern: "have / get + object + past participle",
    rule: {
      en: ["Use it when someone else does a service for you.", "have + object + past participle (neutral); get + object + past participle (more informal).", "Word order matters: I had my hair cut ≠ I cut my hair."],
      es: ["Alguien hace algo por ti: have + objeto + participio."],
    },
    simple: { es: "Mandar a hacer algo: have + cosa + participio.", en: "Someone does it for you: have + thing + past participle." },
    more: [["We need to have the equipment calibrated.", "Necesitamos hacer calibrar el equipo."]],
    items: [
      ["I had my car ___ yesterday.", "repaired", ["repair", "repairing"], "daily", "Me repararon el auto ayer."],
      ["We need to have the equipment ___.", "calibrated", ["calibrate", "to calibrate"], "qa", "Necesitamos hacer calibrar el equipo."],
      ["She had the contract ___ into Spanish.", "translated", ["translate", "translating"], "law", "Hizo traducir el contrato al español."],
      ["We're getting the pump ___ next week.", "serviced", ["service", "to service"], "oil", "Nos revisan la bomba la próxima semana."],
    ],
    challenge: { en: "Write about two services you pay for (have … done).", es: "Escribe sobre dos servicios que pagas (have … done).", check: "\\b(have|has|had|get|got)\\s+\\w+(\\s+\\w+)?\\s+\\w+(ed|en|t)\\b" },
    errors: [],
  },
  {
    id: "g.inversion", level: "C1", title: "Inversion for emphasis", es: "Inversión para dar énfasis", icon: "🔃",
    situation: { emoji: "🎤", en: "A formal speech or a strong written statement.", es: "Un discurso formal o una afirmación escrita contundente." },
    examples: [["Never have we seen such results.", "Nunca habíamos visto tales resultados."], ["Not only did they finish early, but they also cut costs.", "No solo terminaron antes, sino que además redujeron costes."], ["Rarely does a project go exactly to plan.", "Rara vez un proyecto sale exactamente según lo previsto."], ["Should you have any questions, please contact us.", "Si tiene alguna pregunta, contáctenos."]],
    pattern: "Negative adverbial (Never, Rarely, Not only, Only then…) + auxiliary + subject + verb",
    rule: {
      en: ["After negative or restrictive adverbials at the start of a sentence, invert auxiliary and subject: Never have I…", "Common openers: Never, Rarely, Seldom, Not only, No sooner, Hardly, Only then, Under no circumstances.", "Formal conditional inversion: Should you need… = If you need…; Had we known… = If we had known…", "Mainly formal and written; use sparingly for emphasis."],
      es: ["Tras adverbios negativos al inicio, el auxiliar va antes del sujeto: Never have I seen…"],
    },
    simple: { es: "Adverbio negativo al principio → orden de pregunta.", en: "Negative word first → question word order." },
    more: [["Under no circumstances should the valve be opened.", "Bajo ninguna circunstancia se debe abrir la válvula."]],
    items: [
      ["Never ___ we seen such results.", "have", ["we have", "had"], "report", "Nunca habíamos visto tales resultados."],
      ["Not only ___ they finish early, but they also cut costs.", "did", ["they did", "have"], "biz", "No solo terminaron antes, sino que redujeron costes."],
      ["Rarely ___ a project go exactly to plan.", "does", ["do", "is"], "eng", "Rara vez un proyecto sale según lo previsto."],
      ["___ you have any questions, please contact us.", "Should", ["If should", "Would"], "biz", "Si tiene alguna pregunta, contáctenos."],
      ["Under no circumstances ___ the valve be opened.", "should", ["it should", "must not"], "oil", "Bajo ninguna circunstancia debe abrirse la válvula."],
    ],
    challenge: { en: "Rewrite 'We have never had such a good year' using inversion.", es: "Reescribe «We have never had such a good year» con inversión.", check: "^\\s*never\\s+(have|has|had)\\b" },
    errors: [],
  },
  {
    id: "g.mixed-conditionals", level: "C1", title: "Mixed & Advanced Conditionals", es: "Condicionales mixtos y avanzados", icon: "🧬",
    situation: { emoji: "🧭", en: "Reflecting on career decisions.", es: "Reflexionando sobre decisiones de carrera." },
    examples: [["If I had accepted that job, I would be living in Canada now.", "Si hubiera aceptado ese trabajo, ahora viviría en Canadá."], ["If she weren't so experienced, she wouldn't have been promoted.", "Si no tuviera tanta experiencia, no la habrían ascendido."], ["Provided that the budget is approved, we'll start in May.", "Siempre que se apruebe el presupuesto, empezaremos en mayo."], ["But for your help, we would have failed.", "De no ser por tu ayuda, habríamos fallado."]],
    pattern: "If + past perfect → would + base (past → present) · If + past → would have + pp (present → past) · provided that, as long as, but for, otherwise",
    rule: {
      en: ["Mixed conditionals combine different times: a past condition with a present result, or a permanent present condition with a past result.", "Alternatives to if: provided (that), as long as, on condition that, unless, supposing, otherwise, but for + noun.", "Choose the form by the time of each half of the sentence."],
      es: ["Combinan tiempos: condición pasada + resultado presente, o al revés."],
    },
    simple: { es: "Mezcla pasado y presente según cuándo ocurre cada parte.", en: "Each half of the sentence keeps its own time." },
    more: [["As long as the tests pass, we can release the batch.", "Mientras las pruebas salgan bien, podemos liberar el lote."]],
    items: [
      ["If I had accepted that job, I ___ in Canada now.", "would be living", ["would have lived", "will live"], "work", "Si hubiera aceptado ese trabajo, ahora viviría en Canadá."],
      ["If she weren't so experienced, she wouldn't have ___ promoted.", "been", ["be", "being"], "hr", "Si no tuviera tanta experiencia, no la habrían ascendido."],
      ["___ that the budget is approved, we'll start in May.", "Provided", ["Unless", "Despite"], "biz", "Siempre que se apruebe el presupuesto, empezaremos en mayo."],
      ["___ for your help, we would have failed.", "But", ["Without", "If"], "daily", "De no ser por tu ayuda, habríamos fallado."],
      ["As long as the tests ___, we can release the batch.", "pass", ["will pass", "passed"], "qa", "Mientras las pruebas salgan bien, podemos liberar el lote."],
    ],
    challenge: { en: "Write a mixed conditional about a past decision that affects your life today.", es: "Escribe un condicional mixto sobre una decisión pasada que afecta tu vida hoy.", check: "\\bif\\b[^.]*\\bhad\\b[^.]*\\bwould\\b" },
    errors: [],
  },
  {
    id: "g.cleft", level: "C1", title: "Cleft sentences", es: "Oraciones escindidas (énfasis)", icon: "✂️",
    situation: { emoji: "📣", en: "Clarifying the real problem in a meeting.", es: "Aclarando el verdadero problema en una reunión." },
    examples: [["It was the supplier who delayed the shipment.", "Fue el proveedor quien retrasó el envío."], ["What we need is more time.", "Lo que necesitamos es más tiempo."], ["What worries me is the cost.", "Lo que me preocupa es el coste."], ["All I want is a clear answer.", "Lo único que quiero es una respuesta clara."]],
    pattern: "It is/was + X + who/that… · What + clause + is/was + X · All (that) + clause + is…",
    rule: {
      en: ["Cleft sentences split a sentence to focus on one element.", "It-cleft: It was Maria who found the error.", "Wh-cleft: What we need is a plan.", "Very natural in spoken and professional English for emphasis and correction."],
      es: ["Sirven para enfatizar: It was… who…, What we need is…"],
    },
    simple: { es: "«Lo que… es…» = What … is …", en: "Put the important part in focus: What I need is…" },
    more: [["It's the documentation that needs improving, not the process.", "Es la documentación la que hay que mejorar, no el proceso."]],
    items: [
      ["It was the supplier ___ delayed the shipment.", "who", ["what", "which is"], "biz", "Fue el proveedor quien retrasó el envío."],
      ["___ we need is more time.", "What", ["That", "Which"], "meeting", "Lo que necesitamos es más tiempo."],
      ["What worries me ___ the cost.", "is", ["are", "it is"], "report", "Lo que me preocupa es el coste."],
      ["It's the documentation ___ needs improving.", "that", ["what", "who"], "qa", "Es la documentación la que hay que mejorar."],
    ],
    challenge: { en: "Clarify a problem at work using 'What we need is…' or 'It was … that…'.", es: "Aclara un problema usando «What we need is…» o «It was … that…».", check: "^\\s*(what|it (is|was))\\b" },
    errors: [],
  },
  {
    id: "g.participle-clauses", level: "C1", title: "Participle clauses", es: "Oraciones de participio", icon: "🧵",
    situation: { emoji: "📰", en: "Writing concise professional reports.", es: "Redactando informes profesionales concisos." },
    examples: [["Having reviewed the data, we recommend Option B.", "Tras revisar los datos, recomendamos la opción B."], ["Built in 1990, the plant needs modernization.", "Construida en 1990, la planta necesita modernización."], ["Working under pressure, the team still met the deadline.", "Trabajando bajo presión, el equipo cumplió el plazo."]],
    pattern: "-ing (active, same time) · Having + pp (earlier action) · pp (passive)",
    rule: {
      en: ["Participle clauses make writing concise by replacing a subject + verb.", "Present participle (-ing) for simultaneous active actions; having + past participle for earlier actions; past participle for passive meaning.", "The subject of the participle clause must be the same as the main clause subject (avoid dangling participles)."],
      es: ["Acortan oraciones: Having reviewed… = After we had reviewed…"],
    },
    simple: { es: "Una forma corta de unir dos frases con el mismo sujeto.", en: "A short way to join two sentences with the same subject." },
    more: [["Located near the port, the warehouse is easy to access.", "Ubicado cerca del puerto, el almacén es de fácil acceso."]],
    items: [
      ["___ reviewed the data, we recommend Option B.", "Having", ["Have", "Had"], "report", "Tras revisar los datos, recomendamos la opción B."],
      ["___ in 1990, the plant needs modernization.", "Built", ["Building", "Having build"], "oil", "Construida en 1990, la planta necesita modernización."],
      ["___ under pressure, the team still met the deadline.", "Working", ["Worked", "Having work"], "eng", "Trabajando bajo presión, el equipo cumplió el plazo."],
      ["___ near the port, the warehouse is easy to access.", "Located", ["Locating", "Having located"], "biz", "Ubicado cerca del puerto, el almacén es de fácil acceso."],
    ],
    challenge: { en: "Combine two sentences about a project using a participle clause.", es: "Une dos frases sobre un proyecto con una oración de participio.", check: "^\\s*(having|\\w+ing|\\w+ed)\\b[^,]*," },
    errors: [],
  },
  {
    id: "g.academic", level: "C2", title: "Academic Structures (hedging)", es: "Estructuras académicas: matizar", icon: "🎓",
    situation: { emoji: "📚", en: "Writing a paper or a technical conclusion without overclaiming.", es: "Escribiendo un artículo o conclusión técnica sin exagerar." },
    examples: [["The results appear to suggest a correlation.", "Los resultados parecen sugerir una correlación."], ["It could be argued that the model is incomplete.", "Podría argumentarse que el modelo es incompleto."], ["This tends to occur under high pressure.", "Esto tiende a ocurrir con alta presión."], ["There is some evidence to indicate that…", "Existen ciertos indicios de que…"]],
    pattern: "appear / seem / tend to · it could be argued that · may / might · to some extent · the evidence suggests",
    rule: {
      en: ["Hedging expresses caution and precision: appear to, seem to, tend to, may, might, likely, arguably.", "Impersonal structures: It could be argued that…, It is widely accepted that…", "Nominalisation (the implementation of) makes text more formal and dense.", "Balance hedging with clarity: don't hedge facts that are certain."],
      es: ["Matizar afirmaciones con appear to, tend to, may, it could be argued that…"],
    },
    simple: { es: "No digas «es así»; di «parece que es así».", en: "Say it carefully: 'appears to', 'may', 'tends to'." },
    more: [["To some extent, the findings support the hypothesis.", "En cierta medida, los hallazgos apoyan la hipótesis."]],
    items: [
      ["The results appear ___ suggest a correlation.", "to", ["for", "that"], "report", "Los resultados parecen sugerir una correlación."],
      ["It could be ___ that the model is incomplete.", "argued", ["argue", "arguing"], "report", "Podría argumentarse que el modelo es incompleto."],
      ["Corrosion ___ to occur in humid environments.", "tends", ["tend", "is tending"], "oil", "La corrosión tiende a ocurrir en ambientes húmedos."],
      ["To some ___, the findings support the hypothesis.", "extent", ["extend", "degree of"], "report", "En cierta medida, los hallazgos apoyan la hipótesis."],
    ],
    challenge: { en: "Rewrite 'This proves the design is wrong' in a cautious academic way.", es: "Reescribe «This proves the design is wrong» de forma académica y cautelosa.", check: "\\b(may|might|appear|seem|suggest|could|tend|likely)\\b" },
    errors: [],
  },
  {
    id: "g.advanced-writing", level: "C2", title: "Advanced Writing Structures", es: "Estructuras avanzadas de escritura", icon: "🖋️",
    situation: { emoji: "🏛️", en: "Drafting an executive summary for the board.", es: "Redactando un resumen ejecutivo para la junta." },
    examples: [["The implementation of the new system resulted in a 20% reduction in downtime.", "La implementación del nuevo sistema produjo una reducción del 20 % en el tiempo de inactividad."], ["Such was the demand that production doubled.", "Tal fue la demanda que la producción se duplicó."], ["Were the proposal to be accepted, costs would fall.", "Si se aceptara la propuesta, los costes bajarían."]],
    pattern: "Nominalisation · Such was X that… · So + adj + was X that… · Were … to…",
    rule: {
      en: ["Nominalisation turns verbs into nouns for a formal, concise style: implement → the implementation of.", "Fronting and 'such / so … that' structures add emphasis.", "Formal hypothetical inversion: Were the proposal to be accepted…", "Vary sentence length and use precise linking to guide the reader."],
      es: ["Nominalizar (the implementation of…), estructuras enfáticas (Such was…) e inversión formal (Were … to…)."],
    },
    simple: { es: "Estilo formal: verbos → sustantivos y estructuras enfáticas.", en: "Formal style: more nouns, emphatic structures." },
    more: [["So significant was the impact that the policy was revised.", "Tan significativo fue el impacto que se revisó la política."]],
    items: [
      ["The ___ of the new system reduced downtime. (implement)", "implementation", ["implement", "implementing of"], "report", "La implementación del nuevo sistema redujo el tiempo de inactividad."],
      ["___ was the demand that production doubled.", "Such", ["So", "Very"], "biz", "Tal fue la demanda que la producción se duplicó."],
      ["___ the proposal to be accepted, costs would fall.", "Were", ["If", "Was"], "biz", "Si se aceptara la propuesta, los costes bajarían."],
      ["So significant ___ the impact that the policy was revised.", "was", ["it was", "were"], "hr", "Tan significativo fue el impacto que se revisó la política."],
    ],
    challenge: { en: "Write one formal sentence for a board report using nominalisation.", es: "Escribe una frase formal para un informe a la junta con nominalización.", check: "\\b\\w+(tion|ment|ance|ence|ity)\\s+of\\b" },
    errors: [],
  },
  {
    id: "g.subjunctive", level: "C2", title: "Formal Subjunctive", es: "Subjuntivo formal", icon: "📜",
    situation: { emoji: "⚖️", en: "Formal recommendations in legal and corporate documents.", es: "Recomendaciones formales en documentos legales y corporativos." },
    examples: [["The committee recommends that the policy be reviewed.", "El comité recomienda que se revise la política."], ["It is essential that every employee complete the training.", "Es esencial que todos los empleados completen la formación."], ["We insist that he attend the hearing.", "Insistimos en que asista a la audiencia."]],
    pattern: "recommend / insist / suggest / demand / it is essential that + subject + base verb",
    rule: {
      en: ["After verbs and adjectives of demand, necessity or recommendation, formal English uses the base form: that he attend (not attends).", "Common in legal, academic and corporate writing; British English often uses should + base (that he should attend).", "Negative: that he not be informed."],
      es: ["Tras recommend / insist / essential that, el verbo va en forma base: that he attend."],
    },
    simple: { es: "En textos formales: recommend that + persona + verbo sin -s.", en: "Formal: recommend that he go (no -s)." },
    more: [["The court ordered that the documents be disclosed.", "El tribunal ordenó que se divulgaran los documentos."]],
    items: [
      ["The committee recommends that the policy ___ reviewed.", "be", ["is", "will be"], "hr", "El comité recomienda que se revise la política."],
      ["It is essential that every employee ___ the training.", "complete", ["completes", "completed"], "hr", "Es esencial que todos completen la formación."],
      ["We insist that he ___ the hearing.", "attend", ["attends", "attended"], "law", "Insistimos en que asista a la audiencia."],
      ["The court ordered that the documents ___ disclosed.", "be", ["are", "were being"], "law", "El tribunal ordenó que se divulgaran los documentos."],
    ],
    challenge: { en: "Write a formal recommendation using 'recommend that' + subjunctive.", es: "Escribe una recomendación formal con «recommend that» + subjuntivo.", check: "\\b(recommend|insist|suggest|essential|demand)\\w*\\s+that\\s+\\w+\\s+(be|\\w+[^s\\s])\\b" },
    errors: [],
  },
];
