// Apuntes profundos de los temas nuevos B2–C2.
export default {
  "g.future-adv": {
    intro: "Además de will y going to, el inglés tiene tiempos futuros «avanzados» para hablar de acciones en progreso en un momento futuro, o terminadas antes de ese momento. Son muy útiles para planificar proyectos.",
    form: { cols: ["Tiempo", "Forma", "Ejemplo", "Significado"], rows: [
      ["Future continuous", "will be + -ing", "At 9 I'll be driving.", "estaré manejando"], ["Future perfect", "will have + participio", "By 9 I'll have arrived.", "habré llegado"], ["Future perfect continuous", "will have been + -ing", "By 9 I'll have been driving for 3 hours.", "llevaré 3 horas manejando"],
    ] },
    form2: { title: "Negativas y preguntas", cols: ["Forma", "Ejemplo"], rows: [["won't be + -ing", "I won't be working tomorrow."], ["won't have + pp", "They won't have finished by Friday."], ["Will you be + -ing?", "Will you be using the room later?"], ["Will you have + pp?", "Will you have finished by noon?"]] },
    uses: [["Acción en progreso en el futuro", "This time next week I'll be lying on a beach.", "La próxima semana a esta hora estaré en la playa."], ["Acción terminada antes de un plazo", "By the end of the month we'll have delivered 500 units.", "Para fin de mes habremos entregado 500 unidades."], ["Pregunta cortés sobre planes", "Will you be coming to the party?", "¿Vas a venir a la fiesta?"], ["Duración hasta un punto futuro", "In May I'll have been living here for a year.", "En mayo llevaré un año viviendo aquí."]],
    signals: ["this time tomorrow / next week", "at 10 o'clock tomorrow", "by Friday / by then / by the time", "in two years' time"],
    mistakes: [["By Friday I will finish it. (plazo)", "By Friday I'll have finished it.", "Con by + plazo, future perfect."], ["Tomorrow at 9 I will work.", "Tomorrow at 9 I'll be working.", "Acción en progreso en ese momento."], ["By the time you will arrive…", "By the time you arrive…", "Después de by the time / when, presente."]],
    spanish: "Equivalen a «estaré + -ando» y «habré + -ado».",
    tips: ["«by» = no más tarde de → casi siempre future perfect.", "Dibuja una línea del tiempo con el punto futuro y pregúntate: ¿estará pasando o ya habrá terminado?"],
  },
  "g.modals-past": {
    intro: "Los modales + have + participio hablan del pasado: lo que era buena idea y no se hizo, lo que era posible y no ocurrió, o lo que no era necesario. Son claves para lecciones aprendidas y disculpas.",
    form: { cols: ["Estructura", "Significado", "Ejemplo"], rows: [
      ["should have + pp", "habría sido buena idea (pero no se hizo)", "We should have checked."], ["shouldn't have + pp", "se hizo pero fue mala idea", "I shouldn't have said that."],
      ["could have + pp", "era posible (pero no pasó)", "You could have called me."], ["couldn't have + pp", "era imposible", "He couldn't have known."],
      ["needn't have + pp", "se hizo, pero no era necesario", "You needn't have brought food."], ["didn't need to + verbo", "no era necesario (y no se hizo)", "I didn't need to wait."],
      ["would have + pp", "resultado imaginado", "I would have helped."],
    ] },
    uses: [["Críticas y lecciones aprendidas", "We should have followed the procedure.", "Deberíamos haber seguido el procedimiento."], ["Reproches suaves", "You could have warned me!", "¡Me podrías haber avisado!"], ["Disculpas", "I shouldn't have raised my voice.", "No debería haber alzado la voz."]],
    mistakes: [["You should told me.", "You should have told me.", "Falta have + participio."], ["We could have went.", "We could have gone.", "Participio (gone), no pasado (went)."], ["I should of known.", "I should have known.", "«should of» es un error de escritura (suena igual)."]],
    spanish: "should have = debería haber · could have = podría haber · needn't have = no hacía falta que.",
    tips: ["En habla rápida: should've /ʃʊdəv/, could've, would've.", "needn't have (lo hice, no hacía falta) ≠ didn't need to (no lo hice porque no hacía falta)."],
  },
  "g.passive-adv": {
    intro: "La pasiva avanzada permite informar de forma impersonal y formal: lo que se dice, se cree o se espera. Muy usada en noticias, informes y textos académicos.",
    form: { cols: ["Estructura", "Ejemplo", "Español"], rows: [
      ["It is said / believed / reported / expected that…", "It is expected that prices will rise.", "Se espera que los precios suban."],
      ["Sujeto + is said to + verbo (presente)", "He is said to be very rich.", "Se dice que es muy rico."],
      ["Sujeto + is said to be + -ing (en curso)", "The company is believed to be planning cuts.", "Se cree que la empresa planea recortes."],
      ["Sujeto + is said to have + pp (pasado)", "The bridge is thought to have been built in 1900.", "Se cree que el puente se construyó en 1900."],
      ["Modal + be + pp", "It must be repaired.", "Debe repararse."], ["Modal + have been + pp", "It should have been reported.", "Debería haberse informado."],
      ["Infinitivo / gerundio pasivo", "It needs to be checked. / I hate being interrupted.", "Hay que revisarlo. / Odio que me interrumpan."],
    ] },
    uses: [["Noticias", "Three people are reported to have been injured.", "Se informa que tres personas resultaron heridas."], ["Informes técnicos", "The failure is believed to have been caused by corrosion.", "Se cree que la falla fue causada por corrosión."]],
    signals: ["say, believe, think, report, expect, know, consider, estimate, allege"],
    mistakes: [["It is said the company to expand.", "The company is said to be expanding. / It is said that the company is expanding.", "Elige una de las dos estructuras."], ["He is believed to has left.", "He is believed to have left.", "to + have (base)."]],
    spanish: "«Se dice que…», «Se cree que…» y «se informa que…» tienen dos traducciones posibles: It is said that… / X is said to…",
    tips: ["Para el pasado, piensa: «to have + participio».", "Úsala en correos formales para sonar objetivo: It has been agreed that…"],
  },
  "g.relative-adv": {
    intro: "En inglés formal y escrito las oraciones de relativo se vuelven más precisas: preposición + whom/which, expresiones como «most of whom», which referido a toda la oración y relativas reducidas.",
    form: { cols: ["Estructura", "Ejemplo", "Registro"], rows: [
      ["preposición + whom (personas)", "the manager to whom I reported", "formal"], ["preposición + which (cosas)", "the company for which I work", "formal"], ["… preposición al final", "the company I work for", "informal"],
      ["cuantificador + of whom / of which", "most of whom, some of which, none of whom, both of which", "neutral / formal"], [", which = lo cual", "He was late, which annoyed everyone.", "neutral"],
      ["Reducida activa (-ing)", "the woman sitting there (= who is sitting)", "neutral"], ["Reducida pasiva (pp)", "the goods made in China (= which are made)", "neutral"],
    ] },
    uses: [["Cartas y contratos", "The parties to whom this notice is addressed…", "Las partes a quienes va dirigido este aviso…"], ["Informes", "We surveyed 200 employees, 70% of whom work remotely.", "Encuestamos a 200 empleados, el 70 % de los cuales trabaja en remoto."]],
    mistakes: [["most of them who", "most of whom", "Tras of → whom/which."], ["He was late, what annoyed everyone.", "He was late, which annoyed everyone.", "«lo cual» = which."], ["the person to who I spoke", "the person to whom I spoke", "Tras preposición → whom."]],
    spanish: "«Con quien / a quienes / la mayoría de los cuales / lo cual» tienen equivalentes directos: with whom, to whom, most of which, which.",
    tips: ["whom solo después de preposición o en textos muy formales; en conversación, who o preposición al final."],
  },
  "g.emphasis": {
    intro: "Para dar énfasis el inglés usa so y such, las estructuras so… that / such… that y el do enfático, que sirve para insistir o contradecir.",
    form: { cols: ["Estructura", "Uso", "Ejemplo"], rows: [
      ["so + adjetivo / adverbio", "intensificar", "It's so expensive! She speaks so fast."], ["such + a/an + (adj) + sustantivo singular", "intensificar", "It's such a nice day."], ["such + (adj) + plural / incontable", "intensificar", "They're such good friends. Such bad weather!"],
      ["so … that / such … that", "consecuencia", "It was so hot that we stayed in."], ["do / does / did + verbo base", "insistir / contradecir", "I do understand. He did call you!"], ["so much / so many", "cantidad", "There were so many people."],
    ] },
    uses: [["Mostrar empatía", "I do see your point.", "De verdad entiendo tu punto."], ["Corregir un malentendido", "I did send it — check your spam folder.", "Sí lo envié; revisa tu carpeta de spam."]],
    mistakes: [["It's so a good idea.", "It's such a good idea.", "Con sustantivo → such."], ["It was such cold.", "It was so cold.", "Con adjetivo solo → so."], ["I do understood.", "I do understand. / I did understand.", "do + verbo base."]],
    spanish: "so = tan; such = tan + sustantivo («un día tan bonito» = such a nice day). El do enfático equivale a «sí que…» o «de verdad».",
    tips: ["Pregunta: ¿viene un sustantivo? Sí → such. No → so."],
  },
  "g.reporting-verbs": {
    intro: "En lugar de repetir «said», el inglés usa verbos de reporte que resumen la intención del hablante (sugerir, advertir, negar, disculparse). Cada verbo tiene su patrón gramatical.",
    form: { cols: ["Patrón", "Verbos", "Ejemplo"], rows: [
      ["verbo + -ing", "suggest, deny, admit, recommend, regret, mention", "He denied taking the money."], ["verbo + to + verbo", "agree, refuse, offer, promise, threaten, claim", "She refused to sign."],
      ["verbo + persona + to + verbo", "advise, warn, remind, persuade, encourage, invite, urge", "They advised us to wait."], ["verbo + (persona) + preposición + -ing", "apologise for, accuse sb of, blame sb for, insist on, congratulate sb on, thank sb for", "He apologised for being late."],
      ["verbo + that + oración", "explain, claim, admit, suggest, insist, confirm", "She explained that the system was down."], ["suggest + that + sujeto + (should) + verbo", "suggest, recommend, propose", "I suggested that he (should) call."],
    ] },
    uses: [["Actas de reunión", "Mike suggested hiring a contractor; Ana agreed to prepare the budget.", "Mike sugirió contratar…; Ana aceptó preparar…"], ["Informes de incidente", "The operator admitted skipping the checklist.", "El operador admitió haber omitido la lista de verificación."]],
    mistakes: [["She suggested me to go.", "She suggested that I go. / She suggested going.", "suggest no lleva persona + to."], ["He denied to take it.", "He denied taking it.", "deny + -ing."], ["They apologised to be late.", "They apologised for being late.", "apologise for + -ing."], ["He explained me the problem.", "He explained the problem to me.", "explain + cosa + to + persona."]],
    spanish: "Igual que en español usamos «sugirió, negó, admitió», pero en inglés cada verbo exige su estructura.",
    tips: ["Aprende cada verbo en una frase modelo; no lo traduzcas palabra por palabra."],
  },
  "g.ellipsis": {
    intro: "La elipsis (omitir palabras) y la sustitución (reemplazarlas con so, not, one, do…) hacen que el inglés suene natural y evitan repeticiones.",
    form: { cols: ["Recurso", "Ejemplo", "Español"], rows: [
      ["think / hope / expect / suppose / afraid + so / not", "I think so. I hope not. I'm afraid so.", "Creo que sí. Espero que no. Me temo que sí."],
      ["So + auxiliar + sujeto (acuerdo +)", "I'm tired. — So am I.", "Yo también."], ["Neither / Nor + auxiliar + sujeto (acuerdo −)", "I can't swim. — Neither can I.", "Yo tampoco."],
      ["Auxiliar solo", "She earns more than I do. / Yes, I have.", "(evita repetir el verbo)"], ["to sin verbo", "I'd like to. I don't want to.", "Me gustaría. No quiero."],
      ["one / ones", "I prefer the blue one.", "Prefiero el azul."], ["do so / did so", "He promised to call and he did so.", "Prometió llamar y lo hizo."],
    ] },
    uses: [["Conversación natural", "Are you going? — I might.", "¿Vas? — Puede que sí."], ["Respuestas en reuniones", "Is it on schedule? — I believe so.", "¿Va según cronograma? — Creo que sí."]],
    mistakes: [["I think yes.", "I think so.", "«Creo que sí» = I think so."], ["Me too. (a una negativa)", "Me neither. / Neither do I.", "A frase negativa → neither."], ["So I am.", "So am I.", "Orden: so + auxiliar + sujeto."]],
    spanish: "«Creo que sí» = I think so; «yo también» = so do I / me too; «yo tampoco» = neither do I / me neither.",
    tips: ["El auxiliar debe coincidir con el verbo original: I like → so do I; I'm → so am I; I've → so have I."],
  },
  "g.discourse-markers": {
    intro: "Los marcadores del discurso organizan lo que dices: muestran opinión, contraste, aclaración, cambio de tema o conclusión. Hacen que suenes fluido y profesional.",
    form: { cols: ["Función", "Marcadores", "Ejemplo"], rows: [
      ["Opinión", "as far as I'm concerned, in my view, to my mind, personally", "In my view, the risk is acceptable."], ["Contraste / concesión", "having said that, even so, mind you, admittedly, on the other hand", "Admittedly, it's expensive. Even so, it's worth it."],
      ["Aclarar", "in other words, that is to say, to put it another way, I mean", "In other words, we need to start again."], ["Añadir", "what's more, on top of that, besides", "What's more, the client is happy."],
      ["Cambiar / volver al tema", "anyway, by the way, as I was saying, moving on, going back to", "Anyway, as I was saying…"], ["Concluir", "all in all, to sum up, at the end of the day, in short", "All in all, a successful project."],
    ] },
    uses: [["Reuniones", "Having said that, I think we should wait for the data.", "Dicho esto, creo que deberíamos esperar los datos."], ["Presentaciones", "Moving on to the next slide…", "Pasando a la siguiente diapositiva…"]],
    mistakes: [["In my opinion I think…", "In my opinion… / I think…", "No uses ambos juntos."], ["At the end (= en conclusión)", "In the end / At the end of the day", "At the end = al final (lugar/tiempo)."]],
    spanish: "Como «en fin», «dicho esto», «en otras palabras», «por cierto», «en resumen».",
    tips: ["Aprende 2 por función y úsalos en tu próxima reunión."],
  },
  "g.register": {
    intro: "El registro es el nivel de formalidad. En C2 debes adaptar el mismo mensaje a un amigo, a un colega o a la junta directiva. Cambian las palabras, la gramática y la longitud.",
    form: { cols: ["Informal", "Neutral", "Formal"], rows: [
      ["get", "receive", "obtain"], ["start", "begin", "commence"], ["need", "need", "require"], ["find out", "discover", "determine / ascertain"], ["put off", "postpone", "defer"],
      ["Can you…?", "Could you…?", "I would be grateful if you could…"], ["Sorry!", "I'm sorry for…", "Please accept our apologies for…"], ["Thanks!", "Thank you for…", "We would like to express our gratitude for…"],
    ] },
    uses: [["Suavizar malas noticias", "I'm afraid we are unable to proceed at this stage.", "Me temo que no podemos continuar por ahora."], ["Distancia impersonal", "It has been decided that the office will close.", "Se ha decidido cerrar la oficina."], ["Informal entre colegas", "Can you shoot me that file?", "¿Me pasas ese archivo?"]],
    mistakes: [["Dear Sir, gonna send it tomorrow.", "Dear Sir, I will send it tomorrow.", "No mezcles registros."], ["Hey John, I would be most grateful should you…", "Hi John, could you…?", "Demasiado formal para un colega cercano."]],
    spanish: "El español formal usa «usted», el condicional y el subjuntivo; el inglés formal usa verbos latinos, estructuras indirectas y pasiva.",
    tips: ["Antes de escribir pregúntate: ¿quién lo leerá? ¿qué relación tengo con esa persona?", "Las palabras de origen latino suenan más formales en inglés (y se parecen al español)."],
  },
};
