// Gramática A1 — contenido original. Ítem: [frase con ___, respuesta, distractores, contexto, traducción]
export default [
  {
    id: "g.be", level: "A1", title: "Verb to be", es: "El verbo to be (ser / estar)", icon: "🙋",
    situation: { emoji: "🤝", en: "First day at a new job. Ana meets her team.", es: "Primer día en un trabajo nuevo. Ana conoce a su equipo." },
    examples: [["I'm Ana. I'm the new engineer.", "Soy Ana. Soy la nueva ingeniera."], ["You are in the QA team.", "Estás en el equipo de QA."], ["He is from Chile.", "Él es de Chile."], ["We aren't late.", "No llegamos tarde."], ["Are you ready?", "¿Estás listo/a?"]],
    pattern: "I am · you / we / they are · he / she / it is",
    rule: {
      es: ["To be significa ser y estar.", "I → am · he / she / it → is · you / we / they → are.", "Negativo: añade not (I'm not, isn't, aren't).", "Pregunta: invierte el orden → Are you…? Is she…?", "La edad, el hambre o el frío van con be: I'm 30. I'm hungry."],
      en: ["To be describes identity, origin, age, feelings and location.", "I am · he/she/it is · you/we/they are.", "Negative: am not / isn't / aren't.", "Questions: invert the verb → Are you…? Is it…?"],
    },
    simple: { es: "Es un solo verbo para «ser» y «estar». Solo cambia según la persona: am, is, are.", en: "One verb for identity and states. Only three forms: am, is, are." },
    more: [["It's cold today.", "Hace frío hoy."], ["They are my colleagues.", "Son mis colegas."], ["Is the report ready?", "¿Está listo el informe?"]],
    items: [
      ["I ___ a student.", "am", ["is", "are"], "daily", "Soy estudiante."],
      ["She ___ my manager.", "is", ["are", "am"], "work", "Ella es mi jefa."],
      ["We ___ from Ecuador.", "are", ["is", "am"], "travel", "Somos de Ecuador."],
      ["___ you ready for the meeting?", "Are", ["Is", "Am"], "meeting", "¿Estás listo para la reunión?"],
      ["The valve ___ open.", "is", ["are", "am"], "eng", "La válvula está abierta."],
      ["They ___ not in the office today.", "are", ["is", "am"], "work", "Ellos no están en la oficina hoy."],
      ["I'm 28 years old. I ___ hungry now.", "am", ["have", "is"], "daily", "Tengo 28 años. Tengo hambre ahora."],
      ["The candidates ___ in the waiting room.", "are", ["is", "be"], "hr", "Los candidatos están en la sala de espera."],
      ["___ the inspection report ready?", "Is", ["Are", "Am"], "qa", "¿Está listo el informe de inspección?"],
      ["It ___ very hot in the plant.", "is", ["are", "has"], "oil", "Hace mucho calor en la planta."],
    ],
    challenge: { en: "Introduce yourself: name, job and where you are from.", es: "Preséntate: nombre, trabajo y de dónde eres.", check: "\\b(i am|i'm)\\b" },
    errors: ["have-years", "have-feeling", "missing-it"],
  },
  {
    id: "g.pronouns", level: "A1", title: "Pronouns", es: "Pronombres personales", icon: "👥",
    situation: { emoji: "📞", en: "Talking about people on your team.", es: "Hablando de las personas de tu equipo." },
    examples: [["She calls me every morning.", "Ella me llama cada mañana."], ["I know him.", "Lo conozco."], ["We work with them.", "Trabajamos con ellos."], ["Can you help us?", "¿Puedes ayudarnos?"]],
    pattern: "Subject: I you he she it we they · Object: me you him her it us them",
    rule: {
      es: ["Pronombres sujeto (antes del verbo): I, you, he, she, it, we, they.", "Pronombres objeto (después del verbo o de una preposición): me, you, him, her, it, us, them.", "It se usa para cosas y animales.", "En inglés siempre hay sujeto: It is late (no «Is late»).", "I siempre con mayúscula."],
      en: ["Subject pronouns go before the verb.", "Object pronouns go after a verb or preposition: with me, for them.", "Use it for things. English always needs a subject."],
    },
    simple: { es: "Antes del verbo: I, he, she, we, they. Después: me, him, her, us, them.", en: "Before the verb: I, he, she… After the verb: me, him, her…" },
    more: [["Give it to her.", "Dáselo a ella."], ["They like us.", "Les caemos bien."]],
    items: [
      ["Maria is my colleague. ___ is from Peru.", "She", ["Her", "He"], "work", "María es mi colega. Ella es de Perú."],
      ["Can you call ___ tomorrow? (a mí)", "me", ["I", "my"], "daily", "¿Puedes llamarme mañana?"],
      ["The supplier is late. Please email ___.", "him", ["he", "his"], "biz", "El proveedor llega tarde. Por favor escríbele."],
      ["John and I are engineers. ___ work in maintenance.", "We", ["Us", "They"], "eng", "John y yo somos ingenieros. Trabajamos en mantenimiento."],
      ["The pump is old. ___ needs maintenance.", "It", ["He", "Is"], "oil", "La bomba es vieja. Necesita mantenimiento."],
      ["The candidates are here. Please welcome ___.", "them", ["they", "their"], "hr", "Los candidatos están aquí. Por favor, dales la bienvenida."],
      ["This document is for ___ (nosotros).", "us", ["we", "our"], "law", "Este documento es para nosotros."],
      ["Where is Ana? I can't see ___.", "her", ["she", "hers"], "daily", "¿Dónde está Ana? No la veo."],
    ],
    challenge: { en: "Write two sentences about a colleague using he/she and him/her.", es: "Escribe dos frases sobre un colega usando he/she y him/her.", check: "\\b(he|she)\\b" },
    errors: ["explain-me", "lowercase-i", "missing-it"],
  },
  {
    id: "g.articles", level: "A1", title: "Articles: a, an, the", es: "Artículos: a, an, the", icon: "🔤",
    situation: { emoji: "🏢", en: "Describing your job and your office.", es: "Describiendo tu trabajo y tu oficina." },
    examples: [["I'm an engineer.", "Soy ingeniero."], ["She's a lawyer.", "Ella es abogada."], ["The office is on the second floor.", "La oficina está en el segundo piso."], ["I need an hour.", "Necesito una hora."]],
    pattern: "a + consonant sound · an + vowel sound · the = specific",
    rule: {
      es: ["A / an = un, una (algo no específico, singular).", "An antes de sonido vocal: an engineer, an hour. A antes de sonido consonante: a report, a university.", "The = el, la, los, las (algo específico o ya mencionado).", "Con profesiones se usa a / an: I'm a teacher (en español no usamos artículo).", "Para hablar en general no se usa the: I like coffee (no «I like the coffee»)."],
      en: ["a / an = one, non-specific. an before a vowel sound.", "the = specific or already mentioned.", "Use a / an with jobs: She's an auditor.", "No article for general plural or uncountable ideas: Engineers solve problems."],
    },
    simple: { es: "Un/una = a (o an si el sonido empieza con vocal). El/la = the.", en: "a/an = one of many. the = that specific one." },
    more: [["I have a question.", "Tengo una pregunta."], ["The question is difficult.", "La pregunta es difícil."], ["It's an interesting project.", "Es un proyecto interesante."]],
    items: [
      ["I'm ___ engineer.", "an", ["a", "the"], "eng", "Soy ingeniero."],
      ["She works in ___ bank.", "a", ["an", "the"], "daily", "Ella trabaja en un banco."],
      ["Please close ___ door. (la puerta de esta sala)", "the", ["a", "an"], "work", "Por favor, cierra la puerta."],
      ["We need ___ inspection before the release.", "an", ["a", "the"], "qa", "Necesitamos una inspección antes de la liberación."],
      ["He is ___ HR manager.", "an", ["a", "the"], "hr", "Él es gerente de RR. HH."],
      ["The meeting takes ___ hour.", "an", ["a", "the"], "meeting", "La reunión dura una hora."],
      ["She studies at ___ university in Quito.", "a", ["an", "the"], "daily", "Ella estudia en una universidad en Quito."],
      ["I have a contract. ___ contract is for two years.", "The", ["A", "An"], "law", "Tengo un contrato. El contrato es por dos años."],
      ["There is ___ leak in the pipeline.", "a", ["an", "the"], "oil", "Hay una fuga en la tubería."],
    ],
    challenge: { en: "Say what you and two family members do. Use a / an.", es: "Di a qué te dedicas tú y dos familiares. Usa a / an.", check: "\\b(a|an)\\s+\\w+" },
    errors: ["article-profession", "a-an", "an-a", "a-hour"],
  },
  {
    id: "g.plurals", level: "A1", title: "Plural nouns", es: "Sustantivos en plural", icon: "📦",
    situation: { emoji: "🛒", en: "Ordering materials for a project.", es: "Pidiendo materiales para un proyecto." },
    examples: [["two reports", "dos informes"], ["three boxes", "tres cajas"], ["five companies", "cinco empresas"], ["two men and three women", "dos hombres y tres mujeres"], ["People are friendly.", "La gente es amable."]],
    pattern: "+s · +es (s, sh, ch, x) · y → ies · irregular: man→men, person→people",
    rule: {
      es: ["La mayoría: + s (valve → valves).", "Terminadas en s, sh, ch, x: + es (box → boxes).", "Consonante + y: y → ies (company → companies).", "Irregulares: man → men, woman → women, child → children, person → people, foot → feet.", "People es plural: people are.", "Incontables sin plural: information, advice, equipment."],
      en: ["Most nouns add -s. Nouns ending in s/sh/ch/x add -es.", "Consonant + y → -ies.", "Irregular: men, women, children, people, feet, teeth.", "Uncountable nouns have no plural: information, equipment, advice."],
    },
    simple: { es: "Casi siempre se añade -s. Algunas palabras cambian: man → men, person → people.", en: "Add -s. Learn a few special ones: men, women, people, children." },
    more: [["Two employees are on vacation.", "Dos empleados están de vacaciones."], ["The children are at school.", "Los niños están en la escuela."]],
    items: [
      ["We have three ___ (box).", "boxes", ["boxs", "box"], "work", "Tenemos tres cajas."],
      ["There are five ___ (company) in the tender.", "companies", ["companys", "company"], "biz", "Hay cinco empresas en la licitación."],
      ["Many ___ (person) work here.", "people", ["persons", "peoples"], "work", "Mucha gente trabaja aquí."],
      ["The ___ (child) are at school.", "children", ["childs", "childrens"], "daily", "Los niños están en la escuela."],
      ["Please check all the ___ (valve).", "valves", ["valvs", "valvees"], "eng", "Por favor revisa todas las válvulas."],
      ["People ___ very friendly here.", "are", ["is", "be"], "travel", "La gente es muy amable aquí."],
      ["We need more ___ about the candidate.", "information", ["informations", "an information"], "hr", "Necesitamos más información sobre el candidato."],
      ["Two ___ (woman) are on the board.", "women", ["womans", "woman"], "law", "Dos mujeres están en la junta."],
    ],
    challenge: { en: "Describe what is on your desk. Use at least three plural nouns.", es: "Describe qué hay en tu escritorio. Usa al menos tres plurales.", check: "\\b\\w+(s|es)\\b" },
    errors: ["people-is", "uncountable-plural"],
  },
  {
    id: "g.possessives", level: "A1", title: "Possessives", es: "Posesivos (my, your, 's)", icon: "🔑",
    situation: { emoji: "👨‍👩‍👧", en: "Showing photos of your family.", es: "Mostrando fotos de tu familia." },
    examples: [["This is my sister.", "Esta es mi hermana."], ["Her name is Carla.", "Su nombre es Carla."], ["It's Pedro's laptop.", "Es la laptop de Pedro."], ["Our office is small.", "Nuestra oficina es pequeña."], ["Is this yours?", "¿Esto es tuyo?"]],
    pattern: "my your his her its our their · Pedro's = de Pedro · mine yours his hers ours theirs",
    rule: {
      es: ["Adjetivos posesivos (antes del sustantivo): my, your, his (de él), her (de ella), its (de una cosa), our, their.", "His = de él, her = de ella: en español ambos son «su».", "'s indica posesión: Ana's car = el auto de Ana. Plural: the managers' office.", "Pronombres posesivos (sin sustantivo): mine, yours, his, hers, ours, theirs.", "It's = it is; its = su (de una cosa)."],
      en: ["Possessive adjectives go before a noun: my, your, his, her, its, our, their.", "Use 's for people: the client's request.", "Possessive pronouns replace the noun: mine, yours, hers."],
    },
    simple: { es: "«Su» en inglés depende de quién: his (él), her (ella), their (ellos).", en: "his = belongs to a man, her = to a woman, their = to them." },
    more: [["Their project is late.", "Su proyecto (de ellos) está atrasado."], ["The company changed its logo.", "La empresa cambió su logo."]],
    items: [
      ["This is Carlos. ___ job is interesting.", "His", ["Her", "Its"], "work", "Este es Carlos. Su trabajo es interesante."],
      ["Ana is here with ___ husband.", "her", ["his", "their"], "daily", "Ana está aquí con su esposo."],
      ["This is ___ car. (el auto de mi jefe)", "my boss's", ["my boss", "my bosses"], "daily", "Este es el auto de mi jefe."],
      ["The pump and ___ motor are new.", "its", ["it's", "his"], "eng", "La bomba y su motor son nuevos."],
      ["We love ___ new office.", "our", ["us", "ours"], "work", "Nos encanta nuestra nueva oficina."],
      ["The employees know ___ rights.", "their", ["they", "there"], "hr", "Los empleados conocen sus derechos."],
      ["Is this pen yours? — Yes, it's ___.", "mine", ["my", "me"], "daily", "¿Esta pluma es tuya? — Sí, es mía."],
      ["The ___ signature is missing. (del cliente)", "client's", ["clients", "client"], "law", "Falta la firma del cliente."],
    ],
    challenge: { en: "Describe a member of your family: name, job, and one thing they have.", es: "Describe a un familiar: nombre, trabajo y algo que tenga.", check: "\\b(my|his|her|their|our)\\b" },
    errors: ["said-that-me"],
  },
  {
    id: "g.there-is", level: "A1", title: "There is / There are", es: "Hay: there is / there are", icon: "🏠",
    situation: { emoji: "🏨", en: "Describing a hotel room or a workplace.", es: "Describiendo una habitación de hotel o un lugar de trabajo." },
    examples: [["There is a bank near the hotel.", "Hay un banco cerca del hotel."], ["There are two meeting rooms.", "Hay dos salas de reuniones."], ["Is there a problem?", "¿Hay algún problema?"], ["There aren't any chairs.", "No hay sillas."]],
    pattern: "There is + singular · There are + plural · Is there…? Are there…?",
    rule: {
      es: ["«Hay» = there is (singular / incontable) o there are (plural).", "Negativo: there isn't / there aren't (any).", "Pregunta: Is there…? / Are there…?", "No digas «It has» para «hay»: There is a pool (no «It has a pool»)."],
      en: ["There is + singular or uncountable noun.", "There are + plural noun.", "Questions: Is there…? Are there…? Negative with any."],
    },
    simple: { es: "Hay uno → there is. Hay varios → there are.", en: "One thing → there is. Many → there are." },
    more: [["There is some water on the floor.", "Hay agua en el piso."], ["Are there any questions?", "¿Hay alguna pregunta?"]],
    items: [
      ["___ a problem with the printer.", "There is", ["There are", "It has"], "work", "Hay un problema con la impresora."],
      ["___ three hotels near the airport.", "There are", ["There is", "Have"], "travel", "Hay tres hoteles cerca del aeropuerto."],
      ["___ any questions?", "Are there", ["Is there", "There are"], "meeting", "¿Hay alguna pregunta?"],
      ["There ___ a crack in the weld.", "is", ["are", "has"], "qa", "Hay una grieta en la soldadura."],
      ["There ___ any vacancies at the moment.", "aren't", ["isn't", "not"], "hr", "No hay vacantes por el momento."],
      ["___ a restaurant in the hotel?", "Is there", ["Are there", "Has"], "travel", "¿Hay un restaurante en el hotel?"],
      ["There ___ two pumps on the platform.", "are", ["is", "be"], "oil", "Hay dos bombas en la plataforma."],
      ["There ___ some information in the contract about penalties.", "is", ["are", "have"], "law", "Hay información en el contrato sobre penalidades."],
    ],
    challenge: { en: "Describe your home or office with there is / there are.", es: "Describe tu casa u oficina con there is / there are.", check: "\\bthere (is|are|'s)\\b" },
    errors: [],
  },
  {
    id: "g.have-has", level: "A1", title: "Have / Has", es: "Tener: have / has", icon: "🎒",
    situation: { emoji: "📋", en: "Checking what the team has for the project.", es: "Revisando lo que el equipo tiene para el proyecto." },
    examples: [["I have two brothers.", "Tengo dos hermanos."], ["She has a meeting at 10.", "Ella tiene una reunión a las 10."], ["Do you have a pen?", "¿Tienes una pluma?"], ["He doesn't have a car.", "Él no tiene auto."]],
    pattern: "I / you / we / they have · he / she / it has · do / does + have",
    rule: {
      es: ["Have = tener. Con he / she / it → has.", "Negativo: don't have / doesn't have (¡no «doesn't has»!).", "Pregunta: Do you have…? Does she have…?", "Ojo: la edad, el hambre, el frío van con be, no con have."],
      en: ["have / has for possession, relationships and appointments.", "Negative and questions use do/does + have (base form)."],
    },
    simple: { es: "Tengo = I have. Él tiene = he has.", en: "have, but has for he/she/it." },
    more: [["We have a problem.", "Tenemos un problema."], ["Does the room have Wi-Fi?", "¿La habitación tiene Wi-Fi?"]],
    items: [
      ["She ___ two children.", "has", ["have", "haves"], "daily", "Ella tiene dos hijos."],
      ["We ___ a meeting at nine.", "have", ["has", "are"], "meeting", "Tenemos una reunión a las nueve."],
      ["___ you have a reservation?", "Do", ["Does", "Are"], "travel", "¿Tiene una reserva?"],
      ["The company ___ 200 employees.", "has", ["have", "is"], "hr", "La empresa tiene 200 empleados."],
      ["He doesn't ___ the certificate.", "have", ["has", "having"], "qa", "Él no tiene el certificado."],
      ["___ the room have air conditioning?", "Does", ["Do", "Has"], "travel", "¿La habitación tiene aire acondicionado?"],
      ["The new valve ___ a manual override.", "has", ["have", "is"], "eng", "La válvula nueva tiene un accionamiento manual."],
      ["I ___ 30 years old.", "am", ["have", "has"], "daily", "Tengo 30 años."],
    ],
    challenge: { en: "Say three things you have and one thing you don't have.", es: "Di tres cosas que tienes y una que no tienes.", check: "\\b(have|has)\\b" },
    errors: ["have-years", "have-feeling"],
  },
  {
    id: "g.present-simple", level: "A1", title: "Present Simple", es: "Presente simple (rutinas y hechos)", icon: "🔁",
    situation: { emoji: "⏰", en: "Carlos describes his normal workday.", es: "Carlos describe su día normal de trabajo." },
    examples: [["I start work at eight.", "Empiezo a trabajar a las ocho."], ["He checks the reports every morning.", "Él revisa los informes cada mañana."], ["She doesn't work on Sundays.", "Ella no trabaja los domingos."], ["Do you drink coffee?", "¿Tomas café?"], ["Water boils at 100 °C.", "El agua hierve a 100 °C."]],
    pattern: "I work · he works · I don't work · he doesn't work · Do you work? · Does he work?",
    rule: {
      es: ["Se usa para rutinas, hábitos y hechos.", "Con he / she / it el verbo lleva -s: he works, she goes, it has.", "Negativo: don't / doesn't + verbo base (she doesn't work).", "Pregunta: Do / Does + sujeto + verbo base (Does he work?).", "Con does / doesn't el verbo NO lleva -s.", "Palabras típicas: every day, usually, always, never, on Mondays."],
      en: ["Use it for routines, habits and facts.", "Add -s/-es for he/she/it.", "Use do/does in questions and negatives, with the base verb."],
    },
    simple: { es: "Lo que haces siempre o normalmente. Solo recuerda la -s con he / she / it.", en: "Things you do regularly. Remember the -s for he / she / it." },
    more: [["The plant operates 24 hours a day.", "La planta opera 24 horas al día."], ["HR reviews salaries every year.", "RR. HH. revisa los salarios cada año."], ["What time does the store open?", "¿A qué hora abre la tienda?"]],
    items: [
      ["He ___ to work by bus.", "goes", ["go", "going"], "daily", "Él va al trabajo en autobús."],
      ["She ___ like coffee.", "doesn't", ["don't", "isn't"], "daily", "A ella no le gusta el café."],
      ["___ you work on Saturdays?", "Do", ["Does", "Are"], "work", "¿Trabajas los sábados?"],
      ["The inspector ___ every weld.", "checks", ["check", "checking"], "qa", "El inspector revisa cada soldadura."],
      ["The plant ___ 24 hours a day.", "operates", ["operate", "is operate"], "oil", "La planta opera 24 horas al día."],
      ["___ the manager approve the vacation requests?", "Does", ["Do", "Is"], "hr", "¿El gerente aprueba las solicitudes de vacaciones?"],
      ["We usually ___ the meeting at 9 a.m.", "start", ["starts", "starting"], "meeting", "Normalmente empezamos la reunión a las 9 a. m."],
      ["The contract ___ in March.", "ends", ["end", "ending"], "law", "El contrato termina en marzo."],
      ["My sister ___ in a hospital.", "works", ["work", "is work"], "daily", "Mi hermana trabaja en un hospital."],
      ["The system ___ the data every hour.", "updates", ["update", "updating"], "eng", "El sistema actualiza los datos cada hora."],
    ],
    challenge: { en: "Describe your normal day in three sentences. Include he/she once.", es: "Describe tu día normal en tres frases. Incluye he/she una vez.", check: "\\b(he|she)\\s+\\w+s\\b" },
    errors: ["third-person-s", "third-person-dont", "adverb-start", "like-very-much"],
  },
  {
    id: "g.present-continuous", level: "A1", title: "Present Continuous", es: "Presente continuo (ahora mismo)", icon: "▶️",
    situation: { emoji: "📱", en: "Your manager calls: 'What are you doing right now?'", es: "Tu jefe llama: «¿Qué estás haciendo ahora?»" },
    examples: [["I'm writing the report.", "Estoy escribiendo el informe."], ["They're checking the pump.", "Están revisando la bomba."], ["It isn't raining.", "No está lloviendo."], ["Are you listening?", "¿Estás escuchando?"], ["We're meeting the client on Friday.", "Nos reunimos con el cliente el viernes."]],
    pattern: "am / is / are + verb-ing",
    rule: {
      es: ["Acción que ocurre ahora o en este período: I'm working from home this week.", "Forma: be (am / is / are) + verbo -ing.", "Planes ya organizados: We're meeting the client on Friday.", "Ortografía: write → writing, run → running, study → studying.", "Verbos de estado normalmente no van en -ing: know, want, like, need (I know, no «I'm knowing»)."],
      en: ["Use it for actions happening now or around now, and fixed future arrangements.", "Form: am/is/are + -ing.", "State verbs (know, want, need) usually don't take -ing."],
    },
    simple: { es: "Lo que pasa ahora mismo: estoy + -ando/-iendo = am/is/are + -ing.", en: "Happening now: be + -ing." },
    more: [["The technicians are replacing the seal.", "Los técnicos están cambiando el sello."], ["She's interviewing a candidate.", "Ella está entrevistando a un candidato."]],
    items: [
      ["I ___ the report right now.", "am writing", ["write", "writing"], "work", "Estoy escribiendo el informe ahora mismo."],
      ["They ___ the pump at the moment.", "are checking", ["check", "is checking"], "oil", "Están revisando la bomba en este momento."],
      ["Look! It ___.", "is raining", ["rains", "raining"], "daily", "¡Mira! Está lloviendo."],
      ["___ you listening to me?", "Are", ["Do", "Is"], "daily", "¿Me estás escuchando?"],
      ["Sarah ___ a candidate now.", "is interviewing", ["interviews", "interviewing"], "hr", "Sarah está entrevistando a un candidato ahora."],
      ["We ___ the client on Friday. It's in my calendar.", "are meeting", ["meet", "meeting"], "meeting", "Nos reunimos con el cliente el viernes. Está en mi calendario."],
      ["I ___ what you mean.", "understand", ["am understanding", "understanding"], "daily", "Entiendo lo que quieres decir."],
      ["The auditor ___ the records this week.", "is reviewing", ["reviews", "review"], "qa", "El auditor está revisando los registros esta semana."],
    ],
    challenge: { en: "Say what three people you know are doing right now.", es: "Di qué están haciendo ahora tres personas que conoces.", check: "\\b(am|is|are|'m|'s|'re)\\s+\\w+ing\\b" },
    errors: [],
  },
  {
    id: "g.prepositions", level: "A1", title: "Prepositions: in, on, at", es: "Preposiciones de tiempo y lugar", icon: "📍",
    situation: { emoji: "🗓️", en: "Scheduling an inspection with a supplier.", es: "Programando una inspección con un proveedor." },
    examples: [["The meeting is on Monday at 10.", "La reunión es el lunes a las 10."], ["I was born in 1995.", "Nací en 1995."], ["She's at the airport.", "Ella está en el aeropuerto."], ["The file is on the desk.", "El archivo está en el escritorio."], ["We live in Guayaquil.", "Vivimos en Guayaquil."]],
    pattern: "AT time/point · ON day/surface · IN month, year, city, inside",
    rule: {
      es: ["Tiempo: at + hora (at 5 p.m., at night) · on + día/fecha (on Monday, on 3 May) · in + mes/año/estación/partes del día (in July, in 2025, in the morning).", "Lugar: at + punto concreto (at the airport, at work) · on + superficie (on the table, on the second floor) · in + dentro / ciudad / país (in the box, in Quito).", "Sin preposición: go home, next week, last year, this morning."],
      en: ["Time: at + clock time, on + days/dates, in + months/years/seasons.", "Place: at + a point, on + a surface, in + an enclosed space or city/country.", "No preposition with next, last, this, home."],
    },
    simple: { es: "AT = punto exacto. ON = día o superficie. IN = dentro o período largo.", en: "AT = exact point, ON = day/surface, IN = inside/long period." },
    more: [["The audit is in March.", "La auditoría es en marzo."], ["See you on Friday!", "¡Nos vemos el viernes!"], ["Meet me at the gate.", "Encuéntrame en la puerta de embarque."]],
    items: [
      ["The meeting is ___ Monday.", "on", ["in", "at"], "meeting", "La reunión es el lunes."],
      ["My flight leaves ___ 6:30.", "at", ["in", "on"], "travel", "Mi vuelo sale a las 6:30."],
      ["The audit is ___ March.", "in", ["on", "at"], "qa", "La auditoría es en marzo."],
      ["I'm ___ the airport now.", "at", ["on", "in the"], "travel", "Estoy en el aeropuerto ahora."],
      ["The drawings are ___ the table.", "on", ["in", "at"], "eng", "Los planos están sobre la mesa."],
      ["I study English ___ the morning.", "in", ["at", "on"], "daily", "Estudio inglés en la mañana."],
      ["The contract was signed ___ 2023.", "in", ["on", "at"], "law", "El contrato se firmó en 2023."],
      ["She works ___ night.", "at", ["in", "on"], "hr", "Ella trabaja de noche."],
      ["The valve is ___ the second floor.", "on", ["in", "at"], "oil", "La válvula está en el segundo piso."],
      ["We live ___ Quito.", "in", ["at", "on"], "daily", "Vivimos en Quito."],
    ],
    challenge: { en: "Describe your week: use at, on and in at least once each.", es: "Describe tu semana: usa at, on e in al menos una vez.", check: "\\bon\\b[\\s\\S]*\\bat\\b|\\bat\\b[\\s\\S]*\\bon\\b" },
    errors: ["prep-days", "prep-months", "prep-morning", "prep-night", "prep-weekend", "arrive-to", "go-to-home", "depend-of"],
  },
  {
    id: "g.can", level: "A1", title: "Can / Can't", es: "Poder: can / can't", icon: "💪",
    situation: { emoji: "🧑‍💼", en: "A job interview: 'What can you do?'", es: "Una entrevista: «¿Qué sabes hacer?»" },
    examples: [["I can speak Spanish and English.", "Hablo español e inglés."], ["She can't come today.", "Ella no puede venir hoy."], ["Can you help me?", "¿Puedes ayudarme?"], ["Can I ask a question?", "¿Puedo hacer una pregunta?"]],
    pattern: "can + base verb (no to, no -s) · Can you…?",
    rule: {
      es: ["Can = poder / saber hacer (habilidad, posibilidad, permiso, pedidos).", "Es igual para todas las personas: he can (no «he cans»).", "Después va el verbo base sin to: I can swim (no «I can to swim»).", "Negativo: can't / cannot. Pregunta: Can you…? (sin do)."],
      en: ["can for ability, possibility, permission and requests.", "Same form for all persons; base verb without to.", "Questions: Can you…? — never Do you can…?"],
    },
    simple: { es: "Can + verbo. Nada más: sin to, sin -s, sin do.", en: "can + verb. No to, no -s, no do." },
    more: [["Can you send me the file?", "¿Puedes enviarme el archivo?"], ["We can't start without the permit.", "No podemos empezar sin el permiso."]],
    items: [
      ["She ___ speak three languages.", "can", ["cans", "can to"], "daily", "Ella habla tres idiomas."],
      ["___ you help me with this?", "Can", ["Do you can", "Are"], "work", "¿Me puedes ayudar con esto?"],
      ["We ___ start the work without a permit.", "can't", ["don't can", "not can"], "oil", "No podemos empezar el trabajo sin permiso."],
      ["___ I ask a question?", "Can", ["Do", "Am"], "meeting", "¿Puedo hacer una pregunta?"],
      ["He can ___ the machine.", "operate", ["operates", "to operate"], "eng", "Él sabe operar la máquina."],
      ["Candidates ___ apply online.", "can", ["cans", "can to"], "hr", "Los candidatos pueden postular en línea."],
      ["Can you ___ me the invoice?", "send", ["sends", "to send"], "biz", "¿Puedes enviarme la factura?"],
    ],
    challenge: { en: "Write three things you can do and one you can't do.", es: "Escribe tres cosas que sabes hacer y una que no.", check: "\\bcan'?t?\\b" },
    errors: ["do-you-can"],
  },
  {
    id: "g.questions", level: "A1", title: "Question words", es: "Palabras para preguntar", icon: "❓",
    situation: { emoji: "🛂", en: "At immigration: the officer asks you questions.", es: "En migración: el oficial te hace preguntas." },
    examples: [["What's your name?", "¿Cómo te llamas?"], ["Where are you from?", "¿De dónde eres?"], ["How long are you staying?", "¿Cuánto tiempo te quedas?"], ["Why are you here?", "¿Por qué estás aquí?"], ["What does 'MTR' mean?", "¿Qué significa «MTR»?"]],
    pattern: "Wh- + auxiliary (be / do / can) + subject + verb",
    rule: {
      es: ["What (qué), Where (dónde), When (cuándo), Who (quién), Why (por qué), How (cómo), How much / many (cuánto/s), How long (cuánto tiempo), Which (cuál).", "Orden: palabra interrogativa + auxiliar + sujeto + verbo: Where do you work?", "«¿Cómo se llama esto?» = What is it called?", "«¿Qué significa…?» = What does … mean?"],
      en: ["Question word + auxiliary + subject + main verb.", "What is it called? What does X mean?", "How much (uncountable) / How many (countable)."],
    },
    simple: { es: "Pregunta + auxiliar + persona + verbo: Where do you live?", en: "Wh-word + do/does/is + subject + verb." },
    more: [["How much does it cost?", "¿Cuánto cuesta?"], ["Which gate is it?", "¿Qué puerta es?"], ["Who is responsible for this?", "¿Quién es responsable de esto?"]],
    items: [
      ["___ are you from?", "Where", ["What", "Who"], "travel", "¿De dónde eres?"],
      ["___ does the meeting start?", "When", ["Who", "Which"], "meeting", "¿Cuándo empieza la reunión?"],
      ["What does 'NCR' ___?", "mean", ["means", "meaning"], "qa", "¿Qué significa «NCR»?"],
      ["How ___ does it cost?", "much", ["many", "long"], "travel", "¿Cuánto cuesta?"],
      ["How ___ employees work here?", "many", ["much", "long"], "hr", "¿Cuántos empleados trabajan aquí?"],
      ["___ is responsible for the valve inspection?", "Who", ["Where", "How"], "eng", "¿Quién es responsable de la inspección de la válvula?"],
      ["What is this tool ___?", "called", ["call", "name"], "eng", "¿Cómo se llama esta herramienta?"],
      ["___ did you choose this supplier?", "Why", ["What", "Who"], "biz", "¿Por qué eligieron a este proveedor?"],
    ],
    challenge: { en: "Write three questions to ask a new colleague.", es: "Escribe tres preguntas para un nuevo colega.", check: "\\?" },
    errors: ["how-called", "what-means", "make-question"],
  },
];
