// Explicaciones profundas B1–C2 (apuntes de estudio).
export default {
  "g.present-perfect-2": {
    intro: "Además de experiencias, el Present Perfect expresa situaciones que empezaron en el pasado y siguen hoy (for / since) y acciones recientes con resultado presente (just, already, yet).",
    form: { cols: ["Palabra", "Significado", "Posición", "Ejemplo"], rows: [
      ["for", "durante / desde hace (duración)", "antes del período", "I've lived here for ten years."], ["since", "desde (punto de inicio)", "antes del momento", "I've lived here since 2015."],
      ["just", "acabar de", "entre have y participio", "I've just finished."], ["already", "ya (antes de lo esperado)", "entre have y participio", "She's already sent it."],
      ["yet", "ya (pregunta) / todavía (negativa)", "al final", "Have you finished yet? I haven't finished yet."], ["How long…?", "¿Cuánto tiempo…?", "inicio", "How long have you worked here?"],
    ] },
    form2: { title: "for vs since", cols: ["for + período", "since + punto de inicio"], rows: [["for two hours", "since 9 a.m."], ["for three days", "since Monday"], ["for five years", "since 2020"], ["for a long time", "since I was a child"]] },
    uses: [["Estado que continúa", "We've known each other since university.", "Nos conocemos desde la universidad."], ["Acción reciente", "The client has just called.", "El cliente acaba de llamar."], ["Noticias y cambios", "Prices have gone up this year.", "Los precios han subido este año."], ["Periodo no terminado", "I've had three meetings today.", "He tenido tres reuniones hoy."]],
    mistakes: [["I work here since 2019.", "I've worked here since 2019.", "Empieza en el pasado y sigue → present perfect."], ["since three years", "for three years", "Duración → for."], ["I've finished it yesterday.", "I finished it yesterday.", "Con yesterday → past simple."], ["Have you finished already? (pregunta neutra)", "Have you finished yet?", "yet en preguntas."]],
    spanish: "«Trabajo aquí desde hace 5 años» usa presente en español, pero en inglés es present perfect: I've worked here for five years. Es uno de los errores más comunes de hispanohablantes.",
    tips: ["Si en español dices «desde hace» o «desde», piensa en present perfect.", "Cuidado en británico vs americano: en EE. UU. se oye «Did you eat yet?», pero en exámenes usa present perfect."],
  },
  "g.present-perfect-continuous": {
    intro: "Enfatiza la DURACIÓN de una actividad que empezó en el pasado y continúa (o acaba de terminar y vemos el resultado).",
    form: { cols: ["", "Forma", "Ejemplo"], rows: [["✅", "have / has been + verb-ing", "I've been waiting for an hour."], ["❌", "haven't / hasn't been + verb-ing", "She hasn't been sleeping well."], ["❓", "Have / Has + sujeto + been + verb-ing?", "How long have you been studying English?"]] },
    uses: [["Duración hasta ahora", "We've been testing the system for two weeks.", "Llevamos dos semanas probando el sistema."], ["Resultado visible de una actividad reciente", "You're tired. Have you been running?", "Estás cansado. ¿Has estado corriendo?"], ["Actividades repetidas", "I've been calling him all morning.", "Lo he estado llamando toda la mañana."]],
    form2: { title: "Simple vs continuo", cols: ["Present Perfect Simple", "Present Perfect Continuous"], rows: [["Resultado / cantidad: I've written three reports.", "Actividad / duración: I've been writing reports all day."], ["Verbos de estado: I've known him for years.", "No con verbos de estado (know, like, own…)."]] },
    mistakes: [["I'm waiting for an hour.", "I've been waiting for an hour.", "Duración hasta ahora."], ["I've been knowing her.", "I've known her.", "know es de estado."]],
    spanish: "Equivale a «llevar + gerundio»: Llevo una hora esperando = I've been waiting for an hour.",
    tips: ["«Llevo X haciendo algo» → have been + -ing + for X."],
  },
  "g.past-perfect": {
    intro: "El Past Perfect es el «pasado del pasado»: una acción que ocurrió ANTES de otra acción pasada.",
    form: { cols: ["", "Forma", "Ejemplo"], rows: [["✅", "had + participio", "The train had left."], ["❌", "hadn't + participio", "I hadn't seen it before."], ["❓", "Had + sujeto + participio?", "Had you met him before?"]] },
    uses: [["Acción anterior", "When I arrived, the meeting had started.", "Cuando llegué, la reunión había empezado."], ["Explicar causas en un informe", "The pump failed because the bearing had worn out.", "La bomba falló porque el rodamiento se había desgastado."], ["Con by the time", "By the time we arrived, they had finished.", "Para cuando llegamos, habían terminado."], ["Estilo indirecto", "She said she had seen the email.", "Dijo que había visto el correo."]],
    signals: ["before", "after", "by the time", "already", "when", "never … before"],
    mistakes: [["When I arrived, the meeting started. (si empezó antes)", "When I arrived, the meeting had started.", "Sin past perfect cambia el sentido."]],
    spanish: "Equivale al pluscuamperfecto: «había + participio».",
    tips: ["Dibuja una línea del tiempo: la acción más antigua → had + participio."],
  },
  "g.first-conditional": {
    intro: "El primer condicional habla de situaciones REALES y probables en el futuro: si pasa A, pasará B.",
    form: { cols: ["Condición (if)", "Resultado"], rows: [["If + present simple", "will / won't + verbo"], ["If it rains,", "we'll postpone the inspection."], ["If you don't hurry,", "you'll miss the bus."]] },
    form2: { title: "Otras palabras de condición", cols: ["Palabra", "Significado", "Ejemplo"], rows: [["unless", "a menos que (= if not)", "We won't finish unless we get help."], ["when", "cuando (es seguro)", "When I arrive, I'll call you."], ["as soon as", "en cuanto", "As soon as I know, I'll tell you."], ["in case", "por si", "Take an umbrella in case it rains."]] },
    uses: [["Consecuencias probables", "If the pressure drops, the alarm will sound.", "Si baja la presión, sonará la alarma."], ["Advertencias y promesas", "If you sign today, we'll deliver next week.", "Si firma hoy, entregamos la próxima semana."], ["Con imperativo", "If you have questions, call me.", "Si tiene preguntas, llámeme."]],
    mistakes: [["If it will rain…", "If it rains…", "No will después de if."], ["If you will send it, I review it.", "If you send it, I'll review it.", "El will va en el resultado."]],
    spanish: "Igual que en español: «Si llueve, nos quedaremos». Presente después de «si» y futuro en el resultado.",
    tips: ["La coma solo se pone si if va primero: If it rains, we'll stay. / We'll stay if it rains."],
  },
  "g.second-conditional": {
    intro: "El segundo condicional imagina situaciones irreales o improbables en el presente o futuro.",
    form: { cols: ["Condición", "Resultado"], rows: [["If + past simple", "would / wouldn't + verbo"], ["If I had more time,", "I would travel more."], ["If I were you,", "I'd accept the offer."]] },
    uses: [["Situación imaginaria", "If I won the lottery, I'd buy a house.", "Si ganara la lotería, compraría una casa."], ["Consejo", "If I were you, I'd talk to HR.", "Yo que tú, hablaría con RR. HH."], ["Pedido muy cortés", "Would it be possible to change the date?", "¿Sería posible cambiar la fecha?"]],
    form2: { title: "Primer vs segundo condicional", cols: ["1.º (real)", "2.º (imaginario)"], rows: [["If I get the job, I'll move. (es posible)", "If I got the job, I'd move. (no creo que pase)"]] },
    mistakes: [["If I would have…", "If I had…", "No would en la parte del if."], ["If I was you…", "If I were you…", "Forma recomendada en inglés formal y exámenes."]],
    spanish: "Equivale a «Si + imperfecto de subjuntivo, condicional»: Si tuviera…, haría…",
    tips: ["'d puede ser would o had: I'd go (would) / I'd gone (had)."],
  },
  "g.used-to": {
    intro: "«Used to» habla de hábitos o estados del pasado que ya no son ciertos.",
    form: { cols: ["", "Forma", "Ejemplo"], rows: [["✅", "used to + verbo base", "I used to smoke."], ["❌", "didn't use to + verbo", "We didn't use to have a car."], ["❓", "Did + sujeto + use to…?", "Did you use to play soccer?"]] },
    form2: { title: "Tres expresiones parecidas", cols: ["Expresión", "Significado", "Ejemplo"], rows: [["used to + verbo", "solía (ya no)", "I used to live in Quito."], ["be used to + -ing / sustantivo", "estar acostumbrado", "I'm used to working at night."], ["get used to + -ing", "acostumbrarse", "You'll get used to the cold."]] },
    uses: [["Hábitos pasados", "I used to walk to school.", "Caminaba a la escuela."], ["Estados pasados", "This building used to be a factory.", "Este edificio era una fábrica."]],
    mistakes: [["I use to play.", "I used to play.", "En afirmativo lleva -d."], ["Did you used to…?", "Did you use to…?", "Con did, sin -d."], ["I'm used to work late.", "I'm used to working late.", "be used to + -ing."]],
    spanish: "Equivale a «solía» o al imperfecto «jugaba».",
    tips: ["Si ya no pasa → used to. Si ahora es normal para ti → be used to."],
  },
  "g.passive": {
    intro: "En la voz pasiva el protagonista es la acción o el objeto, no quien la hace. Es muy común en informes, procedimientos, contratos y noticias.",
    form: { cols: ["Tiempo", "Activa", "Pasiva (be + participio)"], rows: [
      ["Present simple", "They inspect the valves.", "The valves are inspected."], ["Past simple", "They inspected the valve.", "The valve was inspected."], ["Present continuous", "They are testing the system.", "The system is being tested."],
      ["Present perfect", "They have updated the policy.", "The policy has been updated."], ["Future", "They will publish the results.", "The results will be published."], ["Modal", "You must sign the form.", "The form must be signed."],
    ] },
    uses: [["No importa / no sabemos quién", "My car was stolen.", "Me robaron el auto."], ["Informes técnicos", "The samples were tested in the lab.", "Las muestras se analizaron en el laboratorio."], ["Procesos", "The oil is pumped to the tanks.", "El petróleo se bombea a los tanques."], ["Con agente (by)", "The report was written by the lead auditor.", "El informe fue escrito por el auditor líder."], ["«Se» impersonal", "English is spoken here.", "Aquí se habla inglés."]],
    mistakes: [["The valve was inspect.", "The valve was inspected.", "Falta el participio."], ["The report wrote by Ana.", "The report was written by Ana.", "Falta be."], ["It was builded.", "It was built.", "Participio irregular."]],
    spanish: "El «se» impersonal (se habla, se fabrican) casi siempre se traduce con pasiva: English is spoken, cars are made.",
    tips: ["Fórmula mágica: BE (en el tiempo correcto) + PARTICIPIO.", "Usa by solo si quién lo hizo es importante."],
  },
  "g.relative-clauses": {
    intro: "Las oraciones de relativo añaden información sobre una persona, cosa o lugar sin empezar una frase nueva.",
    form: { cols: ["Pronombre", "Para", "Ejemplo"], rows: [["who", "personas", "The engineer who designed it is here."], ["which", "cosas / animales", "The pump which failed is old."], ["that", "personas o cosas (definitorias)", "The report that I sent…"], ["where", "lugares", "The plant where I work…"], ["whose", "posesión (cuyo)", "The supplier whose price was lowest…"], ["when", "tiempo", "The day when we met…"]] },
    form2: { title: "Definitorias vs explicativas", cols: ["Definitoria (sin comas)", "Explicativa (con comas)"], rows: [["Identifica: The man who called is my boss.", "Información extra: My boss, who is from Chile, called."], ["Puedes usar that", "NO puedes usar that"], ["Puedes omitir el pronombre si es objeto: the report (that) I sent", "No se omite"]] },
    uses: [["Definir personas en el trabajo", "We need someone who speaks English.", "Necesitamos a alguien que hable inglés."], ["Describir documentos", "This is the clause which covers liability.", "Esta es la cláusula que cubre la responsabilidad."]],
    mistakes: [["The man which…", "The man who…", "Personas → who."], ["My boss, that is from Chile, …", "My boss, who is from Chile, …", "Con comas no se usa that."], ["The report that I sent it.", "The report that I sent.", "No repitas el objeto."]],
    spanish: "«Que» se traduce who, which o that según el antecedente. «Cuyo» = whose. «Donde» = where.",
    tips: ["Persona → who. Cosa → which / that. Lugar → where. Dueño → whose."],
  },
  "g.gerunds-infinitives": {
    intro: "Cuando un verbo va después de otro, puede ir con -ing (gerundio) o con to + verbo (infinitivo). Depende del primer verbo.",
    form: { cols: ["Estructura", "Verbos", "Ejemplo"], rows: [
      ["verbo + -ing", "enjoy, finish, avoid, suggest, consider, mind, keep, practice, recommend, admit, deny", "I enjoy working with people."],
      ["verbo + to + verbo", "want, need, decide, plan, hope, agree, expect, promise, refuse, learn, would like", "I decided to apply."],
      ["verbo + persona + to", "want, ask, tell, would like, expect, allow, remind", "I'd like you to send it."],
      ["preposición + -ing", "interested in, good at, before, after, without, instead of, look forward to", "I'm interested in learning Python."],
      ["-ing como sujeto", "", "Smoking is not allowed."], ["to para propósito (para)", "", "I study to get a better job."],
    ] },
    form2: { title: "Cambian de significado", cols: ["Verbo", "+ -ing", "+ to"], rows: [["stop", "dejar de: I stopped smoking.", "detenerse para: I stopped to smoke."], ["remember", "recordar algo pasado: I remember meeting her.", "acordarse de hacer: Remember to call."], ["try", "probar: Try restarting it.", "intentar: I tried to open it."]] },
    uses: [["Hablar de gustos", "I love traveling. / I'd love to travel.", "Me encanta viajar. / Me encantaría viajar."], ["Correo profesional", "I look forward to hearing from you.", "Quedo atento a su respuesta."]],
    mistakes: [["I want that you come.", "I want you to come.", "want + persona + to."], ["I'm interested in learn.", "I'm interested in learning.", "Preposición + -ing."], ["for to get", "to get", "Propósito = to."], ["I enjoy to work.", "I enjoy working.", "enjoy + -ing."], ["I look forward to hear from you.", "I look forward to hearing from you.", "to aquí es preposición → -ing."]],
    spanish: "«Quiero que vengas» NO se traduce palabra por palabra: I want you to come. «Para + verbo» = to + verbo.",
    tips: ["Aprende cada verbo con su «pareja»: enjoy + ing, decide + to.", "Después de preposición SIEMPRE -ing."],
  },
  "g.phrasal-verbs": {
    intro: "Un phrasal verb es un verbo + partícula (up, out, off, on, in, over…) que crea un significado nuevo. Son esenciales para entender a los nativos.",
    form: { cols: ["Tipo", "Regla", "Ejemplo"], rows: [
      ["Intransitivo (sin objeto)", "verbo + partícula", "The car broke down. Prices went up."], ["Separable", "objeto en medio o al final", "Turn off the light. / Turn the light off."],
      ["Separable con pronombre", "pronombre SIEMPRE en medio", "Turn it off. (✗ Turn off it)"], ["Inseparable", "objeto después", "Look after the children. Deal with the problem."], ["Tres palabras", "verbo + 2 partículas", "run out of, look forward to, come up with"],
    ] },
    form2: { title: "Partículas y su idea general", cols: ["Partícula", "Idea", "Ejemplos"], rows: [["up", "aumentar / completar", "go up, fill up, set up, follow up"], ["down", "disminuir / detener", "cut down, break down, shut down"], ["out", "hacia fuera / descubrir / terminar", "find out, figure out, run out"], ["off", "cancelar / desconectar", "call off, turn off, take off"], ["on", "continuar / activar", "carry on, turn on, go on"], ["over", "revisar / pasar", "go over, take over"]] },
    uses: [["Trabajo diario", "I'll follow up on the invoice.", "Haré seguimiento de la factura."], ["Problemas", "We ran out of spare parts.", "Nos quedamos sin repuestos."]],
    mistakes: [["Turn off it.", "Turn it off.", "Pronombre en medio."], ["I look forward to see you.", "I look forward to seeing you.", "to + -ing aquí."]],
    spanish: "No existen en español: apréndelos como vocabulario, con un ejemplo cada uno.",
    tips: ["En textos formales puedes usar el verbo equivalente: call off → cancel, put off → postpone, find out → discover."],
  },
  "g.reported-speech": {
    intro: "Reported speech (estilo indirecto) cuenta lo que otra persona dijo. Normalmente los tiempos «retroceden» un paso.",
    form: { cols: ["Dijo (directo)", "Reportado (indirecto)"], rows: [
      ["\"I work here.\" (present simple)", "She said (that) she worked there."], ["\"I'm working.\" (present continuous)", "She said she was working."], ["\"I finished.\" (past simple)", "She said she had finished."],
      ["\"I've finished.\" (present perfect)", "She said she had finished."], ["\"I will call.\" (will)", "She said she would call."], ["\"I can help.\" (can)", "She said she could help."], ["\"I must go.\" (must)", "She said she had to go."],
    ] },
    form2: { title: "Cambios de tiempo y lugar", cols: ["Directo", "Indirecto"], rows: [["today", "that day"], ["tomorrow", "the next day / the following day"], ["yesterday", "the day before / the previous day"], ["here", "there"], ["now", "then"], ["this", "that"]] },
    uses: [["say vs tell", "He said (that) he was busy. / He told me (that) he was busy.", "say + lo dicho; tell + persona."], ["Preguntas sí/no → if / whether", "She asked if I was ready.", "Preguntó si estaba listo."], ["Preguntas wh- → orden normal", "He asked where I worked.", "Preguntó dónde trabajaba."], ["Órdenes → tell + to", "She told me to wait.", "Me dijo que esperara."]],
    mistakes: [["He said me…", "He told me… / He said to me…", "say no lleva persona directa."], ["She asked where did I work.", "She asked where I worked.", "Sin inversión en preguntas indirectas."]],
    spanish: "Igual que en español cambiamos «voy» → «dijo que iba». En inglés además las preguntas indirectas no llevan auxiliar.",
    tips: ["Si lo dicho sigue siendo verdad, a veces no se cambia el tiempo: He said the Earth is round."],
  },
  "g.third-conditional": {
    intro: "El tercer condicional habla de un pasado imaginario: algo que NO pasó y su consecuencia imaginada. Sirve para lamentos, críticas y lecciones aprendidas.",
    form: { cols: ["Condición", "Resultado"], rows: [["If + had + participio", "would have + participio"], ["If we had checked the valve,", "the leak wouldn't have happened."], ["If I had known,", "I would have called you."]] },
    uses: [["Lamentos", "If I had studied, I would have passed.", "Si hubiera estudiado, habría aprobado."], ["Lecciones aprendidas", "If we had followed the procedure, we would have avoided the incident.", "Si hubiéramos seguido el procedimiento, habríamos evitado el incidente."], ["could / might have", "If you had asked, I could have helped.", "Si hubieras preguntado, podría haberte ayudado."]],
    mistakes: [["If I would have known…", "If I had known…", "No would en la parte del if."], ["would have went", "would have gone", "Participio, no pasado."]],
    spanish: "«Si hubiera + participio, habría + participio».",
    tips: ["Pronunciación rápida: would have → «would've» /wʊdəv/."],
  },
  "g.wish": {
    intro: "Wish / If only expresan deseos sobre situaciones que no son como queremos. El verbo retrocede un tiempo.",
    form: { cols: ["Queremos cambiar…", "Estructura", "Ejemplo"], rows: [["el presente", "wish + past simple", "I wish I spoke French."], ["el pasado (lamento)", "wish + past perfect", "I wish I had studied more."], ["el comportamiento de otro", "wish + would", "I wish you would listen."], ["una habilidad", "wish + could", "I wish I could swim."]] },
    uses: [["Deseos", "I wish I had more time.", "Ojalá tuviera más tiempo."], ["If only (más enfático)", "If only I had known!", "¡Si tan solo lo hubiera sabido!"]],
    mistakes: [["I wish I have…", "I wish I had…", "Un tiempo hacia atrás."], ["I wish I would… (sobre mí)", "I wish I could…", "would se usa para otros."]],
    spanish: "«Ojalá + subjuntivo»: Ojalá tuviera = I wish I had.",
    tips: ["wish = siempre un paso atrás en el tiempo."],
  },
  "g.modals-deduction": {
    intro: "Los modales de deducción expresan cuán seguros estamos de algo según la evidencia.",
    form: { cols: ["Seguridad", "Presente", "Pasado"], rows: [["~100% sí", "must be", "must have been"], ["posible", "might / may / could be", "might / may / could have been"], ["~100% no", "can't / couldn't be", "can't / couldn't have been"]] },
    uses: [["Diagnóstico técnico", "There's oil on the floor. The seal must be damaged.", "Debe de estar dañado el sello."], ["Hipótesis", "It might be a software problem.", "Podría ser un problema de software."], ["Descartar", "It can't be the pump. We replaced it.", "No puede ser la bomba."]],
    mistakes: [["It mustn't be true. (deducción)", "It can't be true.", "Deducción negativa = can't."], ["He must have go.", "He must have gone.", "have + participio."]],
    spanish: "«Debe de ser» (deducción) = must be. «Puede que sea» = might be. «No puede ser» = can't be.",
    tips: ["Evidencia fuerte → must / can't. Duda → might / could."],
  },
  "g.linking": {
    intro: "Los conectores de contraste y adición organizan tus ideas en informes, correos y presentaciones.",
    form: { cols: ["Conector", "Estructura", "Ejemplo"], rows: [
      ["although / even though", "+ sujeto + verbo", "Although it was expensive, we bought it."], ["despite / in spite of", "+ sustantivo / -ing", "Despite the delay, we finished. / Despite being late…"],
      ["however", "nueva oración, con coma", "The design is safe. However, it's expensive."], ["whereas / while", "contraste entre dos hechos", "A is cheap, whereas B is durable."],
      ["moreover / furthermore / in addition", "añadir (formal)", "In addition, the supplier offers training."], ["therefore / as a result", "consecuencia (formal)", "Costs rose. Therefore, we changed supplier."],
    ] },
    uses: [["Recomendaciones equilibradas", "Although option B costs more, it reduces risk. Therefore, we recommend it.", "Aunque la opción B cuesta más, reduce el riesgo."]],
    mistakes: [["Despite it was late…", "Although it was late… / Despite the late hour…", "despite no va con oración."], ["However the cost is high, …", "Although the cost is high, …", "however no une dos oraciones así."]],
    spanish: "«Aunque» = although (+ oración). «A pesar de» = despite (+ sustantivo). «Sin embargo» = however.",
    tips: ["despite + the fact that + oración es posible: Despite the fact that it rained…"],
  },
  "g.causative": {
    intro: "El causativo indica que otra persona hace algo por nosotros (normalmente un servicio).",
    form: { cols: ["Estructura", "Ejemplo"], rows: [["have + objeto + participio", "I had my car repaired."], ["get + objeto + participio (informal)", "We got the pump serviced."], ["have + persona + verbo base", "I'll have the technician check it."], ["get + persona + to + verbo", "I got him to sign the form."]] },
    uses: [["Servicios", "I need to have my eyes tested.", "Necesito hacerme un examen de la vista."], ["Delegar en el trabajo", "We'll have the equipment calibrated.", "Haremos calibrar el equipo."]],
    mistakes: [["I cut my hair (en la peluquería).", "I had my hair cut.", "Otro lo hizo por ti."], ["I had repaired my car.", "I had my car repaired.", "El objeto va antes del participio."]],
    spanish: "«Mandar a hacer / hacerse»: Me corté el pelo (en la peluquería) = I had my hair cut.",
    tips: ["Orden: HAVE + COSA + PARTICIPIO."],
  },
  "g.inversion": {
    intro: "La inversión (auxiliar antes del sujeto) después de expresiones negativas da énfasis en inglés formal, discursos y textos escritos.",
    form: { cols: ["Expresión", "Estructura", "Ejemplo"], rows: [
      ["Never / Rarely / Seldom", "+ auxiliar + sujeto", "Never have I seen such results."], ["Not only … but also", "Not only + aux + sujeto…", "Not only did they finish early, but they also cut costs."],
      ["No sooner … than", "No sooner had + sujeto + pp … than", "No sooner had we started than it rained."], ["Hardly … when", "Hardly had + sujeto + pp … when", "Hardly had I arrived when the phone rang."],
      ["Only then / Only after", "+ aux + sujeto", "Only then did we understand the problem."], ["Under no circumstances", "+ aux + sujeto", "Under no circumstances should you open it."],
      ["Condicional formal", "Should / Had / Were + sujeto", "Should you need help, call us. Had I known, I'd have come."],
    ] },
    uses: [["Correos formales", "Should you have any questions, please contact us.", "Si tiene alguna pregunta, contáctenos."]],
    mistakes: [["Never I have seen…", "Never have I seen…", "Invierte auxiliar y sujeto."], ["Not only they finished…", "Not only did they finish…", "Necesita auxiliar do/did."]],
    spanish: "No hay equivalente directo: en español el orden es libre. En inglés la inversión es una señal de estilo formal.",
    tips: ["Úsala con moderación: una por párrafo como máximo."],
  },
  "g.mixed-conditionals": {
    intro: "Los condicionales mixtos combinan tiempos distintos en cada mitad, y existen alternativas a «if» para expresar condiciones con precisión.",
    form: { cols: ["Tipo", "Estructura", "Ejemplo"], rows: [["Pasado → presente", "If + had + pp, would + verbo", "If I had taken that job, I would be in Canada now."], ["Presente → pasado", "If + past simple, would have + pp", "If she weren't so talented, she wouldn't have been promoted."]] },
    form2: { title: "Alternativas a if", cols: ["Expresión", "Significado", "Ejemplo"], rows: [["provided (that) / providing", "siempre que", "Provided that the budget is approved, we'll start."], ["as long as", "mientras", "As long as the tests pass, we release it."], ["on condition that", "con la condición de que", "We'll sign on condition that…"], ["unless", "a menos que", "Unless we act now, costs will rise."], ["but for / if it weren't for", "de no ser por", "But for your help, we'd have failed."], ["otherwise", "si no", "Hurry, otherwise we'll miss it."], ["supposing / what if", "suponiendo que", "Supposing the supplier refuses, what then?"]] },
    uses: [["Reflexión profesional", "If we had invested earlier, we would be leaders now.", "Si hubiéramos invertido antes, hoy seríamos líderes."]],
    mistakes: [["If I would have…", "If I had…", "Nunca would en la parte del if."]],
    spanish: "También en español mezclamos: «Si hubiera aceptado, ahora estaría en Canadá».",
    tips: ["Decide el tiempo de cada mitad por separado."],
  },
  "g.cleft": {
    intro: "Las oraciones escindidas (cleft sentences) dividen la frase para destacar una parte. Son muy naturales al aclarar o corregir.",
    form: { cols: ["Tipo", "Estructura", "Ejemplo"], rows: [["It-cleft", "It is/was + X + who/that…", "It was Maria who found the error."], ["Wh-cleft", "What + oración + is/was + X", "What we need is more time."], ["All-cleft", "All (that) + oración + is…", "All I want is an answer."], ["Reversed", "X + is what…", "Time is what we need."]] },
    uses: [["Corregir", "It wasn't the pump that failed; it was the valve.", "No fue la bomba la que falló; fue la válvula."], ["Enfatizar en presentaciones", "What I'd like to highlight is the cost saving.", "Lo que quiero destacar es el ahorro."]],
    mistakes: [["What we need it is time.", "What we need is time.", "No repitas it."]],
    spanish: "Igual que «Lo que necesitamos es…» / «Fue María quien…».",
    tips: ["What I mean is… / The thing is… son muy útiles al hablar."],
  },
  "g.participle-clauses": {
    intro: "Las oraciones de participio acortan y unen frases con el mismo sujeto. Dan un estilo conciso, típico de informes.",
    form: { cols: ["Forma", "Significado", "Ejemplo"], rows: [["-ing (presente)", "al mismo tiempo / causa (activa)", "Working late, she finished the report."], ["Having + pp", "acción anterior", "Having reviewed the data, we recommend B."], ["participio (pasado)", "significado pasivo", "Built in 1990, the plant needs updating."]] },
    uses: [["Informes", "Located near the port, the warehouse is easy to reach.", "Ubicado cerca del puerto, el almacén es accesible."], ["Reducir relativas", "The man sitting there is my boss (= who is sitting).", "El hombre sentado allí es mi jefe."]],
    mistakes: [["Walking to work, the rain started. (¿quién caminaba?)", "Walking to work, I got caught in the rain.", "El sujeto debe ser el mismo (dangling participle)."]],
    spanish: "Parecido a «Tras revisar…», «Construida en…», «Trabajando…».",
    tips: ["Comprueba siempre que el sujeto de ambas partes sea el mismo."],
  },
  "g.academic": {
    intro: "El inglés académico y técnico «matiza» (hedging): evita afirmaciones absolutas cuando la evidencia no es total, y prefiere estructuras impersonales.",
    form: { cols: ["Recurso", "Ejemplos"], rows: [["Verbos", "appear to, seem to, tend to, suggest, indicate"], ["Modales", "may, might, could"], ["Adverbios", "arguably, possibly, largely, relatively, to some extent"], ["Impersonal", "It could be argued that… / It is widely accepted that…"], ["Nominalización", "analyse → the analysis of; implement → the implementation of"]] },
    uses: [["Conclusiones prudentes", "The results suggest that the new process may reduce costs.", "Los resultados sugieren que el nuevo proceso podría reducir costes."]],
    mistakes: [["This proves the design is wrong.", "This suggests the design may be flawed.", "Evita exagerar con evidencia limitada."]],
    spanish: "Similar a «parece indicar», «podría argumentarse».",
    tips: ["Usa hedging para opiniones; no para hechos comprobados."],
  },
  "g.advanced-writing": {
    intro: "Estructuras avanzadas para escritura formal: nominalización, énfasis con such/so y construcciones hipotéticas formales.",
    form: { cols: ["Estructura", "Ejemplo"], rows: [["Nominalización", "The introduction of the policy led to…"], ["Such + be + sustantivo + that", "Such was the demand that production doubled."], ["So + adj + be + sujeto + that", "So significant was the impact that…"], ["Were + sujeto + to", "Were the proposal to be accepted, costs would fall."], ["Fronting", "Of particular concern is the lack of data."]] },
    uses: [["Resúmenes ejecutivos", "The implementation of the new system resulted in a 20% reduction in downtime.", "La implementación produjo una reducción del 20 %."]],
    mistakes: [["So was the impact that…", "Such was the impact that… / So great was the impact that…", "such + sustantivo; so + adjetivo."]],
    spanish: "El español formal también nominaliza («la implementación de»), pero el inglés valora más la concisión.",
    tips: ["Alterna frases largas y cortas para mantener la claridad."],
  },
  "g.subjunctive": {
    intro: "El subjuntivo formal en inglés usa el verbo base (sin -s) después de verbos o adjetivos de recomendación, exigencia o necesidad.",
    form: { cols: ["Disparador", "Estructura", "Ejemplo"], rows: [["recommend, suggest, insist, demand, request, propose", "that + sujeto + verbo base", "We recommend that he attend the meeting."], ["essential, vital, important, necessary", "It is … that + sujeto + verbo base", "It is essential that she be informed."], ["Negativo", "that + sujeto + not + verbo base", "We suggest that he not sign yet."]] },
    uses: [["Documentos legales y corporativos", "The board requires that all directors disclose conflicts of interest.", "La junta exige que los directores declaren conflictos."]],
    mistakes: [["We recommend that he attends.", "We recommend that he attend.", "Forma base (en inglés formal americano)."]],
    spanish: "Equivale al subjuntivo español: «recomendamos que asista».",
    tips: ["En británico también: We recommend that he should attend."],
  },
};
