// Explicaciones profundas A1–A2 (apuntes de estudio). Se muestran por secciones:
// intro · form (tabla) · form2 · uses · spelling · signals · mistakes · spanish · tips
export default {
  "g.be": {
    intro: "«To be» es el verbo más importante del inglés. En español tenemos dos verbos (ser y estar); en inglés hay uno solo con tres formas: am, is, are. Lo usas para decir quién eres, cómo estás, de dónde eres, tu edad y dónde está algo.",
    form: { cols: ["Persona", "Afirmativo ✅", "Negativo ❌", "Pregunta ❓"], rows: [
      ["I (yo)", "I am → I'm", "I am not → I'm not", "Am I…?"],
      ["You (tú / usted / ustedes)", "You are → You're", "You are not → You aren't", "Are you…?"],
      ["He (él)", "He is → He's", "He is not → He isn't", "Is he…?"],
      ["She (ella)", "She is → She's", "She is not → She isn't", "Is she…?"],
      ["It (cosa / animal)", "It is → It's", "It is not → It isn't", "Is it…?"],
      ["We (nosotros)", "We are → We're", "We are not → We aren't", "Are we…?"],
      ["They (ellos / ellas)", "They are → They're", "They are not → They aren't", "Are they…?"],
    ] },
    form2: { title: "Respuestas cortas", cols: ["Pregunta", "Sí", "No"], rows: [
      ["Are you a student?", "Yes, I am.", "No, I'm not."], ["Is she from Peru?", "Yes, she is.", "No, she isn't."], ["Are they ready?", "Yes, they are.", "No, they aren't."],
    ] },
    uses: [
      ["Nombre e identidad", "I'm Carlos. / This is Ana.", "Soy Carlos. / Ella es Ana."],
      ["Profesión (¡con a/an!)", "She's a doctor. / I'm an engineer.", "Es doctora. / Soy ingeniero."],
      ["Origen y nacionalidad", "We're from Ecuador. We're Ecuadorian.", "Somos de Ecuador. Somos ecuatorianos."],
      ["Edad", "I'm 30 (years old).", "Tengo 30 años."],
      ["Estados y sentimientos", "I'm tired. / Are you OK?", "Estoy cansado. / ¿Estás bien?"],
      ["Lugar", "The keys are on the table.", "Las llaves están en la mesa."],
      ["Descripción", "The office is big and modern.", "La oficina es grande y moderna."],
      ["Tiempo (clima y hora)", "It's cold. / It's 3 o'clock.", "Hace frío. / Son las 3."],
    ],
    signals: ["Con adjetivos: happy, tired, big, cold…", "Con lugares: at home, in Quito, on the table", "Con edades: 25 years old"],
    mistakes: [
      ["I have 25 years.", "I am 25 (years old).", "La edad se dice con be, no con have."],
      ["I have hungry / cold.", "I am hungry / cold.", "Hambre, frío, calor, miedo → be + adjetivo."],
      ["Is very good.", "It is very good.", "En inglés siempre hay sujeto: it."],
      ["She engineer.", "She is an engineer.", "No olvides el verbo be ni el artículo a/an."],
      ["Are you agree?", "Do you agree?", "Agree es un verbo normal: no va con be."],
    ],
    spanish: "En español podemos omitir el sujeto («Es tarde») y usamos «tener» para la edad y las sensaciones. En inglés: siempre sujeto (It's late) y «be» para edad y sensaciones (I'm hungry).",
    tips: ["Piensa en una canción: I am, you are, he is, she is, it is, we are, they are.", "En conversación usa contracciones: I'm, you're, he's. Suena más natural.", "Para preguntar, solo cambia el orden: You are → Are you?"],
  },
  "g.pronouns": {
    intro: "Los pronombres reemplazan a los nombres para no repetirlos. En inglés hay pronombres sujeto (antes del verbo) y pronombres objeto (después del verbo o de una preposición).",
    form: { cols: ["Sujeto (hace la acción)", "Objeto (recibe la acción)", "Español"], rows: [
      ["I", "me", "yo / me, mí"], ["you", "you", "tú, usted / te, ti"], ["he", "him", "él / lo, le"], ["she", "her", "ella / la, le"],
      ["it", "it", "(cosa) / lo, la"], ["we", "us", "nosotros / nos"], ["they", "them", "ellos, ellas / los, las, les"],
    ] },
    uses: [
      ["Sujeto: antes del verbo", "She works here. They live in Lima.", "Ella trabaja aquí. Ellos viven en Lima."],
      ["Objeto: después del verbo", "I know him. Call me.", "Lo conozco. Llámame."],
      ["Objeto: después de preposición", "This is for you. Come with us.", "Esto es para ti. Ven con nosotros."],
      ["It para cosas y animales", "The pump is new. It works well.", "La bomba es nueva. Funciona bien."],
      ["They para personas o cosas en plural", "The reports? They're on your desk.", "¿Los informes? Están en tu escritorio."],
    ],
    mistakes: [
      ["Me and Ana are friends.", "Ana and I are friends.", "Como sujeto se usa I (y por cortesía va al final)."],
      ["Is raining.", "It is raining.", "El clima necesita el sujeto it."],
      ["Explain me.", "Explain it to me.", "Explain + cosa + to + persona."],
      ["i work here.", "I work here.", "I siempre con mayúscula."],
    ],
    spanish: "En español el sujeto suele omitirse porque el verbo lo indica (trabajo = yo trabajo). En inglés el verbo casi no cambia, por eso el sujeto es OBLIGATORIO: I work, she works.",
    tips: ["Si puedes decir «yo/él/ella» antes del verbo → sujeto (I, he, she).", "Si en español es «me, te, lo, la, nos, les» → objeto (me, you, him, her, us, them)."],
  },
  "g.articles": {
    intro: "Los artículos son palabras pequeñas antes del sustantivo. A / an = un, una. The = el, la, los, las. A veces en inglés no se usa ningún artículo.",
    form: { cols: ["Artículo", "Cuándo", "Ejemplo"], rows: [
      ["a", "Singular, algo no específico, antes de SONIDO consonante", "a car, a report, a university (/ju/)"],
      ["an", "Singular, algo no específico, antes de SONIDO vocal", "an apple, an engineer, an hour (h muda)"],
      ["the", "Algo específico, conocido o ya mencionado (singular o plural)", "the car in the garage, the sun"],
      ["— (nada)", "Plurales o incontables en sentido general", "I like coffee. Engineers solve problems."],
    ] },
    uses: [
      ["Mencionar algo por primera vez", "I have a meeting. The meeting is at 10.", "Tengo una reunión. La reunión es a las 10."],
      ["Profesiones", "He's a mechanic. I'm an auditor.", "Es mecánico. Soy auditor."],
      ["Cosas únicas", "the sun, the internet, the president", "el sol, internet, el presidente"],
      ["Instrumentos musicales y lugares conocidos", "She plays the guitar. I'm going to the bank.", "Toca la guitarra. Voy al banco."],
      ["Generalizaciones: SIN artículo", "Life is beautiful. Dogs are loyal.", "La vida es bella. Los perros son leales."],
      ["Comidas, idiomas, deportes: SIN artículo", "I have lunch at one. I speak English. I play soccer.", "Almuerzo a la una. Hablo inglés. Juego fútbol."],
    ],
    spelling: ["Lo importante es el SONIDO, no la letra: a uniform (/ju/), an hour (/aʊ/), an MBA (/em/).", "a + adjetivo + sustantivo: a big house, an old house."],
    mistakes: [
      ["I am engineer.", "I am an engineer.", "Las profesiones en singular llevan a/an."],
      ["The life is hard.", "Life is hard.", "En general, sin the."],
      ["I like the music.", "I like music.", "Gustos generales, sin the."],
      ["a apple / an car", "an apple / a car", "an antes de sonido vocal; a antes de consonante."],
      ["I play the soccer.", "I play soccer.", "Deportes sin artículo."],
    ],
    spanish: "El español usa mucho el artículo en general («La vida es bella», «Me gusta el café»). El inglés no: «Life is beautiful», «I like coffee». Y al revés: el inglés usa a/an con profesiones y el español no.",
    tips: ["Pregúntate: ¿hablo de TODOS en general? → sin artículo. ¿De uno específico? → the. ¿De uno cualquiera? → a/an.", "Di la palabra en voz alta: si empieza con sonido vocal, usa an."],
  },
  "g.plurals": {
    intro: "Para decir más de uno, casi siempre añadimos -s. Pero hay reglas de ortografía y algunas palabras irregulares que hay que memorizar.",
    form: { cols: ["Regla", "Singular → Plural"], rows: [
      ["La mayoría: + s", "book → books, valve → valves"],
      ["Terminan en s, ss, sh, ch, x, z: + es", "bus → buses, class → classes, box → boxes, watch → watches"],
      ["Consonante + y → ies", "company → companies, city → cities"],
      ["Vocal + y → + s", "day → days, key → keys"],
      ["Terminan en f / fe → ves (muchas)", "knife → knives, life → lives, shelf → shelves"],
      ["Algunas en o → oes", "potato → potatoes, tomato → tomatoes (pero photo → photos)"],
      ["Irregulares", "man → men, woman → women, child → children, person → people, foot → feet, tooth → teeth, mouse → mice"],
      ["Iguales en singular y plural", "fish, sheep, series, species"],
    ] },
    form2: { title: "Pronunciación de la -s final", cols: ["Sonido", "Cuándo", "Ejemplos"], rows: [
      ["/s/", "después de sonidos sordos p, t, k, f", "books, cats, maps"], ["/z/", "después de sonidos sonoros y vocales", "dogs, days, valves"], ["/ɪz/", "después de s, sh, ch, x, z, ge", "boxes, buses, pages"],
    ] },
    uses: [
      ["Contables: se pueden contar", "two pumps, three employees", "dos bombas, tres empleados"],
      ["Incontables: sin plural", "information, advice, equipment, money, water, furniture", "información, consejos, equipo, dinero, agua, muebles"],
      ["Para contar incontables", "a piece of advice, two pieces of equipment, a glass of water", "un consejo, dos equipos, un vaso de agua"],
    ],
    mistakes: [
      ["informations, advices, equipments", "information, advice, equipment", "Son incontables en inglés."],
      ["The people is nice.", "The people are nice.", "People es plural."],
      ["childs, mans, persons*", "children, men, people", "Plurales irregulares (*persons existe en textos legales)."],
      ["two car", "two cars", "Después de un número mayor que uno, plural."],
    ],
    spanish: "Algunas palabras son plurales en español y singulares en inglés (o al revés): «los consejos» = advice (incontable), «la gente» = people (plural).",
    tips: ["Haz una lista de irregulares: men, women, children, people, feet, teeth.", "Recuerda los incontables del trabajo: information, equipment, feedback, advice, software, research."],
  },
  "g.possessives": {
    intro: "Los posesivos indican de quién es algo. En inglés el posesivo depende del DUEÑO, no de la cosa: «his car» (el auto de él), «her car» (el auto de ella).",
    form: { cols: ["Persona", "Adjetivo posesivo (+ sustantivo)", "Pronombre posesivo (solo)"], rows: [
      ["I", "my book", "mine"], ["you", "your book", "yours"], ["he", "his book", "his"], ["she", "her book", "hers"],
      ["it", "its color", "—"], ["we", "our book", "ours"], ["they", "their book", "theirs"],
    ] },
    form2: { title: "El genitivo 's (de alguien)", cols: ["Caso", "Forma", "Ejemplo"], rows: [
      ["Una persona", "nombre + 's", "Ana's car = el auto de Ana"], ["Plural con s", "+ ' (solo apóstrofo)", "the managers' office"], ["Plural irregular", "+ 's", "the children's toys"], ["Cosas (normalmente)", "the … of …", "the end of the meeting"],
    ] },
    uses: [
      ["Adjetivo posesivo antes del sustantivo", "This is my sister. Their office is big.", "Esta es mi hermana. Su oficina es grande."],
      ["Pronombre posesivo sin sustantivo", "Is this pen yours? — Yes, it's mine.", "¿Es tuyo este bolígrafo? — Sí, es mío."],
      ["Whose? = ¿de quién?", "Whose laptop is this? — It's Pedro's.", "¿De quién es esta laptop? — Es de Pedro."],
    ],
    mistakes: [
      ["Ana is with his husband.", "Ana is with her husband.", "El posesivo depende de la dueña (Ana → her)."],
      ["The car of my boss.", "My boss's car.", "Con personas usamos 's."],
      ["The company changed it's logo.", "The company changed its logo.", "its = su (posesivo); it's = it is."],
      ["This book is my.", "This book is mine.", "Sin sustantivo después → mine."],
    ],
    spanish: "En español «su» sirve para él, ella, ellos y usted. En inglés hay que elegir: his (de él), her (de ella), their (de ellos), your (de usted).",
    tips: ["Pregunta: ¿de quién es? Si es de un hombre → his; de una mujer → her; de varios → their.", "it's con apóstrofo = it is. Si puedes decir «it is», lleva apóstrofo."],
  },
  "g.there-is": {
    intro: "«There is / There are» significa «hay». Se usa para decir que algo existe o está en un lugar.",
    form: { cols: ["", "Singular / incontable", "Plural"], rows: [
      ["✅ Afirmativo", "There is (There's) a bank.", "There are two banks."],
      ["❌ Negativo", "There isn't a bank. / There's no bank.", "There aren't any banks."],
      ["❓ Pregunta", "Is there a bank?", "Are there any banks?"],
      ["Respuestas cortas", "Yes, there is. / No, there isn't.", "Yes, there are. / No, there aren't."],
      ["Pasado", "There was a problem.", "There were three problems."],
    ] },
    uses: [
      ["Describir un lugar", "There's a pool and there are two restaurants.", "Hay una piscina y hay dos restaurantes."],
      ["Preguntar si existe algo", "Is there a pharmacy near here?", "¿Hay una farmacia cerca?"],
      ["Con incontables", "There is some water on the floor.", "Hay agua en el piso."],
      ["¿Cuántos hay?", "How many people are there?", "¿Cuántas personas hay?"],
    ],
    signals: ["some (afirmativas)", "any (negativas y preguntas)", "a lot of, many, much", "How many…are there?"],
    mistakes: [
      ["It has a pool.", "There is a pool.", "«Hay» no es «it has»."],
      ["There is two rooms.", "There are two rooms.", "Plural → are."],
      ["Have a problem?", "Is there a problem?", "Para «¿hay…?» usa Is there / Are there."],
    ],
    spanish: "En español «hay» nunca cambia (hay una, hay dos). En inglés cambia según lo que viene después: there IS (uno), there ARE (varios).",
    tips: ["Mira lo que viene después: si es singular → is; si es plural → are.", "En pasado: there was / there were."],
  },
  "g.have-has": {
    intro: "«Have» significa tener. Con he, she, it cambia a «has». Para negar y preguntar usamos do / does.",
    form: { cols: ["", "I / you / we / they", "he / she / it"], rows: [
      ["✅ Afirmativo", "I have a car.", "She has a car."],
      ["❌ Negativo", "I don't have a car.", "She doesn't have a car."],
      ["❓ Pregunta", "Do you have a car?", "Does she have a car?"],
      ["Respuesta corta", "Yes, I do. / No, I don't.", "Yes, she does. / No, she doesn't."],
    ] },
    uses: [
      ["Posesión", "I have two phones.", "Tengo dos teléfonos."],
      ["Familia y relaciones", "She has three brothers.", "Tiene tres hermanos."],
      ["Características", "The room has a balcony.", "La habitación tiene balcón."],
      ["Citas y eventos", "We have a meeting at nine.", "Tenemos una reunión a las nueve."],
      ["Comidas (have = tomar/comer)", "I have breakfast at seven.", "Desayuno a las siete."],
      ["Enfermedades", "I have a headache.", "Tengo dolor de cabeza."],
    ],
    mistakes: [
      ["She doesn't has.", "She doesn't have.", "Después de does/doesn't, verbo base (have)."],
      ["Does she has…?", "Does she have…?", "Igual: does + have."],
      ["I have 20 years / I have hungry.", "I'm 20. / I'm hungry.", "Edad y sensaciones con be."],
      ["He have a car.", "He has a car.", "he / she / it → has."],
    ],
    spanish: "«Tener» en español se usa para edad, hambre, frío, miedo, razón… En inglés estas expresiones usan be: I'm 20, I'm hungry, I'm cold, I'm afraid, you're right.",
    tips: ["has = have + s de he/she/it.", "British English también dice «have got»: I've got a car."],
  },
  "g.present-simple": {
    intro: "El Presente Simple sirve para rutinas, hábitos, horarios y verdades generales. Es el tiempo más usado en inglés. Lo más importante: con he, she, it el verbo lleva -s.",
    form: { cols: ["", "I / you / we / they", "he / she / it"], rows: [
      ["✅ Afirmativo", "I work.", "She works."],
      ["❌ Negativo", "I don't (do not) work.", "She doesn't (does not) work."],
      ["❓ Pregunta", "Do you work?", "Does she work?"],
      ["Respuesta corta", "Yes, I do. / No, I don't.", "Yes, she does. / No, she doesn't."],
      ["Pregunta con Wh-", "Where do you work?", "Where does she work?"],
    ] },
    spelling: ["La mayoría: + s → works, plays, lives", "Terminan en s, sh, ch, x, o: + es → watches, finishes, goes, does", "Consonante + y → ies → study → studies, carry → carries", "Vocal + y → + s → play → plays", "Irregular: have → has"],
    uses: [
      ["Rutinas y hábitos", "I get up at six every day.", "Me levanto a las seis todos los días."],
      ["Hechos y verdades generales", "Water boils at 100 °C.", "El agua hierve a 100 °C."],
      ["Situaciones permanentes", "She lives in Guayaquil. He works for a bank.", "Vive en Guayaquil. Trabaja para un banco."],
      ["Horarios y programas", "The train leaves at 8:15. The store opens at nine.", "El tren sale a las 8:15. La tienda abre a las nueve."],
      ["Gustos y opiniones", "I like tea. I think it's a good idea.", "Me gusta el té. Creo que es buena idea."],
      ["Instrucciones y procesos", "You open the valve and check the pressure.", "Abres la válvula y revisas la presión."],
    ],
    signals: ["always (siempre)", "usually (normalmente)", "often (a menudo)", "sometimes (a veces)", "rarely (rara vez)", "never (nunca)", "every day / week", "on Mondays", "twice a week"],
    form2: { title: "Posición de los adverbios de frecuencia", cols: ["Regla", "Ejemplo"], rows: [
      ["ANTES del verbo principal", "I always check the pressure."], ["DESPUÉS de be", "She is never late."], ["Expresiones largas al final", "I go to the gym three times a week."],
    ] },
    mistakes: [
      ["He go to work.", "He goes to work.", "he / she / it → verbo + s."],
      ["She don't like coffee.", "She doesn't like coffee.", "he / she / it → doesn't."],
      ["Does he works?", "Does he work?", "Con does, el verbo NO lleva -s."],
      ["Always I check.", "I always check.", "El adverbio va antes del verbo."],
      ["Do you can…?", "Can you…?", "Can no usa do."],
    ],
    spanish: "En español cada persona tiene su terminación (trabajo, trabajas, trabaja). En inglés solo cambia la 3.ª persona singular: work → works. Por eso es fácil olvidarla: ¡vigila la -s!",
    tips: ["Truco: «He, She, It: la S se lleva la S».", "Si hay does/doesn't en la frase, la -s ya está en does: no la repitas en el verbo.", "Present Simple = cosas que pasan SIEMPRE o NORMALMENTE, no ahora mismo."],
  },
  "g.present-continuous": {
    intro: "El Presente Continuo describe acciones que ocurren ahora mismo o en este período, y planes futuros ya organizados. Se forma con be + verbo terminado en -ing.",
    form: { cols: ["", "Forma", "Ejemplo"], rows: [
      ["✅ Afirmativo", "am / is / are + verb-ing", "I'm working. She's studying. They're waiting."],
      ["❌ Negativo", "am not / isn't / aren't + verb-ing", "He isn't listening."],
      ["❓ Pregunta", "Am / Is / Are + sujeto + verb-ing?", "Are you coming?"],
      ["Respuesta corta", "Yes, I am. / No, she isn't.", ""],
    ] },
    spelling: ["La mayoría: + ing → work → working", "Terminan en -e: quitar la e → write → writing, make → making", "Consonante-vocal-consonante (sílaba fuerte): doblar → run → running, stop → stopping, begin → beginning", "Terminan en -ie → ying → lie → lying, die → dying"],
    uses: [
      ["Acción en este momento", "Look! It's raining.", "¡Mira! Está lloviendo."],
      ["Situación temporal (estos días)", "I'm working from home this week.", "Esta semana trabajo desde casa."],
      ["Cambios en progreso", "Prices are going up.", "Los precios están subiendo."],
      ["Planes futuros organizados", "We're meeting the client on Friday.", "Nos reunimos con el cliente el viernes."],
      ["Quejas con always", "He's always arriving late!", "¡Siempre llega tarde!"],
    ],
    signals: ["now", "right now", "at the moment", "today", "this week / month", "Look! / Listen!", "currently"],
    form2: { title: "Verbos de estado (normalmente SIN -ing)", cols: ["Tipo", "Verbos"], rows: [
      ["Mente", "know, understand, believe, remember, think (= opinar)"], ["Gustos", "like, love, hate, prefer, want, need"], ["Posesión", "have (= poseer), own, belong"], ["Sentidos", "see, hear, smell, taste"],
    ] },
    mistakes: [
      ["I working now.", "I'm working now.", "Falta el verbo be."],
      ["I'm knowing the answer.", "I know the answer.", "know es verbo de estado."],
      ["She is work.", "She is working.", "Falta el -ing."],
      ["I am study English every day.", "I study English every day.", "Rutinas → Present Simple."],
    ],
    spanish: "Corresponde a «estar + -ando / -iendo» (estoy trabajando). Pero en inglés también se usa para planes («Nos vemos mañana» → We're meeting tomorrow).",
    tips: ["Present Simple = siempre / normalmente. Present Continuous = ahora / estos días.", "Si puedes decir «en este momento», probablemente es continuo."],
  },
  "g.prepositions": {
    intro: "In, on y at son las preposiciones más comunes para tiempo y lugar. En español usamos «en» para casi todo; en inglés hay que elegir según la «precisión».",
    form: { cols: ["", "⏰ TIEMPO", "📍 LUGAR"], rows: [
      ["AT (punto exacto)", "at 5 o'clock, at noon, at night, at the weekend (UK), at Christmas", "at the airport, at work, at home, at the door, at the bus stop"],
      ["ON (día / superficie)", "on Monday, on 3 May, on my birthday, on the weekend (US)", "on the table, on the wall, on the second floor, on the bus"],
      ["IN (período / dentro)", "in July, in 2025, in summer, in the morning, in two weeks", "in the box, in the room, in Quito, in Ecuador, in the car"],
    ] },
    form2: { title: "Otras preposiciones de lugar", cols: ["Preposición", "Significado", "Ejemplo"], rows: [
      ["next to", "al lado de", "The bank is next to the pharmacy."], ["between", "entre (dos)", "It's between the bank and the school."], ["opposite", "enfrente de", "The hotel is opposite the station."],
      ["under", "debajo de", "The cat is under the table."], ["behind", "detrás de", "The car is behind the house."], ["in front of", "delante de", "Wait in front of the gate."],
    ] },
    uses: [
      ["Fechas completas → on", "The audit is on 12 March.", "La auditoría es el 12 de marzo."],
      ["Partes del día → in the…", "in the morning / afternoon / evening", "por la mañana / tarde / noche"],
      ["Excepción: at night", "I sleep at night.", "Duermo de noche."],
      ["Sin preposición", "next week, last year, this morning, every day, tomorrow", "la próxima semana, el año pasado…"],
      ["Llegar", "arrive at the airport / arrive in London", "llegar al aeropuerto / a Londres"],
    ],
    mistakes: [
      ["in Monday", "on Monday", "Días → on."],
      ["at the morning", "in the morning", "Partes del día → in the."],
      ["in the night", "at night", "Expresión fija."],
      ["arrive to", "arrive at / in", "Arrive nunca va con to."],
      ["on next week", "next week", "Sin preposición con next / last / this."],
      ["depend of", "depend on", "Verbo + preposición fija."],
    ],
    spanish: "«En» se traduce de tres formas: at (punto), on (superficie o día), in (dentro o período). Piensa en una pirámide: IN (grande) → ON (medio) → AT (pequeño y exacto).",
    tips: ["Pirámide: IN = años, meses, ciudades (grande). ON = días, calles, superficies. AT = horas, direcciones exactas, puntos.", "Aprende en bloques: at work, at home, at school, in bed, on the bus."],
  },
  "g.can": {
    intro: "«Can» expresa habilidad (saber hacer), posibilidad, permiso y peticiones. Es un verbo modal: es igual para todas las personas y va seguido del verbo base.",
    form: { cols: ["", "Forma", "Ejemplo"], rows: [
      ["✅ Afirmativo", "sujeto + can + verbo base", "She can drive."], ["❌ Negativo", "can't / cannot + verbo base", "I can't swim."], ["❓ Pregunta", "Can + sujeto + verbo base?", "Can you help me?"], ["Respuesta corta", "Yes, I can. / No, I can't.", ""], ["Pasado", "could / couldn't", "I couldn't sleep last night."],
    ] },
    uses: [
      ["Habilidad", "I can speak two languages.", "Hablo dos idiomas / sé hablar…"], ["Posibilidad", "You can pay by card.", "Puede pagar con tarjeta."],
      ["Pedir permiso", "Can I open the window?", "¿Puedo abrir la ventana?"], ["Pedir algo", "Can you send me the file?", "¿Me puedes enviar el archivo?"],
      ["Más cortés: could", "Could you repeat that, please?", "¿Podría repetirlo, por favor?"], ["Prohibición", "You can't park here.", "No puede estacionar aquí."],
    ],
    mistakes: [
      ["She cans swim.", "She can swim.", "Los modales no llevan -s."], ["I can to go.", "I can go.", "Sin to después de can."], ["Do you can…?", "Can you…?", "Can no usa do."], ["He can speaks.", "He can speak.", "Verbo base después de can."],
    ],
    spanish: "«Saber» + verbo (sé nadar) se traduce con can (I can swim), no con know.",
    tips: ["can = poder / saber hacer. could = podía / podría.", "Pronunciación: can /kən/ (débil) en frases afirmativas; can't /kænt/ siempre fuerte."],
  },
  "g.questions": {
    intro: "Para hacer preguntas en inglés necesitas: palabra interrogativa + auxiliar + sujeto + verbo. El auxiliar puede ser be, do/does/did, can, will, have…",
    form: { cols: ["Palabra", "Significado", "Ejemplo"], rows: [
      ["What", "qué / cuál", "What's your name?"], ["Where", "dónde", "Where do you live?"], ["When", "cuándo", "When does the meeting start?"], ["Who", "quién", "Who is your manager?"],
      ["Why", "por qué", "Why are you late?"], ["How", "cómo", "How do you spell it?"], ["Which", "cuál (entre opciones)", "Which gate is it?"], ["Whose", "de quién", "Whose bag is this?"],
      ["How much", "cuánto (incontable / precio)", "How much is it?"], ["How many", "cuántos (contable)", "How many people work here?"], ["How long", "cuánto tiempo", "How long is the flight?"], ["How old", "qué edad", "How old are you?"], ["How often", "con qué frecuencia", "How often do you travel?"],
    ] },
    form2: { title: "Orden de la pregunta", cols: ["Wh-", "Auxiliar", "Sujeto", "Verbo", "Resto"], rows: [
      ["Where", "do", "you", "work", "?"], ["What", "does", "she", "need", "?"], ["When", "did", "they", "arrive", "?"], ["Why", "are", "you", "laughing", "?"], ["How", "can", "I", "help", "you?"],
    ] },
    uses: [
      ["Preguntas sí/no: empiezan con el auxiliar", "Do you like it? Is she here?", "¿Te gusta? ¿Está ella aquí?"],
      ["Preguntas por el sujeto: SIN auxiliar", "Who called you? What happened?", "¿Quién te llamó? ¿Qué pasó?"],
      ["Preguntas indirectas (más corteses)", "Could you tell me where the station is?", "¿Podría decirme dónde está la estación?"],
    ],
    mistakes: [
      ["Where you live?", "Where do you live?", "Falta el auxiliar do."], ["What means this?", "What does this mean?", "Wh- + does + sujeto + verbo."], ["How is called this?", "What is this called?", "«¿Cómo se llama?» = What is it called?"], ["Who did call you?", "Who called you?", "Si Who es el sujeto, no hay auxiliar."],
    ],
    spanish: "En español la entonación basta (¿Tú vives aquí?). En inglés hace falta cambiar el orden o usar un auxiliar: Do you live here?",
    tips: ["Recuerda QASI: Question word · Auxiliary · Subject · Infinitive (verbo).", "¿Cómo se dice…? = How do you say…? · ¿Qué significa…? = What does … mean?"],
  },
  "g.past-simple": {
    intro: "El Pasado Simple cuenta acciones terminadas en un momento concreto del pasado. Los verbos regulares añaden -ed; los irregulares tienen su propia forma. ¡La buena noticia: es igual para todas las personas!",
    form: { cols: ["", "Todas las personas", "Ejemplo"], rows: [
      ["✅ Afirmativo", "verbo-ed / forma irregular", "I worked. She went."], ["❌ Negativo", "didn't + verbo base", "I didn't work. She didn't go."], ["❓ Pregunta", "Did + sujeto + verbo base?", "Did you work? Where did she go?"], ["Respuesta corta", "Yes, I did. / No, I didn't.", ""],
      ["Be en pasado", "I / he / she / it WAS · you / we / they WERE", "I was tired. They weren't there."],
    ] },
    spelling: ["La mayoría: + ed → worked, played", "Terminan en -e: + d → lived, closed", "Consonante + y → ied → study → studied (pero play → played)", "Consonante-vocal-consonante: doblar → stop → stopped, plan → planned"],
    form2: { title: "Irregulares más frecuentes (apréndelos de 10 en 10)", cols: ["Base", "Pasado", "Base", "Pasado"], rows: [
      ["be", "was / were", "go", "went"], ["have", "had", "do", "did"], ["make", "made", "take", "took"], ["get", "got", "come", "came"], ["see", "saw", "say", "said"],
      ["know", "knew", "think", "thought"], ["give", "gave", "find", "found"], ["tell", "told", "leave", "left"], ["buy", "bought", "bring", "brought"], ["write", "wrote", "speak", "spoke"],
      ["eat", "ate", "drink", "drank"], ["meet", "met", "pay", "paid"], ["send", "sent", "spend", "spent"], ["begin", "began", "feel", "felt"],
    ] },
    uses: [
      ["Acción terminada con tiempo definido", "I visited Madrid in 2019.", "Visité Madrid en 2019."], ["Secuencia de acciones", "I got up, had a shower and left.", "Me levanté, me duché y salí."],
      ["Historias y reportes", "The pump stopped at 3 a.m.", "La bomba se detuvo a las 3 a. m."], ["Hábitos pasados", "When I was a child, I played soccer every day.", "De niño jugaba fútbol todos los días."],
    ],
    form3: { title: "Pronunciación de -ed", cols: ["Sonido", "Cuándo", "Ejemplos"], rows: [["/t/", "después de p, k, s, sh, ch, f", "worked, stopped, finished"], ["/d/", "después de sonidos sonoros y vocales", "played, called, lived"], ["/ɪd/ (sílaba extra)", "después de t o d", "wanted, needed, inspected"]] },
    signals: ["yesterday", "last night / week / year", "two days ago", "in 2020", "when I was…", "then / after that"],
    mistakes: [
      ["I didn't went.", "I didn't go.", "didn't + verbo base."], ["Did you saw…?", "Did you see…?", "did + verbo base."], ["Yesterday I go…", "Yesterday I went…", "Con yesterday → pasado."], ["I was go.", "I went.", "No mezcles was con otro verbo."], ["work-ed (2 sílabas)", "worked /wɜːrkt/", "-ed solo suena como sílaba después de t/d."],
    ],
    spanish: "Corresponde al pretérito indefinido (trabajé, fui) y a veces al imperfecto (jugaba). El pasado inglés no cambia por persona: I went, you went, she went.",
    tips: ["Aprende los irregulares en grupos que suenan parecido: buy/bought, bring/brought, think/thought.", "En negativas y preguntas el pasado lo lleva DID; el verbo vuelve a su forma base."],
  },
  "g.past-continuous": {
    intro: "El Pasado Continuo describe una acción en progreso en un momento del pasado. Muy útil para contar historias y describir el «escenario» cuando algo ocurrió.",
    form: { cols: ["", "Forma", "Ejemplo"], rows: [["✅", "was / were + verb-ing", "I was working. They were talking."], ["❌", "wasn't / weren't + verb-ing", "She wasn't listening."], ["❓", "Was / Were + sujeto + verb-ing?", "What were you doing at 8?"]] },
    uses: [
      ["Acción en progreso en un momento", "At 8 p.m. I was having dinner.", "A las 8 estaba cenando."],
      ["Acción larga interrumpida por una corta", "I was sleeping when the phone rang.", "Estaba durmiendo cuando sonó el teléfono."],
      ["Dos acciones largas a la vez", "While I was cooking, he was cleaning.", "Mientras yo cocinaba, él limpiaba."],
      ["Describir el escenario de una historia", "It was raining and people were running.", "Llovía y la gente corría."],
    ],
    signals: ["when (+ acción corta en past simple)", "while (+ acción larga en past continuous)", "at 8 o'clock yesterday", "all morning"],
    mistakes: [["I was work when…", "I was working when…", "Falta -ing."], ["When the alarm was ringing, I left.", "When the alarm rang, I left.", "La acción corta va en past simple."]],
    spanish: "Equivale a «estaba + -ando/-iendo» y a veces al imperfecto («llovía»).",
    tips: ["Imagina una línea: la acción larga (was …ing) y un rayo que la interrumpe (past simple).", "while + largo · when + corto."],
  },
  "g.going-to": {
    intro: "«Be going to» expresa planes e intenciones ya decididos y predicciones basadas en lo que vemos ahora.",
    form: { cols: ["", "Forma", "Ejemplo"], rows: [["✅", "am / is / are + going to + verbo base", "I'm going to study."], ["❌", "isn't / aren't + going to + verbo", "We aren't going to travel."], ["❓", "Are you going to + verbo?", "Are you going to apply?"]] },
    uses: [["Plan o intención", "I'm going to learn to drive this year.", "Voy a aprender a manejar este año."], ["Predicción con evidencia", "Look at the clouds! It's going to rain.", "¡Mira las nubes! Va a llover."], ["Decisión tomada antes de hablar", "I'm going to call the client after lunch.", "Voy a llamar al cliente después del almuerzo."]],
    signals: ["tomorrow", "next week / month / year", "soon", "this weekend"],
    mistakes: [["I going to study.", "I'm going to study.", "Falta be."], ["I'm going to studying.", "I'm going to study.", "Verbo base después de to."]],
    spanish: "Es igual que «ir a + infinitivo»: voy a estudiar = I'm going to study. ¡Muy fácil para hispanohablantes!",
    tips: ["En conversación informal suena «gonna»: I'm gonna call you. No lo escribas en textos formales.", "going to go → se puede simplificar: I'm going to the beach."],
  },
  "g.will": {
    intro: "«Will» se usa para decisiones tomadas en el momento, promesas, ofrecimientos y predicciones u opiniones sobre el futuro.",
    form: { cols: ["", "Forma", "Ejemplo"], rows: [["✅", "will ('ll) + verbo base", "I'll help you."], ["❌", "won't (will not) + verbo base", "It won't be easy."], ["❓", "Will + sujeto + verbo?", "Will you come?"]] },
    uses: [["Decisión en el momento", "The phone's ringing. — I'll get it!", "Suena el teléfono. — ¡Yo contesto!"], ["Promesa", "I'll send it today, I promise.", "Te lo envío hoy, lo prometo."], ["Ofrecimiento", "I'll carry your bag.", "Te llevo la maleta."], ["Predicción / opinión", "I think prices will rise.", "Creo que los precios subirán."], ["Pedido", "Will you help me?", "¿Me ayudas?"]],
    form2: { title: "Will vs going to", cols: ["will", "going to"], rows: [["Decides AHORA: «I'll have the fish.»", "Ya lo habías decidido: «I'm going to have the fish.»"], ["Opinión: «I think it will rain.»", "Evidencia: «Look at those clouds! It's going to rain.»"]] },
    signals: ["I think / I'm sure / probably", "tomorrow, next year, in the future", "I promise"],
    mistakes: [["I will to go.", "I will go.", "Sin to."], ["If it will rain…", "If it rains…", "Después de if, presente."], ["She wills.", "She will.", "Will no cambia."]],
    spanish: "Corresponde al futuro simple (iré, llamaré) y al presente con valor de ofrecimiento («Yo lo hago»).",
    tips: ["Shall I…? / Shall we…? = ¿…? para ofrecer o sugerir: Shall I open the window?"],
  },
  "g.comparatives": {
    intro: "Los comparativos sirven para comparar dos cosas: más grande que, más caro que, mejor que.",
    form: { cols: ["Tipo de adjetivo", "Regla", "Ejemplo"], rows: [
      ["1 sílaba", "+ er + than", "cheap → cheaper than, fast → faster"], ["1 sílaba terminada en -e", "+ r", "large → larger, safe → safer"], ["Consonante-vocal-consonante", "doblar + er", "big → bigger, hot → hotter"],
      ["2 sílabas terminadas en -y", "y → ier", "easy → easier, busy → busier"], ["2 o más sílabas", "more + adjetivo + than", "more expensive, more reliable"], ["Irregulares", "—", "good → better, bad → worse, far → farther/further"],
    ] },
    form2: { title: "Otras formas de comparar", cols: ["Estructura", "Significado", "Ejemplo"], rows: [["less + adj + than", "menos … que", "It's less expensive than the other one."], ["as + adj + as", "tan … como", "This pump is as powerful as that one."], ["not as + adj + as", "no tan … como", "It's not as cold as yesterday."], ["much / a lot / a bit + comparativo", "mucho / un poco más", "It's much cheaper. It's a bit faster."]] },
    uses: [["Comparar dos cosas", "Quito is higher than Lima.", "Quito es más alto que Lima."], ["Comparar ofertas", "Supplier A is cheaper but Supplier B is more reliable.", "El proveedor A es más barato pero el B es más confiable."]],
    mistakes: [["more better", "better", "Nunca more + -er."], ["more big", "bigger", "Adjetivos cortos con -er."], ["bigger that", "bigger than", "Que = than."], ["more easy", "easier", "-y → -ier."]],
    spanish: "En español siempre decimos «más … que». En inglés depende del largo del adjetivo: corto → -er; largo → more.",
    tips: ["Cuenta las sílabas: 1 → -er; 3 o más → more; 2 con -y → -ier.", "than suena /ðən/ en frases rápidas."],
  },
  "g.superlatives": {
    intro: "El superlativo expresa el grado máximo: el más grande, el mejor, el más caro de un grupo.",
    form: { cols: ["Tipo", "Regla", "Ejemplo"], rows: [["1 sílaba", "the + adj + est", "the cheapest, the fastest"], ["Doblar consonante", "the + big → biggest", "the hottest, the biggest"], ["-y", "the + iest", "the easiest, the busiest"], ["2+ sílabas", "the most + adj", "the most expensive"], ["Irregulares", "the best, the worst, the farthest", ""]] },
    uses: [["El máximo de un grupo o lugar (in)", "It's the tallest building in the city.", "Es el edificio más alto de la ciudad."], ["De un período (of)", "It was the best day of my life.", "Fue el mejor día de mi vida."], ["Con present perfect + ever", "It's the best movie I've ever seen.", "Es la mejor película que he visto."], ["El menos…", "the least expensive option", "la opción menos cara"]],
    mistakes: [["the most big", "the biggest", "Cortos con -est."], ["the better of all", "the best of all", "Superlativo de good = best."], ["the tallest of the city", "the tallest in the city", "Lugares con in."]],
    spanish: "«El más … de» = the …-est / the most … in/of.",
    tips: ["Comparativo compara 2; superlativo compara 3 o más.", "Recuerda la familia: good – better – the best · bad – worse – the worst."],
  },
  "g.quantifiers": {
    intro: "Para hablar de cantidades hay que saber si el sustantivo es contable (se puede contar: one valve, two valves) o incontable (no se cuenta: water, information).",
    form: { cols: ["", "Contables (plural)", "Incontables"], rows: [
      ["Mucho / muchos", "many (preguntas y negativas) · a lot of", "much (preguntas y negativas) · a lot of"],
      ["Algo / algunos", "some (+) · any (− ?)", "some (+) · any (− ?)"], ["Pocos / poco", "a few (algunos) · few (casi ninguno)", "a little (algo) · little (casi nada)"],
      ["¿Cuántos? / ¿Cuánto?", "How many?", "How much?"], ["Ninguno", "no / not any", "no / not any"],
    ] },
    uses: [["some en ofrecimientos y pedidos", "Would you like some coffee? Can I have some water?", "¿Quieres café? ¿Me das agua?"], ["any en preguntas y negativas", "Do you have any questions? We don't have any spare parts.", "¿Tienen preguntas? No tenemos repuestos."], ["a lot of en afirmativas (natural)", "We have a lot of work.", "Tenemos mucho trabajo."], ["Unidades para incontables", "a bottle of water, a piece of information, a cup of tea, a sheet of paper", "una botella de agua, un dato…"]],
    form2: { title: "Incontables comunes en el trabajo", cols: ["Incontable", "Para contar"], rows: [["information", "a piece of information"], ["advice", "a piece of advice"], ["equipment", "a piece of equipment"], ["feedback", "some feedback / a comment"], ["money", "dollars, coins"], ["furniture", "a piece of furniture / a chair"], ["news", "a piece of news (news es singular: The news is good.)"]] },
    mistakes: [["How much people?", "How many people?", "People es contable."], ["informations", "information", "Incontable."], ["I don't know nothing.", "I don't know anything.", "Sin doble negación."], ["a advice", "a piece of advice", "Incontable no lleva a/an."]],
    spanish: "Algunos contables en español son incontables en inglés: consejos (advice), muebles (furniture), noticias (news), información (information).",
    tips: ["Si puedes poner un número delante (two…), es contable → many/few.", "Si dudas, usa a lot of: sirve para los dos."],
  },
  "g.modals-obligation": {
    intro: "Estos verbos expresan obligación, prohibición, falta de necesidad y consejo. ¡Ojo! «Mustn't» y «don't have to» significan cosas MUY distintas.",
    form: { cols: ["Verbo", "Significado", "Ejemplo"], rows: [
      ["must", "obligación fuerte (reglas, lo que el hablante siente necesario)", "You must wear a helmet."], ["have to / has to", "obligación externa (leyes, jefe, horarios)", "I have to work on Saturday."],
      ["mustn't", "PROHIBIDO", "You mustn't smoke here."], ["don't have to", "NO es necesario (es opcional)", "You don't have to come. It's optional."],
      ["should / shouldn't", "consejo, recomendación", "You should rest. You shouldn't work so much."], ["need to / don't need to", "necesidad", "We need to finish today."],
    ] },
    form2: { title: "En pasado y futuro", cols: ["Tiempo", "Forma"], rows: [["Pasado", "had to: I had to work late yesterday. (must no tiene pasado)"], ["Futuro", "will have to: You'll have to wait."], ["Pregunta", "Do I have to…? / Should I…?"]] },
    uses: [["Normas de seguridad", "All visitors must sign in.", "Todos los visitantes deben registrarse."], ["Obligaciones del trabajo", "She has to submit the report by Friday.", "Tiene que entregar el informe el viernes."], ["Consejos", "You should read the contract carefully.", "Deberías leer el contrato con cuidado."]],
    mistakes: [["You don't have to smoke here (para prohibir).", "You mustn't smoke here.", "Prohibido = mustn't."], ["He musts go.", "He must go.", "Los modales no llevan -s."], ["You should to rest.", "You should rest.", "Sin to (excepto have to / need to)."], ["I must to go.", "I must go.", "Sin to."]],
    spanish: "«Tener que» = have to. «Deber» puede ser must (obligación) o should (consejo). «No tener que» = don't have to (no es necesario).",
    tips: ["mustn't = 🚫 (no se puede). don't have to = 🤷 (no hace falta).", "should = «yo que tú…»: consejo suave."],
  },
  "g.present-perfect": {
    intro: "El Present Perfect conecta el pasado con el presente. En A2 lo usamos sobre todo para EXPERIENCIAS de la vida, sin decir cuándo ocurrieron.",
    form: { cols: ["", "Forma", "Ejemplo"], rows: [["✅", "have / has + participio", "I've visited Spain. She's worked abroad."], ["❌", "haven't / hasn't + participio", "I haven't seen that movie."], ["❓", "Have / Has + sujeto + participio?", "Have you ever been to Peru?"], ["Respuesta corta", "Yes, I have. / No, I haven't.", ""]] },
    form2: { title: "Participios (3.ª columna)", cols: ["Base", "Pasado", "Participio"], rows: [["work", "worked", "worked (regular)"], ["be", "was/were", "been"], ["go", "went", "gone / been"], ["do", "did", "done"], ["see", "saw", "seen"], ["eat", "ate", "eaten"], ["write", "wrote", "written"], ["take", "took", "taken"], ["speak", "spoke", "spoken"], ["meet", "met", "met"]] },
    uses: [["Experiencias (alguna vez)", "Have you ever eaten ceviche?", "¿Alguna vez has comido ceviche?"], ["Nunca", "I've never flown in a helicopter.", "Nunca he volado en helicóptero."], ["Número de veces", "I've been to Lima three times.", "He estado en Lima tres veces."], ["Resultado presente", "I've lost my keys (and I don't have them now).", "He perdido mis llaves."]],
    signals: ["ever (alguna vez, en preguntas)", "never (nunca)", "once, twice, three times", "before"],
    form3: { title: "Present Perfect vs Past Simple", cols: ["Present Perfect (sin fecha)", "Past Simple (con fecha)"], rows: [["I've been to Mexico.", "I went to Mexico in 2019."], ["Have you ever tried sushi?", "When did you try it? — Last year."]] },
    mistakes: [["I have been in Spain last year.", "I went to Spain last year.", "Con fecha concreta → past simple."], ["Did you ever…?", "Have you ever…?", "Experiencias → present perfect."], ["She have seen.", "She has seen.", "she → has."]],
    spanish: "Se parece a «he + participio» (he visitado), pero en inglés no se usa con momentos terminados como «ayer» o «en 2019».",
    tips: ["been to = fui y volví. gone to = se fue y está allá.", "Pregunta clave: ¿digo CUÁNDO? Sí → past simple. No → present perfect."],
  },
  "g.conjunctions": {
    intro: "Los conectores unen ideas y hacen que tu inglés suene más natural y fluido.",
    form: { cols: ["Conector", "Función", "Ejemplo"], rows: [
      ["and", "sumar (y)", "I work and study."], ["but", "contraste (pero)", "It's cheap but slow."], ["or", "opción (o)", "Tea or coffee?"], ["because", "causa (porque)", "I'm late because of traffic… / because the bus was late."],
      ["so", "resultado (así que)", "It was late, so I took a taxi."], ["also", "además", "She also speaks French."], ["then / after that", "secuencia", "I had lunch. Then I went back to work."], ["when", "cuando", "Call me when you arrive."],
    ] },
    uses: [["because + frase / because of + sustantivo", "because it rained · because of the rain", "porque llovió · por la lluvia"], ["so: consecuencia", "The test failed, so we repeated it.", "La prueba falló, así que la repetimos."]],
    mistakes: [["Because I was tired. (frase sola)", "I went home because I was tired.", "because necesita la idea principal."], ["because the rain", "because of the rain", "Con sustantivo → because of."]],
    spanish: "«Porque» (respuesta) = because. «¿Por qué?» (pregunta) = why.",
    tips: ["Une frases cortas: «I was tired. I went to bed.» → «I was tired, so I went to bed.»"],
  },
};
