// Bancos de vocabulario profesional (secciones 50-58, 72-83, 153). Contenido original.
// Mismo formato que vocab.js. Enseña idioma, no asesoramiento profesional (sección 168).
import { buildWords } from "./vocab.js";

const RAW = {
  "eng-core": { title: "Engineering: equipment & operations", es: "Ingeniería: equipos y operación", icon: "⚙️", area: "engineering", words: [
    ["equipment", "equipo(s)", "ɪˈkwɪpmənt", "machines and tools needed for a job (uncountable)", "The equipment was inspected yesterday.", "B1", "🏗️"],
    ["maintenance", "mantenimiento", "ˈmeɪntənəns", "work done to keep something in good condition", "The pump needs preventive maintenance.", "B1", "🔧"],
    ["failure", "falla", "ˈfeɪljər", "when a machine stops working correctly", "The failure was caused by overheating.", "B1", "💥", "breakdown"],
    ["drawing", "plano", "ˈdrɔːɪŋ", "a technical picture that shows design details", "Please check the latest drawing revision.", "B1", "📐"],
    ["specification", "especificación", "ˌspesɪfɪˈkeɪʃn", "a detailed description of requirements", "The material must meet the specification.", "B2", "📑", "spec"],
    ["design", "diseño / diseñar", "dɪˈzaɪn", "a plan for how something will be made", "The design was approved last week.", "B1", "✏️"],
    ["installation", "instalación", "ˌɪnstəˈleɪʃn", "putting equipment in place ready for use", "Installation will take three days.", "B1", "🔩"],
    ["testing", "pruebas", "ˈtestɪŋ", "checking that something works", "Pressure testing starts on Monday.", "B1", "🧪"],
    ["commissioning", "puesta en marcha", "kəˈmɪʃənɪŋ", "testing a new system before it starts operating", "Commissioning is scheduled for June.", "B2", "🚦"],
    ["troubleshoot", "diagnosticar fallas", "ˈtrʌblʃuːt", "to find and fix problems", "Can you help me troubleshoot the motor?", "B2", "🛠️"],
    ["tolerance", "tolerancia", "ˈtɑːlərəns", "the allowed variation in a measurement", "The diameter is within tolerance.", "B2", "📏"],
    ["risk assessment", "evaluación de riesgos", "rɪsk əˈsesmənt", "a study of possible dangers and controls", "Complete the risk assessment before starting.", "B2", "⚠️"],
  ]},
  "oil-core": { title: "Oil & Gas", es: "Petróleo y gas", icon: "🛢️", area: "oilgas", words: [
    ["well", "pozo", "wel", "a hole drilled to get oil or gas", "The well produces 800 barrels a day.", "B1", "🕳️"],
    ["rig", "taladro / plataforma", "rɪɡ", "a structure used to drill wells", "The rig moved to a new location.", "B1", "🏗️"],
    ["drilling", "perforación", "ˈdrɪlɪŋ", "making a deep hole in the ground", "Drilling will start next month.", "B1", "⛏️"],
    ["pipeline", "oleoducto / tubería", "ˈpaɪplaɪn", "a long pipe that carries oil or gas", "The pipeline crosses the river.", "B1", "🛤️"],
    ["flowline", "línea de flujo", "ˈfloʊlaɪn", "a pipe that carries fluids from a well", "The flowline pressure is stable.", "B2", "〰️"],
    ["valve", "válvula", "vælv", "a device that controls the flow of liquid or gas", "Close the valve slowly.", "B1", "🚰"],
    ["pump", "bomba", "pʌmp", "a machine that moves liquid", "The pump is running at full capacity.", "B1", "⛽"],
    ["pressure", "presión", "ˈpreʃər", "force on a surface", "The pressure dropped suddenly.", "B1", "🧭"],
    ["corrosion", "corrosión", "kəˈroʊʒn", "damage to metal caused by chemical reactions", "We found corrosion on the tank.", "B2", "🦠"],
    ["shutdown", "parada", "ˈʃʌtdaʊn", "when a plant stops operating", "The plant shutdown lasts two weeks.", "B2", "⏹️", "", "start-up"],
    ["production", "producción", "prəˈdʌkʃn", "the amount of oil or gas produced", "Production increased by 5%.", "B1", "📈"],
    ["leak", "fuga", "liːk", "an unwanted escape of liquid or gas", "Report any leak immediately.", "B1", "💧"],
  ]},
  "energy": { title: "Energy", es: "Energía", icon: "⚡", area: "energy", words: [
    ["renewable", "renovable", "rɪˈnuːəbl", "coming from a source that doesn't run out", "Renewable energy is growing fast.", "B1", "♻️"],
    ["solar panel", "panel solar", "ˈsoʊlər ˈpænl", "a device that turns sunlight into electricity", "They installed solar panels on the roof.", "B1", "☀️"],
    ["wind turbine", "aerogenerador", "wɪnd ˈtɜːrbaɪn", "a machine that produces electricity from wind", "The wind turbines are offshore.", "B1", "🌬️"],
    ["hydropower", "energía hidroeléctrica", "ˈhaɪdroʊpaʊər", "electricity produced by moving water", "Ecuador uses a lot of hydropower.", "B2", "💧"],
    ["geothermal", "geotérmica", "ˌdʒiːoʊˈθɜːrml", "using heat from inside the earth", "Iceland uses geothermal energy.", "B2", "🌋"],
    ["grid", "red eléctrica", "ɡrɪd", "the network that delivers electricity", "The plant is connected to the grid.", "B2", "🔌"],
    ["generation", "generación", "ˌdʒenəˈreɪʃn", "the production of electricity", "Power generation is stable.", "B2", "⚡"],
    ["transmission", "transmisión", "trænsˈmɪʃn", "sending electricity over long distances", "Transmission losses are high.", "B2", "🗼"],
    ["battery storage", "almacenamiento en baterías", "ˈbætəri ˈstɔːrɪdʒ", "storing electricity in batteries", "Battery storage balances supply and demand.", "B2", "🔋"],
    ["energy efficiency", "eficiencia energética", "ˈenərdʒi ɪˈfɪʃnsi", "using less energy for the same result", "LED lights improve energy efficiency.", "B2", "💡"],
    ["sustainability", "sostenibilidad", "səˌsteɪnəˈbɪləti", "meeting needs without harming the future", "Sustainability is part of our strategy.", "B2", "🌱"],
  ]},
  "qa-core": { title: "QA/QC essentials", es: "QA/QC esencial", icon: "✅", area: "qaqc", words: [
    ["inspection", "inspección", "ɪnˈspekʃn", "a careful check of something", "The inspection is scheduled for 9 a.m.", "B1", "🔎"],
    ["quality control", "control de calidad", "ˈkwɑːləti kənˈtroʊl", "checking products to find defects", "Quality control rejected the batch.", "B1", "🧪", "QC"],
    ["quality assurance", "aseguramiento de calidad", "ˈkwɑːləti əˈʃʊrəns", "systems that prevent defects", "Quality assurance reviews the procedures.", "B2", "🛡️", "QA"],
    ["defect", "defecto", "ˈdiːfekt", "a fault or problem in a product", "The inspector found a defect in the weld.", "B1", "❗", "flaw"],
    ["non-conformance", "no conformidad", "ˌnɑːn kənˈfɔːrməns", "failure to meet a requirement", "We raised a non-conformance report.", "B2", "🚫", "nonconformity"],
    ["NCR", "informe de no conformidad", "ˌen siː ˈɑːr", "Non-Conformance Report", "Please close the NCR by Friday.", "B2", "📄"],
    ["corrective action", "acción correctiva", "kəˈrektɪv ˈækʃn", "action to remove the cause of a problem", "What corrective action did you take?", "B2", "🔁"],
    ["preventive action", "acción preventiva", "prɪˈventɪv ˈækʃn", "action to stop a problem from happening", "We implemented a preventive action.", "B2", "🛑"],
    ["acceptance", "aceptación", "əkˈseptəns", "approval that something meets requirements", "The client signed the acceptance.", "B2", "👍", "", "rejection"],
    ["rejection", "rechazo", "rɪˈdʒekʃn", "when something is not accepted", "The reason for rejection was porosity.", "B2", "👎", "", "acceptance"],
    ["release", "liberación", "rɪˈliːs", "permission for a product to continue", "QC gave the release for shipment.", "B2", "🚚"],
    ["calibration", "calibración", "ˌkælɪˈbreɪʃn", "adjusting a tool so it measures correctly", "The gauge calibration has expired.", "B2", "🎚️"],
  ]},
  "qa-docs": { title: "QA/QC documents & control points", es: "Documentos y puntos de control QA/QC", icon: "🗂️", area: "qaqc", words: [
    ["procedure", "procedimiento", "prəˈsiːdʒər", "an official way of doing something", "Follow the welding procedure.", "B1", "📘"],
    ["standard", "norma", "ˈstændərd", "an official set of rules or requirements", "The work complies with the ASME standard.", "B1", "📏"],
    ["traceability", "trazabilidad", "ˌtreɪsəˈbɪləti", "the ability to track the history of an item", "Material traceability is mandatory.", "B2", "🧬"],
    ["material certificate", "certificado de material", "məˈtɪriəl sərˈtɪfɪkət", "a document proving material properties", "Where is the material certificate?", "B2", "📜"],
    ["MTR", "reporte de pruebas del material", "ˌem tiː ˈɑːr", "Mill Test Report", "The MTR shows the chemical composition.", "B2", "🧾"],
    ["ITP", "plan de inspección y pruebas", "ˌaɪ tiː ˈpiː", "Inspection and Test Plan", "The ITP defines all the hold points.", "B2", "🗒️"],
    ["hold point", "punto de espera", "hoʊld pɔɪnt", "a stage where work stops until approval", "This is a hold point: we need the client.", "B2", "✋"],
    ["witness point", "punto de testificación", "ˈwɪtnəs pɔɪnt", "a stage the client may choose to observe", "The client will attend the witness point.", "B2", "👁️"],
    ["inspection report", "informe de inspección", "ɪnˈspekʃn rɪˈpɔːrt", "a document with inspection results", "Attach photos to the inspection report.", "B1", "📋"],
    ["documentation", "documentación", "ˌdɑːkjumenˈteɪʃn", "official documents and records", "The documentation is incomplete.", "B1", "📚"],
  ]},
  "audit": { title: "Audit English", es: "Inglés de auditoría", icon: "🔍", area: "auditing", words: [
    ["audit", "auditoría", "ˈɔːdɪt", "an official examination of records or processes", "The external audit is next week.", "B1", "🔍"],
    ["auditor", "auditor", "ˈɔːdɪtər", "a person who carries out an audit", "The lead auditor opened the meeting.", "B1", "🧑‍💼"],
    ["evidence", "evidencia", "ˈevɪdəns", "information that shows something is true (uncountable)", "Can you show me evidence of training?", "B1", "🗃️"],
    ["finding", "hallazgo", "ˈfaɪndɪŋ", "a result of an audit", "There were three findings.", "B2", "📍"],
    ["observation", "observación", "ˌɑːbzərˈveɪʃn", "a comment about a possible improvement", "This is an observation, not a nonconformity.", "B2", "👀"],
    ["opening meeting", "reunión de apertura", "ˈoʊpənɪŋ ˈmiːtɪŋ", "the first meeting of an audit", "The opening meeting starts at 8:30.", "B2", "🚪"],
    ["closing meeting", "reunión de cierre", "ˈkloʊzɪŋ ˈmiːtɪŋ", "the final meeting where findings are presented", "Findings are presented at the closing meeting.", "B2", "🔚"],
    ["scope", "alcance", "skoʊp", "the range of activities covered", "The scope includes production and warehouse.", "B2", "🎯"],
    ["compliance", "cumplimiento", "kəmˈplaɪəns", "following rules or requirements", "We verify compliance with ISO 9001.", "B2", "✔️"],
    ["record", "registro", "ˈrekərd", "a written document kept as proof", "Keep training records for five years.", "B1", "🗄️"],
  ]},
  "hr-recruitment": { title: "HR: recruitment", es: "RR. HH.: reclutamiento", icon: "🧲", area: "hr", words: [
    ["vacancy", "vacante", "ˈveɪkənsi", "a job that is available", "We have a vacancy in the finance team.", "B1", "📢", "opening"],
    ["job description", "descripción del puesto", "dʒɑːb dɪˈskrɪpʃn", "a document listing duties of a job", "Please update the job description.", "B1", "📄"],
    ["candidate", "candidato/a", "ˈkændɪdət", "a person applying for a job", "The candidate has great experience.", "B1", "🧑", "applicant"],
    ["resume", "currículum", "ˈrezəmeɪ", "a document about your education and experience", "Send your resume by email.", "B1", "📃", "CV"],
    ["cover letter", "carta de presentación", "ˈkʌvər ˈletər", "a letter sent with a job application", "Her cover letter was excellent.", "B1", "✉️"],
    ["screening", "preselección / filtro", "ˈskriːnɪŋ", "the first review of candidates", "Phone screening takes 15 minutes.", "B2", "🧹"],
    ["interview", "entrevista", "ˈɪntərvjuː", "a formal meeting to assess a candidate", "The interview is on Tuesday.", "A2", "🎙️"],
    ["references", "referencias", "ˈrefrənsɪz", "people who can describe your work", "We will check your references.", "B1", "📞"],
    ["job offer", "oferta de trabajo", "dʒɑːb ˈɔːfər", "a formal proposal of employment", "She accepted the job offer.", "B1", "🎁"],
    ["shortlist", "lista final de candidatos", "ˈʃɔːrtlɪst", "a small list of the best candidates", "Five candidates are on the shortlist.", "B2", "📝"],
    ["recruitment process", "proceso de selección", "rɪˈkruːtmənt ˈprɑːses", "all the steps to hire someone", "The recruitment process takes four weeks.", "B2", "🔄"],
  ]},
  "hr-onboarding": { title: "HR: onboarding", es: "RR. HH.: incorporación", icon: "🚀", area: "hr", words: [
    ["onboarding", "incorporación", "ˈɑːnbɔːrdɪŋ", "the process of welcoming a new employee", "Onboarding lasts one week.", "B2", "🧭"],
    ["induction", "inducción", "ɪnˈdʌkʃn", "an introduction to a job or workplace", "Safety induction is mandatory.", "B2", "🦺"],
    ["policy", "política", "ˈpɑːləsi", "an official set of rules", "Please read the vacation policy.", "B1", "📘"],
    ["benefits", "beneficios", "ˈbenɪfɪts", "extra advantages besides salary", "The benefits include health insurance.", "B1", "🎁"],
    ["responsibilities", "responsabilidades", "rɪˌspɑːnsəˈbɪlətiz", "duties that are part of your job", "Let me explain your responsibilities.", "B1", "📌"],
    ["mentor", "mentor", "ˈmentɔːr", "an experienced person who guides you", "Your mentor will help you this month.", "B1", "🧑‍🏫"],
    ["probation period", "período de prueba", "proʊˈbeɪʃn ˈpɪriəd", "the first months to evaluate a new employee", "The probation period is three months.", "B2", "⏳"],
    ["badge", "credencial", "bædʒ", "an ID card for entering a building", "Wear your badge at all times.", "B1", "🪪"],
  ]},
  "hr-performance": { title: "HR: performance management", es: "RR. HH.: gestión del desempeño", icon: "📊", area: "hr", words: [
    ["performance review", "evaluación de desempeño", "pərˈfɔːrməns rɪˈvjuː", "a meeting to evaluate an employee's work", "Performance reviews are in December.", "B2", "📊", "appraisal"],
    ["objective", "objetivo", "əbˈdʒektɪv", "a goal you want to achieve", "Let's set three objectives for next year.", "B1", "🎯", "goal"],
    ["KPI", "indicador clave de desempeño", "ˌkeɪ piː ˈaɪ", "Key Performance Indicator", "Our main KPI is on-time delivery.", "B2", "📐"],
    ["feedback", "retroalimentación", "ˈfiːdbæk", "comments about how well someone does something (uncountable)", "Thank you for your feedback.", "B1", "💬"],
    ["strengths", "fortalezas", "streŋθs", "things someone does well", "Communication is one of your strengths.", "B1", "💪", "", "weaknesses"],
    ["areas for improvement", "áreas de mejora", "ˈeriəz fər ɪmˈpruːvmənt", "skills that need development", "Time management is an area for improvement.", "B2", "📈"],
    ["development plan", "plan de desarrollo", "dɪˈveləpmənt plæn", "a plan to grow skills", "We agreed on a development plan.", "B2", "🗺️"],
    ["promotion", "ascenso", "prəˈmoʊʃn", "a move to a higher position", "She got a promotion last year.", "B1", "⬆️"],
  ]},
  "hr-relations": { title: "HR: employee relations", es: "RR. HH.: relaciones laborales", icon: "🤝", area: "hr", words: [
    ["complaint", "queja / reclamo", "kəmˈpleɪnt", "a statement that something is wrong", "She made a formal complaint.", "B1", "📣"],
    ["grievance", "queja formal", "ˈɡriːvəns", "an official complaint by an employee", "The grievance procedure has three steps.", "B2", "📂"],
    ["conflict", "conflicto", "ˈkɑːnflɪkt", "a serious disagreement", "We need to resolve this conflict.", "B1", "⚡"],
    ["concern", "inquietud / preocupación", "kənˈsɜːrn", "a worry about something", "Thank you for raising this concern.", "B1", "🤔"],
    ["disciplinary action", "medida disciplinaria", "ˈdɪsəplɪneri ˈækʃn", "an official response to bad conduct", "Disciplinary action may follow.", "B2", "⚖️"],
    ["misconduct", "falta de conducta", "ˌmɪsˈkɑːndʌkt", "bad or unacceptable behavior at work", "Theft is serious misconduct.", "C1", "🚨"],
    ["confidential", "confidencial", "ˌkɑːnfɪˈdenʃl", "private; not to be shared", "This conversation is confidential.", "B1", "🤐"],
    ["investigation", "investigación", "ɪnˌvestɪˈɡeɪʃn", "a formal examination of facts", "HR opened an investigation.", "B2", "🔍"],
  ]},
  "hr-policies": { title: "HR: policies, pay & benefits", es: "RR. HH.: políticas, pago y beneficios", icon: "💳", area: "hr", words: [
    ["leave", "licencia / permiso", "liːv", "time away from work with permission", "I'd like to request two days of leave.", "B1", "🏖️"],
    ["sick leave", "baja por enfermedad", "sɪk liːv", "time off work because you are ill", "He is on sick leave this week.", "B1", "🤒"],
    ["working hours", "horario laboral", "ˈwɜːrkɪŋ ˈaʊərz", "the hours you are expected to work", "Working hours are 8 to 5.", "A2", "🕘"],
    ["remote work", "trabajo remoto", "rɪˈmoʊt wɜːrk", "working from outside the office", "We allow remote work on Fridays.", "B1", "🏡"],
    ["payroll", "nómina", "ˈpeɪroʊl", "the system for paying employees", "Payroll is processed on the 25th.", "B2", "💵"],
    ["bonus", "bono", "ˈboʊnəs", "extra money for good results", "Employees receive an annual bonus.", "B1", "🎉"],
    ["overtime", "horas extra", "ˈoʊvərtaɪm", "time worked beyond normal hours", "Overtime is paid at 150%.", "B1", "⏰"],
    ["allowance", "asignación / viático", "əˈlaʊəns", "money given for a specific purpose", "There's a travel allowance.", "B2", "🧳"],
    ["compensation package", "paquete de compensación", "ˌkɑːmpenˈseɪʃn ˈpækɪdʒ", "salary plus all benefits", "The compensation package is competitive.", "B2", "📦"],
    ["code of conduct", "código de conducta", "koʊd əv ˈkɑːndʌkt", "rules for behavior at a company", "All staff must follow the code of conduct.", "B2", "📜"],
    ["insurance", "seguro", "ɪnˈʃʊrəns", "protection against costs if something bad happens", "Health insurance covers your family.", "B1", "🛡️"],
  ]},
  "hr-ld": { title: "HR: learning & development", es: "RR. HH.: formación y desarrollo", icon: "🌱", area: "hr", words: [
    ["training", "capacitación", "ˈtreɪnɪŋ", "teaching skills for a job", "The training starts on Monday.", "B1", "🏫"],
    ["coaching", "coaching / acompañamiento", "ˈkoʊtʃɪŋ", "helping someone improve through guidance", "Coaching helped her become a leader.", "B2", "🧑‍🏫"],
    ["mentoring", "mentoría", "ˈmentɔːrɪŋ", "support from an experienced colleague", "Our mentoring program is very popular.", "B2", "🤝"],
    ["competency", "competencia", "ˈkɑːmpɪtənsi", "a skill needed for a job", "Leadership is a key competency.", "B2", "🧩"],
    ["career plan", "plan de carrera", "kəˈrɪr plæn", "a plan for your professional future", "Let's talk about your career plan.", "B2", "🪜"],
    ["succession planning", "planificación de la sucesión", "səkˈseʃn ˈplænɪŋ", "preparing people to replace key roles", "Succession planning reduces risk.", "C1", "🔗"],
    ["leadership development", "desarrollo de liderazgo", "ˈliːdərʃɪp dɪˈveləpmənt", "programs that grow leaders", "She joined the leadership development program.", "B2", "🦁"],
  ]},
  "law-core": { title: "Legal vocabulary", es: "Vocabulario jurídico", icon: "⚖️", area: "law", words: [
    ["law", "ley / derecho", "lɔː", "the system of rules of a country", "Employment law protects workers.", "B1", "📚"],
    ["court", "tribunal", "kɔːrt", "a place where legal cases are decided", "The case went to court.", "B1", "🏛️"],
    ["judge", "juez", "dʒʌdʒ", "the person who decides a case in court", "The judge dismissed the claim.", "B1", "👨‍⚖️"],
    ["lawyer", "abogado/a", "ˈlɔːjər", "a person trained to give legal advice", "Our lawyer reviewed the contract.", "A2", "👩‍⚖️", "attorney"],
    ["counsel", "asesor/a legal", "ˈkaʊnsl", "a lawyer who gives advice (formal)", "Legal counsel attended the meeting.", "C1", "🗣️"],
    ["claim", "reclamación / demanda", "kleɪm", "a formal request for money or rights", "The supplier filed a claim.", "B2", "📨"],
    ["case", "caso", "keɪs", "a matter decided in court", "The case lasted two years.", "B1", "📁"],
    ["liability", "responsabilidad legal", "ˌlaɪəˈbɪləti", "legal responsibility for something", "The company accepted liability.", "B2", "🧾"],
    ["damages", "daños y perjuicios", "ˈdæmɪdʒɪz", "money paid for loss or injury", "The court awarded damages.", "C1", "💸"],
    ["breach", "incumplimiento", "briːtʃ", "breaking a rule or agreement", "Late delivery is a breach of contract.", "B2", "💔"],
    ["rights", "derechos", "raɪts", "things you are legally entitled to", "Employees have the right to rest.", "B1", "✊", "", "duties"],
    ["settlement", "acuerdo / transacción", "ˈsetlmənt", "an agreement that ends a dispute", "They reached a settlement.", "B2", "🤝"],
  ]},
  "law-systems": { title: "Legal systems", es: "Sistemas jurídicos", icon: "🏛️", area: "law", words: [
    ["common law", "derecho anglosajón", "ˈkɑːmən lɔː", "a system based on court decisions", "The UK has a common law system.", "C1", "🇬🇧"],
    ["civil law", "derecho civil / continental", "ˈsɪvl lɔː", "a system based on written codes", "Ecuador follows civil law.", "C1", "📕"],
    ["case law", "jurisprudencia", "keɪs lɔː", "law created by earlier court decisions", "Case law guides the judges.", "C1", "📚"],
    ["statute", "ley escrita / estatuto", "ˈstætʃuːt", "a written law passed by a legislature", "The statute sets a two-year limit.", "C1", "📜"],
    ["regulation", "reglamento / regulación", "ˌreɡjuˈleɪʃn", "an official rule", "New safety regulations apply from May.", "B2", "📏"],
    ["jurisdiction", "jurisdicción", "ˌdʒʊrɪsˈdɪkʃn", "the authority of a court over a place or case", "This court has no jurisdiction.", "C1", "🗺️"],
    ["legislation", "legislación", "ˌledʒɪsˈleɪʃn", "a law or set of laws", "Data protection legislation is strict.", "B2", "🏛️"],
    ["precedent", "precedente", "ˈpresɪdənt", "an earlier decision used as an example", "The ruling set a precedent.", "C1", "🧭"],
  ]},
  "law-contract": { title: "Contract English", es: "Inglés contractual", icon: "📝", area: "law", words: [
    ["agreement", "acuerdo / contrato", "əˈɡriːmənt", "a formal arrangement between parties", "Both parties signed the agreement.", "B1", "🤝", "contract"],
    ["party", "parte (contractual)", "ˈpɑːrti", "a person or company in a contract", "Each party must give 30 days' notice.", "B2", "👥"],
    ["effective date", "fecha de entrada en vigor", "ɪˈfektɪv deɪt", "the date a contract starts to apply", "The effective date is 1 January.", "B2", "📅"],
    ["term", "plazo / duración; término", "tɜːrm", "the period of a contract; also a condition", "The term of the agreement is two years.", "B2", "⏳"],
    ["termination", "terminación / rescisión", "ˌtɜːrmɪˈneɪʃn", "ending a contract", "Termination requires written notice.", "B2", "🛑"],
    ["obligations", "obligaciones", "ˌɑːblɪˈɡeɪʃnz", "things a party must do", "The supplier's obligations are listed in clause 4.", "B2", "📌"],
    ["warranty", "garantía", "ˈwɔːrənti", "a promise that something is true or will work", "The warranty covers defects for 12 months.", "B2", "🛡️"],
    ["indemnify", "indemnizar", "ɪnˈdemnɪfaɪ", "to compensate someone for loss", "The contractor shall indemnify the client.", "C1", "💰"],
    ["force majeure", "fuerza mayor", "ˌfɔːrs mæˈʒɜːr", "events beyond control that prevent performance", "The storm was a force majeure event.", "C1", "🌪️"],
    ["governing law", "ley aplicable", "ˈɡʌvərnɪŋ lɔː", "the law that applies to the contract", "The governing law is the law of England.", "C1", "🏛️"],
    ["dispute resolution", "resolución de controversias", "dɪˈspjuːt ˌrezəˈluːʃn", "the method to solve disagreements", "Dispute resolution is by arbitration.", "C1", "🕊️"],
    ["amendment", "enmienda / modificación", "əˈmendmənt", "a change to a document", "Any amendment must be in writing.", "B2", "✏️"],
    ["notice", "notificación / aviso", "ˈnoʊtɪs", "formal information or warning", "Send notice to the address in clause 15.", "B2", "📬"],
    ["confidentiality", "confidencialidad", "ˌkɑːnfɪˌdenʃiˈæləti", "keeping information private", "The confidentiality clause survives termination.", "B2", "🔒"],
  ]},
  "law-litigation": { title: "Litigation", es: "Litigio", icon: "🏛️", area: "law", words: [
    ["plaintiff", "demandante", "ˈpleɪntɪf", "the person who starts a court case", "The plaintiff asked for damages.", "C1", "🙋", "claimant", "defendant"],
    ["defendant", "demandado/a", "dɪˈfendənt", "the person accused or sued in court", "The defendant denied the claim.", "C1", "🧍", "", "plaintiff"],
    ["witness", "testigo", "ˈwɪtnəs", "a person who saw something and gives evidence", "The witness described the accident.", "B2", "👁️"],
    ["hearing", "audiencia", "ˈhɪrɪŋ", "a meeting of a court to examine a case", "The hearing is on 3 May.", "B2", "🔔"],
    ["trial", "juicio", "ˈtraɪəl", "the process of examining a case in court", "The trial lasted a week.", "B2", "⚖️"],
    ["appeal", "apelación", "əˈpiːl", "a request to a higher court to change a decision", "They filed an appeal.", "B2", "⬆️"],
    ["judgment", "sentencia / fallo", "ˈdʒʌdʒmənt", "the decision of a court", "The judgment was in our favor.", "C1", "🔨", "ruling"],
    ["testimony", "testimonio", "ˈtestɪmoʊni", "a formal statement given in court", "Her testimony was clear.", "C1", "🗣️"],
    ["proceedings", "procedimiento judicial", "prəˈsiːdɪŋz", "the process of a legal case", "Legal proceedings have started.", "C1", "📂"],
  ]},
  "law-corporate": { title: "Corporate law", es: "Derecho societario", icon: "🏢", area: "law", words: [
    ["corporation", "sociedad anónima / corporación", "ˌkɔːrpəˈreɪʃn", "a large company that is a legal entity", "The corporation has offices in ten countries.", "B2", "🏢"],
    ["shareholder", "accionista", "ˈʃerhoʊldər", "a person who owns shares in a company", "Shareholders approved the dividend.", "B2", "📈", "stockholder"],
    ["board of directors", "directorio / junta directiva", "bɔːrd əv dəˈrektərz", "the group that governs a company", "The board of directors meets monthly.", "B2", "🪑"],
    ["corporate governance", "gobierno corporativo", "ˈkɔːrpərət ˈɡʌvərnəns", "the system of rules that controls a company", "Good corporate governance builds trust.", "C1", "🧭"],
    ["resolution", "resolución / acuerdo", "ˌrezəˈluːʃn", "a formal decision of a board", "The board passed a resolution.", "C1", "📃"],
    ["subsidiary", "filial / subsidiaria", "səbˈsɪdieri", "a company controlled by another company", "The subsidiary is based in Peru.", "C1", "🌿"],
    ["joint venture", "empresa conjunta", "dʒɔɪnt ˈventʃər", "a business created by two companies together", "They formed a joint venture.", "C1", "🤝"],
    ["merger", "fusión", "ˈmɜːrdʒər", "joining two companies into one", "The merger was announced today.", "C1", "🔗"],
    ["acquisition", "adquisición", "ˌækwɪˈzɪʃn", "buying another company", "The acquisition cost $2 billion.", "C1", "🛒"],
  ]},
  "law-labor": { title: "Labor law English", es: "Inglés de derecho laboral", icon: "👷", area: "law", words: [
    ["employment contract", "contrato de trabajo", "ɪmˈplɔɪmənt ˈkɑːntrækt", "an agreement between employer and employee", "Read your employment contract carefully.", "B2", "📄"],
    ["employer", "empleador", "ɪmˈplɔɪər", "a company or person that employs people", "The employer must provide safety equipment.", "B1", "🏢", "", "employee"],
    ["employee", "empleado/a", "ɪmˈplɔɪiː", "a person who works for an employer", "The company has 300 employees.", "A2", "🧑‍🔧", "", "employer"],
    ["dismissal", "despido", "dɪsˈmɪsl", "ending someone's employment", "The dismissal was unfair.", "C1", "🚪", "termination"],
    ["resignation", "renuncia", "ˌrezɪɡˈneɪʃn", "officially leaving your job", "She handed in her resignation.", "B2", "✍️"],
    ["severance pay", "indemnización por despido", "ˈsevərəns peɪ", "money paid when employment ends", "He received severance pay.", "C1", "💵"],
    ["notice period", "período de preaviso", "ˈnoʊtɪs ˈpɪriəd", "time between resigning and leaving", "The notice period is 30 days.", "B2", "📆"],
  ]},
  "law-compliance": { title: "Compliance English", es: "Inglés de cumplimiento", icon: "🧭", area: "law", words: [
    ["ethics", "ética", "ˈeθɪks", "moral principles of behavior", "Our ethics policy is clear.", "B2", "🧭"],
    ["internal controls", "controles internos", "ɪnˈtɜːrnl kənˈtroʊlz", "processes to prevent errors and fraud", "Internal controls were tested.", "C1", "🎛️"],
    ["conflict of interest", "conflicto de interés", "ˈkɑːnflɪkt əv ˈɪntrəst", "when personal interest affects a decision", "Declare any conflict of interest.", "B2", "⚔️"],
    ["bribery", "soborno", "ˈbraɪbəri", "offering money to influence someone illegally", "Bribery is strictly prohibited.", "C1", "💰"],
    ["anti-corruption", "anticorrupción", "ˌænti kəˈrʌpʃn", "rules against dishonest behavior", "Complete the anti-corruption training.", "C1", "🚫"],
    ["privacy", "privacidad", "ˈpraɪvəsi", "the right to keep personal information private", "We respect your privacy.", "B1", "🔏"],
    ["whistleblower", "denunciante", "ˈwɪslbloʊər", "a person who reports wrongdoing", "Whistleblowers are protected.", "C1", "📯"],
    ["reporting", "reporte / denuncia", "rɪˈpɔːrtɪŋ", "telling the right people about a problem", "Use the reporting hotline.", "B2", "☎️"],
  ]},
  "finance": { title: "Finance", es: "Finanzas", icon: "💹", area: "finance", words: [
    ["revenue", "ingresos", "ˈrevənuː", "money a company receives from sales", "Revenue grew by 12%.", "B2", "💰", "income"],
    ["cost", "costo", "kɔːst", "the amount of money needed", "We need to reduce costs.", "B1", "💸"],
    ["cash flow", "flujo de caja", "kæʃ floʊ", "money coming in and going out", "Cash flow is positive this quarter.", "B2", "🌊"],
    ["balance sheet", "balance general", "ˈbæləns ʃiːt", "a statement of assets and liabilities", "Let's look at the balance sheet.", "C1", "📊"],
    ["assets", "activos", "ˈæsets", "things of value a company owns", "Total assets increased.", "B2", "🏦", "", "liabilities"],
    ["forecast", "proyección", "ˈfɔːrkæst", "an estimate of future results", "The sales forecast looks good.", "B2", "🔮"],
    ["loss", "pérdida", "lɔːs", "money lost", "The company reported a loss.", "B1", "📉", "", "profit"],
    ["tax", "impuesto", "tæks", "money paid to the government", "Prices include tax.", "B1", "🏛️"],
    ["audit trail", "pista de auditoría", "ˈɔːdɪt treɪl", "records that show every transaction", "Keep a clear audit trail.", "C1", "👣"],
  ]},
  "medicine": { title: "Medicine", es: "Medicina", icon: "🩺", area: "medicine", words: [
    ["symptom", "síntoma", "ˈsɪmptəm", "a sign of illness", "What are your symptoms?", "B1", "🤧"],
    ["diagnosis", "diagnóstico", "ˌdaɪəɡˈnoʊsɪs", "identifying an illness", "The diagnosis was confirmed.", "B2", "🩻"],
    ["treatment", "tratamiento", "ˈtriːtmənt", "medical care for an illness", "The treatment takes two weeks.", "B1", "💉"],
    ["patient", "paciente", "ˈpeɪʃnt", "a person receiving medical care", "The patient is stable.", "B1", "🛌"],
    ["surgery", "cirugía", "ˈsɜːrdʒəri", "an operation on the body", "He needs surgery.", "B2", "🏥"],
    ["allergy", "alergia", "ˈælərdʒi", "a bad reaction to a substance", "Do you have any allergies?", "B1", "🤧"],
    ["dose", "dosis", "doʊs", "the amount of medicine to take", "Take one dose every eight hours.", "B1", "💊"],
    ["emergency", "emergencia", "iˈmɜːrdʒənsi", "a sudden dangerous situation", "Call 911 in an emergency.", "B1", "🚑"],
  ]},
  "tech": { title: "Technology (IT)", es: "Tecnología (TI)", icon: "🖥️", area: "technology", words: [
    ["server", "servidor", "ˈsɜːrvər", "a computer that provides data to others", "The server is down.", "B1", "🗄️"],
    ["database", "base de datos", "ˈdeɪtəbeɪs", "an organized collection of data", "The database stores all orders.", "B1", "🗃️"],
    ["bug", "error (de software)", "bʌɡ", "a mistake in a program", "We found a bug in the app.", "B1", "🐛"],
    ["deploy", "desplegar", "dɪˈplɔɪ", "to release software to users", "We deploy every Friday.", "B2", "🚀"],
    ["cloud", "nube", "klaʊd", "servers accessed over the internet", "Our files are in the cloud.", "B1", "☁️"],
    ["cybersecurity", "ciberseguridad", "ˌsaɪbərsɪˈkjʊrəti", "protection of systems from attacks", "Cybersecurity training is mandatory.", "B2", "🛡️"],
    ["user", "usuario", "ˈjuːzər", "a person who uses a system", "The user can't log in.", "A2", "👤"],
    ["backup", "respaldo", "ˈbækʌp", "a copy of data kept safe", "Do you have a backup?", "B1", "💾"],
  ]},
  "pm": { title: "Project management", es: "Gestión de proyectos", icon: "📋", area: "pm", words: [
    ["milestone", "hito", "ˈmaɪlstoʊn", "an important point in a project", "We reached the first milestone.", "B2", "🚩"],
    ["scope creep", "desvío del alcance", "skoʊp kriːp", "uncontrolled growth of project scope", "Scope creep delayed the project.", "C1", "🐢"],
    ["stakeholders", "interesados", "ˈsteɪkhoʊldərz", "people affected by a project", "Keep stakeholders informed.", "B2", "👥"],
    ["on schedule", "a tiempo (según cronograma)", "ɑːn ˈskedʒuːl", "happening at the planned time", "We are on schedule.", "B1", "✅", "on track", "behind schedule"],
    ["behind schedule", "atrasado", "bɪˈhaɪnd ˈskedʒuːl", "later than planned", "The project is two weeks behind schedule.", "B1", "🐌"],
    ["deliverable", "entregable", "dɪˈlɪvərəbl", "a product or result to be delivered", "The main deliverable is the design report.", "B2", "📦"],
    ["resources", "recursos", "ˈriːsɔːrsɪz", "people, money and materials available", "We need more resources.", "B1", "🧰"],
    ["kick-off meeting", "reunión de lanzamiento", "ˈkɪk ɔːf ˈmiːtɪŋ", "the first meeting of a project", "The kick-off meeting is on Monday.", "B2", "🏁"],
  ]},
  "hse": { title: "HSE (Health, Safety & Environment)", es: "Seguridad, salud y ambiente", icon: "🦺", area: "hse", words: [
    ["hazard", "peligro", "ˈhæzərd", "something that can cause harm", "Identify all hazards before starting.", "B1", "☢️"],
    ["PPE", "equipo de protección personal", "ˌpiː piː ˈiː", "Personal Protective Equipment", "Wear PPE at all times.", "B1", "🥽"],
    ["near miss", "casi accidente", "nɪr mɪs", "an event that almost caused an accident", "Report every near miss.", "B2", "😮"],
    ["permit to work", "permiso de trabajo", "ˈpɜːrmɪt tə wɜːrk", "a document that authorizes risky work", "You need a permit to work for hot work.", "B2", "🪪"],
    ["lockout", "bloqueo", "ˈlɑːkaʊt", "isolating energy before maintenance", "Apply lockout before opening the panel.", "B2", "🔒"],
    ["incident", "incidente", "ˈɪnsɪdənt", "an unexpected event, often harmful", "Fill in the incident report.", "B1", "🚨"],
    ["evacuation", "evacuación", "ɪˌvækjuˈeɪʃn", "moving people away from danger", "Know the evacuation route.", "B1", "🏃"],
    ["spill", "derrame", "spɪl", "liquid that has accidentally come out", "Clean the oil spill immediately.", "B1", "🫗"],
  ]},
  "procurement": { title: "Procurement", es: "Compras / abastecimiento", icon: "🛒", area: "procurement", words: [
    ["purchase order", "orden de compra", "ˈpɜːrtʃəs ˈɔːrdər", "an official document to buy goods", "We issued the purchase order yesterday.", "B1", "🧾", "PO"],
    ["quotation", "cotización", "kwoʊˈteɪʃn", "a written price offer", "Please send a quotation by Friday.", "B1", "💬", "quote"],
    ["tender", "licitación", "ˈtendər", "a formal process to choose a supplier", "Five companies joined the tender.", "B2", "📣", "bid"],
    ["lead time", "tiempo de entrega", "liːd taɪm", "time between ordering and receiving", "The lead time is six weeks.", "B2", "⏱️"],
    ["vendor", "proveedor", "ˈvendər", "a company that sells goods", "Approved vendors are listed here.", "B1", "🏪", "supplier"],
    ["delivery", "entrega", "dɪˈlɪvəri", "bringing goods to a place", "Delivery is scheduled for Monday.", "A2", "🚚"],
    ["negotiate", "negociar", "nɪˈɡoʊʃieɪt", "to discuss to reach an agreement", "We negotiated a better price.", "B1", "🤝"],
  ]},
};

const built = buildWords(RAW);
export const PRO_WORDS = built.words;
export const PRO_TOPICS = built.topics;
