// Banco original de exámenes (inspirado en los FORMATOS de EF SET y GoFluent; no se copia contenido oficial).
// q: [pregunta, respuesta correcta, [distractores]]

export const TEST_READINGS = [
  { level: "A1", title: "A note on the fridge", text: "Hi Tom,\nI'm at the supermarket. There is pizza in the fridge for dinner. Please feed the cat at seven. Mom calls at eight. I'm home at nine.\nLove,\nSara",
    q: [["Where is Sara?", "At the supermarket.", ["At home.", "At work."]], ["What is for dinner?", "Pizza.", ["Chicken.", "Fish."]], ["When does Tom feed the cat?", "At seven.", ["At eight.", "At nine."]], ["Who calls at eight?", "Mom.", ["Sara.", "Tom."]]] },
  { level: "A1", title: "My new job", text: "My name is Pablo. I am a driver. I work for a small company in Cuenca. I start work at seven in the morning and I finish at four. I drive a white van. I like my job because I meet new people every day. On Saturdays I don't work.",
    q: [["What is Pablo's job?", "He is a driver.", ["He is a mechanic.", "He is a teacher."]], ["What time does he finish?", "At four.", ["At seven.", "At noon."]], ["What color is the van?", "White.", ["Red.", "Blue."]], ["Why does he like his job?", "He meets new people.", ["The salary is high.", "He works from home."]]] },
  { level: "A2", title: "A weekend in the mountains", text: "Last weekend my friends and I went to Baños. We left early on Saturday morning and arrived at ten. In the afternoon we rode bikes to a waterfall. It was hard work but the view was amazing. In the evening we had dinner in a small restaurant and I tried trout for the first time. On Sunday it rained, so we visited the hot springs. We came back tired but happy.",
    q: [["How did they travel to the waterfall?", "By bike.", ["By bus.", "On foot."]], ["What did the writer eat for the first time?", "Trout.", ["Pizza.", "Chicken."]], ["Why did they visit the hot springs?", "Because it rained.", ["Because it was hot.", "Because the bikes broke."]], ["How did they feel at the end?", "Tired but happy.", ["Bored.", "Angry."]]] },
  { level: "A2", title: "Office notice", text: "IMPORTANT: From Monday 5 May, the main entrance will be closed for repairs. Please use the side door next to the car park. The cafeteria will open at 8:00 instead of 7:30 during the repairs. If you need a parking space, please email reception before Friday. Thank you for your patience.",
    q: [["Why is the main entrance closed?", "For repairs.", ["For a holiday.", "Because of a meeting."]], ["Which door should people use?", "The side door near the car park.", ["The back door of the cafeteria.", "The main entrance."]], ["What time will the cafeteria open?", "At 8:00.", ["At 7:30.", "At 9:00."]], ["What should you do if you need parking?", "Email reception before Friday.", ["Call security.", "Park on the street."]]] },
  { level: "B1", title: "Learning a language at work", text: "More and more companies are offering language training to their employees. For many workers, lessons during working hours are the only realistic way to study, because evenings are busy with family. Research shows that employees who improve their English are more likely to be promoted and feel more confident in international meetings. However, success depends on regular practice. Experts recommend short daily sessions rather than one long class per week, because the brain remembers information better when it is reviewed several times.",
    q: [["Why do many workers prefer lessons during working hours?", "Their evenings are busy with family.", ["They are cheaper.", "Teachers prefer it."]], ["What is one benefit of improving English at work?", "Employees are more likely to be promoted.", ["They work fewer hours.", "They travel less."]], ["What do experts recommend?", "Short daily practice.", ["One long weekly class.", "Studying only before exams."]], ["Why is regular review important?", "The brain remembers better with repetition.", ["Teachers are not available.", "Classes are too short."]]] },
  { level: "B1", title: "Customer complaint", text: "Dear Customer Service,\nI am writing to complain about the coffee machine I bought from your website on 2 June. When it arrived, the water tank was cracked and the machine did not turn on. I contacted your support team twice by phone, but nobody called me back. I would like a full refund or a replacement as soon as possible. I have attached photos of the damage.\nYours faithfully,\nMarta López",
    q: [["What is the problem with the machine?", "The tank was cracked and it didn't turn on.", ["It was the wrong color.", "It arrived late."]], ["How many times did Marta call support?", "Twice.", ["Once.", "Three times."]], ["What does Marta want?", "A refund or a replacement.", ["A discount on her next order.", "A technician to visit."]], ["What did she attach?", "Photos of the damage.", ["The invoice only.", "A video."]]] },
  { level: "B2", title: "Remote teams", text: "Managing a remote team requires a different set of skills from managing people in an office. Without casual conversations in the corridor, misunderstandings can grow unnoticed. Successful remote managers therefore over-communicate: they set clear expectations in writing, hold short but regular check-ins and make a deliberate effort to recognise achievements publicly. Interestingly, several studies have found that remote employees are not less productive; in fact, many report fewer interruptions. The main risk is isolation, which, if left unaddressed, can lead to lower engagement and higher staff turnover.",
    q: [["Why can misunderstandings grow in remote teams?", "There are no casual conversations.", ["Managers are less skilled.", "Employees work fewer hours."]], ["What do successful remote managers do?", "They over-communicate and recognise achievements.", ["They avoid meetings.", "They monitor screens constantly."]], ["What have studies found about productivity?", "Remote employees are not less productive.", ["Remote employees are much less productive.", "Productivity cannot be measured."]], ["What is the main risk mentioned?", "Isolation.", ["High costs.", "Technology failures."]]] },
  { level: "B2", title: "Supplier evaluation", text: "Selecting a supplier purely on price is a common but costly mistake. A cheaper supplier may lack the quality systems needed to deliver consistent products, and the cost of rejected batches, delays and rework can quickly exceed the initial savings. For this reason, many organisations use a weighted scorecard that considers quality history, delivery performance, financial stability and technical capability alongside price. Suppliers are then audited periodically, and those who fall below an agreed threshold are asked to submit an improvement plan.",
    q: [["Why is choosing only on price a mistake?", "Hidden costs can exceed the savings.", ["Cheap suppliers never deliver.", "Prices change every month."]], ["What is a weighted scorecard?", "A tool that evaluates several criteria.", ["A list of the cheapest suppliers.", "A contract template."]], ["What happens to suppliers below the threshold?", "They must submit an improvement plan.", ["They are fined immediately.", "Nothing happens."]], ["Which is NOT mentioned as a criterion?", "Number of employees.", ["Delivery performance.", "Financial stability."]]] },
  { level: "C1", title: "The paradox of choice", text: "It is widely assumed that more options lead to greater satisfaction. Yet a substantial body of research suggests otherwise: when confronted with an abundance of alternatives, people frequently postpone decisions, and those who do choose tend to be less satisfied with the outcome, haunted by the attractive features of the options they rejected. This phenomenon, often termed the 'paradox of choice', has clear implications for product design and public policy. Rather than eliminating choice altogether, the most effective interventions curate it — offering a manageable set of well-differentiated options and sensible defaults.",
    q: [["What is the common assumption challenged by the text?", "More options increase satisfaction.", ["People prefer fewer products.", "Choice has no effect."]], ["What happens when people face too many options?", "They postpone decisions and feel less satisfied.", ["They always choose the cheapest.", "They become more loyal."]], ["What does 'haunted' suggest in this context?", "They keep thinking about the rejected options.", ["They are scared of products.", "They forget the options quickly."]], ["What do the most effective interventions do?", "Curate choice with a few clear options and defaults.", ["Remove all choices.", "Offer as many options as possible."]]] },
  { level: "C1", title: "Carbon accounting", text: "As investors increasingly scrutinise environmental performance, companies are under pressure to disclose their greenhouse gas emissions. Direct emissions from owned operations (Scope 1) and purchased energy (Scope 2) are relatively straightforward to measure. Scope 3 emissions, however, which arise across the entire value chain — from suppliers' factories to the use of sold products — often account for the majority of a company's footprint and are notoriously difficult to quantify. Critics warn that without standardised methodologies, disclosures risk becoming exercises in public relations rather than meaningful measures of progress.",
    q: [["Why are companies disclosing emissions?", "Investors are scrutinising environmental performance.", ["It reduces taxes.", "Customers demand lower prices."]], ["Which emissions are hardest to measure?", "Scope 3.", ["Scope 1.", "Scope 2."]], ["What do Scope 3 emissions often represent?", "The majority of the footprint.", ["A tiny fraction.", "Only energy use."]], ["What is the critics' concern?", "Disclosures may become public relations.", ["Companies will stop reporting.", "Measurement is too expensive."]]] },
];

// Diálogos para listening (se leen con TTS). "A:" y "B:" alternan voces si el dispositivo lo permite.
export const TEST_LISTENINGS = [
  { level: "A1", lines: ["A: Hi! Are you Mr. Brown?", "B: No, I'm not. I'm Mr. Green. Mr. Brown is in room five."], q: [["What is the man's name?", "Mr. Green.", ["Mr. Brown.", "Mr. Five."]], ["Where is Mr. Brown?", "In room five.", ["At home.", "In room nine."]]] },
  { level: "A1", lines: ["A: How much is this T-shirt?", "B: It's twelve dollars.", "A: And the blue one?", "B: That one is fifteen."], q: [["How much is the first T-shirt?", "$12", ["$20", "$15"]], ["How much is the blue T-shirt?", "$15", ["$12", "$50"]]] },
  { level: "A2", lines: ["A: Excuse me, how do I get to the train station?", "B: Go straight on and take the second street on the left. The station is next to the post office.", "A: Is it far?", "B: No, it's about five minutes on foot."], q: [["Which street should the person take?", "The second on the left.", ["The first on the right.", "The second on the right."]], ["What is next to the station?", "The post office.", ["A bank.", "A hotel."]], ["How long is the walk?", "About five minutes.", ["About fifteen minutes.", "About an hour."]]] },
  { level: "A2", lines: ["A: Hello, I'd like to book a table for Friday evening.", "B: Of course. For how many people?", "A: For four, at half past eight.", "B: I'm sorry, we're full at eight thirty. Is nine o'clock OK?", "A: Yes, that's fine."], q: [["When does the person want to eat?", "Friday evening.", ["Thursday evening.", "Friday lunch."]], ["How many people?", "Four.", ["Two.", "Eight."]], ["What time is the booking?", "Nine o'clock.", ["Half past eight.", "Eight o'clock."]]] },
  { level: "B1", lines: ["A: Did you finish the inspection report?", "B: Almost. I'm still waiting for the lab results for the weld samples.", "A: When will you get them?", "B: They promised them by Thursday, so I'll send the report on Friday morning."], q: [["What is B waiting for?", "Lab results.", ["A new inspector.", "The client's approval."]], ["When will the report be sent?", "Friday morning.", ["Thursday.", "Monday."]]] },
  { level: "B1", lines: ["A: I'm calling about the job advertisement for a sales assistant.", "B: Yes, the position is still open. Do you have any experience?", "A: I worked in a clothes shop for two years while I was at university.", "B: Great. Could you email us your CV and come for an interview on Tuesday?"], q: [["What job is the caller interested in?", "Sales assistant.", ["Receptionist.", "Teacher."]], ["Where did the caller work before?", "In a clothes shop.", ["In a bank.", "At the university library."]], ["What should the caller do next?", "Email a CV and attend an interview.", ["Start work on Tuesday.", "Call again next week."]]] },
  { level: "B2", lines: ["A: The figures for the third quarter look disappointing.", "B: They do, but bear in mind that we lost two weeks of production because of the shutdown.", "A: True. If we adjust for that, are we on track for the annual target?", "B: More or less. We'd need a strong fourth quarter, which is realistic given the new contracts."], q: [["Why were third-quarter figures low?", "Production stopped for two weeks.", ["They lost a major client.", "Prices fell."]], ["What is B's view on the annual target?", "It's achievable with a strong fourth quarter.", ["It's impossible.", "It has already been reached."]]] },
  { level: "B2", lines: ["A: I'm not entirely convinced we should outsource the maintenance.", "B: What's your main concern?", "A: Response times. If a critical pump fails at night, an external contractor might take hours to arrive.", "B: That's a fair point. We could include a guaranteed response time in the contract, with penalties if they miss it."], q: [["What is A's main concern about outsourcing?", "Slow response times.", ["High costs.", "Poor quality of parts."]], ["What does B suggest?", "A guaranteed response time with penalties.", ["Cancelling the plan.", "Hiring more night staff."]]] },
  { level: "C1", lines: ["A: What struck me about the proposal is how little it says about implementation.", "B: Admittedly, it's rather light on detail. The authors seem to assume that once the policy is announced, compliance will follow.", "A: Which, in my experience, is wishful thinking. Without training and clear accountability, it'll simply be ignored."], q: [["What is A's criticism of the proposal?", "It lacks implementation detail.", ["It is too expensive.", "It is too long."]], ["What does 'wishful thinking' mean here?", "An unrealistic hope.", ["A careful plan.", "A legal requirement."]], ["According to A, what is needed?", "Training and clear accountability.", ["A new policy.", "More announcements."]]] },
];

// Preguntas de inglés de negocios, formato situacional (estilo GoFluent)
export const BUSINESS_ITEMS = [
  { level: "A2", q: "A colleague says: “Thanks for your help!” You reply:", a: "You're welcome.", d: ["Yes, please.", "I'm sorry."] },
  { level: "A2", q: "You answer the office phone. What do you say?", a: "Good morning, QualiTech. How can I help you?", d: ["Who are you?", "What do you want?"] },
  { level: "A2", q: "You want to know the time of a meeting. You ask:", a: "What time is the meeting?", d: ["When the meeting is?", "What hour the meeting?"] },
  { level: "A2", q: "Choose the best subject line for an email asking for a day off:", a: "Leave request – Friday 12 May", d: ["Hello!!!", "Important thing"] },
  { level: "B1", q: "Best way to start a formal email to someone you don't know:", a: "Dear Mr. Evans,", d: ["Hey Evans!", "Hi guy,"] },
  { level: "B1", q: "Best way to close a formal email:", a: "Kind regards,", d: ["See ya!", "Love,"] },
  { level: "B1", q: "You didn't hear what someone said in a meeting. You say:", a: "Sorry, could you repeat that, please?", d: ["What?", "Repeat."] },
  { level: "B1", q: "You want to disagree politely:", a: "I see your point, but I have a different view.", d: ["You're wrong.", "That's stupid."] },
  { level: "B1", q: "“Please find attached the report.” This means:", a: "The report is included with the email.", d: ["The report is lost.", "Please look for the report."] },
  { level: "B1", q: "Complete: “I look forward to ___ from you.”", a: "hearing", d: ["hear", "heard"] },
  { level: "B1", q: "A client is angry because a delivery is late. The best first reply is:", a: "I'm very sorry for the delay. Let me check what happened.", d: ["It's not my fault.", "Deliveries are always late."] },
  { level: "B1", q: "“ASAP” means:", a: "As soon as possible", d: ["As simple as possible", "After some approval process"] },
  { level: "B1", q: "In a meeting, to move to the next topic you say:", a: "Let's move on to the next point.", d: ["Next thing now.", "Stop talking."] },
  { level: "B1", q: "Complete: “Could you ___ me know by Friday?”", a: "let", d: ["make", "tell"] },
  { level: "B2", q: "Most diplomatic way to reject a supplier's price:", a: "I'm afraid that's above our budget. Is there any flexibility?", d: ["Your price is ridiculous.", "No. Too expensive."] },
  { level: "B2", q: "“We're on the same page” means:", a: "We agree / understand each other.", d: ["We read the same document.", "We work in the same office."] },
  { level: "B2", q: "Complete: “The project is ___ schedule, so we'll finish early.”", a: "ahead of", d: ["behind", "on top of"] },
  { level: "B2", q: "Best way to ask for a deadline extension:", a: "Would it be possible to extend the deadline until Monday?", d: ["Give me more time.", "I want Monday."] },
  { level: "B2", q: "“Let's touch base next week” means:", a: "Let's contact each other briefly next week.", d: ["Let's play baseball.", "Let's cancel the project."] },
  { level: "B2", q: "Complete: “Should you ___ any questions, please contact me.”", a: "have", d: ["having", "had"] },
  { level: "B2", q: "In a negotiation, “What's your bottom line?” asks for:", a: "The minimum you can accept.", d: ["Your last page.", "Your email signature."] },
  { level: "B2", q: "Best way to summarize at the end of a meeting:", a: "So, to sum up, we've agreed to…", d: ["OK, bye.", "Whatever, finished."] },
  { level: "C1", q: "Most appropriate way to raise a concern with senior management:", a: "I'd like to flag a potential risk regarding the timeline.", d: ["The timeline is a disaster.", "Someone messed up the timeline."] },
  { level: "C1", q: "“The proposal was met with a lukewarm response” means it was:", a: "received without much enthusiasm.", d: ["received very warmly.", "rejected angrily."] },
  { level: "C1", q: "Complete: “Not only ___ the target, but we exceeded it.”", a: "did we meet", d: ["we met", "we did meet"] },
  { level: "C1", q: "Which sentence is the most concise for a report?", a: "Costs rose 12% owing to higher energy prices.", d: ["Costs, they went up by like 12 percent because energy was more expensive.", "There was an increase that happened in costs of 12%."] },
];

// Descriptores tipo EF SET: puntuación 0-100 ↔ CEFR
export const SCORE_BANDS = [
  { level: "A1", min: 1, max: 30, label: "Beginner" }, { level: "A2", min: 31, max: 40, label: "Elementary" },
  { level: "B1", min: 41, max: 50, label: "Intermediate" }, { level: "B2", min: 51, max: 60, label: "Upper Intermediate" },
  { level: "C1", min: 61, max: 70, label: "Advanced" }, { level: "C2", min: 71, max: 100, label: "Proficient" },
];

export const CAN_DO = {
  A1: "Entiendes y usas expresiones cotidianas muy básicas; puedes presentarte y hacer preguntas simples si te hablan despacio.",
  A2: "Entiendes frases frecuentes sobre temas cercanos (familia, compras, trabajo) y te comunicas en tareas simples y rutinarias.",
  B1: "Te desenvuelves en viajes, entiendes lo principal de temas conocidos y puedes describir experiencias, planes y opiniones.",
  B2: "Entiendes textos complejos y te comunicas con fluidez y espontaneidad con nativos; puedes participar en reuniones de trabajo.",
  C1: "Usas el idioma con flexibilidad y eficacia en contextos sociales, académicos y profesionales; produces textos claros y bien estructurados.",
  C2: "Entiendes prácticamente todo lo que oyes o lees y te expresas con precisión y matices finos.",
};
