// Vocabulario general (secciones 17-19, 143). Contenido original.
// Formato: [word, traducción, IPA, definición, ejemplo, CEFR, emoji, sinónimo, antónimo, variante UK]
// Orden dentro de cada tema = frecuencia (primero las más comunes).

const RAW = {
  social: { title: "Social English", es: "Inglés social", icon: "👋", words: [
    ["hello", "hola", "həˈloʊ", "a greeting", "Hello, nice to meet you.", "A1", "👋", "hi", "goodbye"],
    ["please", "por favor", "pliːz", "a polite word for requests", "Can you help me, please?", "A1", "🙏"],
    ["thank you", "gracias", "ˈθæŋk juː", "words to show you are grateful", "Thank you for your help.", "A1", "😊", "thanks"],
    ["sorry", "perdón / lo siento", "ˈsɑːri", "a word to apologize", "Sorry, I'm late.", "A1", "😔"],
    ["excuse me", "disculpe", "ɪkˈskjuːz miː", "a polite way to get attention", "Excuse me, where is the station?", "A1", "🙋"],
    ["welcome", "bienvenido", "ˈwelkəm", "a word to greet someone who arrives", "Welcome to the team!", "A1", "🤗"],
    ["friend", "amigo/a", "frend", "a person you know and like", "She is my best friend.", "A1", "🧑‍🤝‍🧑", "mate", "enemy"],
    ["invite", "invitar", "ɪnˈvaɪt", "to ask someone to come to an event", "I want to invite you to dinner.", "A2", "💌"],
    ["polite", "educado", "pəˈlaɪt", "showing good manners", "He is always very polite.", "A2", "🎩", "courteous", "rude"],
    ["chat", "charlar", "tʃæt", "to talk in a friendly, informal way", "We chatted for an hour.", "A2", "💬"],
    ["introduce", "presentar", "ˌɪntrəˈduːs", "to tell someone another person's name", "Let me introduce my colleague.", "A2", "🤝"],
    ["appreciate", "agradecer / valorar", "əˈpriːʃieɪt", "to be grateful for something", "I really appreciate your help.", "B1", "🙌"],
  ]},
  family: { title: "Family", es: "Familia", icon: "👨‍👩‍👧", words: [
    ["mother", "madre", "ˈmʌðər", "a female parent", "My mother is a teacher.", "A1", "👩", "mom", "father"],
    ["father", "padre", "ˈfɑːðər", "a male parent", "My father works in a bank.", "A1", "👨", "dad", "mother"],
    ["brother", "hermano", "ˈbrʌðər", "a boy or man with the same parents as you", "I have one brother.", "A1", "👦", "", "sister"],
    ["sister", "hermana", "ˈsɪstər", "a girl or woman with the same parents as you", "My sister lives in Spain.", "A1", "👧", "", "brother"],
    ["son", "hijo", "sʌn", "a male child", "Their son is five years old.", "A1", "👶", "", "daughter"],
    ["daughter", "hija", "ˈdɔːtər", "a female child", "Our daughter studies law.", "A1", "👧", "", "son"],
    ["husband", "esposo", "ˈhʌzbənd", "the man a woman is married to", "Her husband is an engineer.", "A1", "🤵", "", "wife"],
    ["wife", "esposa", "waɪf", "the woman a man is married to", "His wife is from Colombia.", "A1", "👰", "", "husband"],
    ["parents", "padres", "ˈperənts", "a mother and a father", "My parents live in Cuenca.", "A1", "👪"],
    ["grandmother", "abuela", "ˈɡrænmʌðər", "the mother of your mother or father", "My grandmother is 85.", "A1", "👵"],
    ["cousin", "primo/a", "ˈkʌzn", "the child of your aunt or uncle", "My cousin works in Miami.", "A2", "🧒"],
    ["relatives", "parientes", "ˈrelətɪvz", "members of your family", "We visit our relatives at Christmas.", "B1", "👨‍👩‍👧‍👦", "family"],
  ]},
  home: { title: "Home", es: "Casa", icon: "🏠", words: [
    ["house", "casa", "haʊs", "a building where people live", "They live in a big house.", "A1", "🏠", "home"],
    ["room", "habitación", "ruːm", "a part of a building with walls", "My room is small.", "A1", "🚪"],
    ["kitchen", "cocina", "ˈkɪtʃɪn", "the room where you cook", "The kitchen is next to the living room.", "A1", "🍳"],
    ["bedroom", "dormitorio", "ˈbedruːm", "the room where you sleep", "The apartment has two bedrooms.", "A1", "🛏️"],
    ["bathroom", "baño", "ˈbæθruːm", "the room with a toilet and shower", "Where is the bathroom?", "A1", "🚿", "restroom"],
    ["apartment", "departamento", "əˈpɑːrtmənt", "a set of rooms in a building", "I rent an apartment downtown.", "A1", "🏢", "", "", "flat"],
    ["table", "mesa", "ˈteɪbl", "furniture with a flat top and legs", "The keys are on the table.", "A1", "🪑"],
    ["window", "ventana", "ˈwɪndoʊ", "an opening in a wall with glass", "Please open the window.", "A1", "🪟"],
    ["neighbor", "vecino/a", "ˈneɪbər", "a person who lives near you", "Our neighbors are very friendly.", "A2", "🏘️", "", "", "neighbour"],
    ["rent", "alquiler / alquilar", "rent", "money you pay to live in a place", "The rent is $500 a month.", "A2", "💵"],
    ["furniture", "muebles", "ˈfɜːrnɪtʃər", "chairs, tables, beds, etc. (uncountable)", "We need new furniture.", "A2", "🛋️"],
    ["tidy", "ordenado", "ˈtaɪdi", "neat and organized", "Keep your room tidy.", "B1", "🧹", "neat", "messy"],
  ]},
  food: { title: "Food", es: "Comida", icon: "🍽️", words: [
    ["water", "agua", "ˈwɔːtər", "the clear liquid we drink", "Can I have some water, please?", "A1", "💧"],
    ["bread", "pan", "bred", "a food made from flour and baked", "I eat bread for breakfast.", "A1", "🍞"],
    ["coffee", "café", "ˈkɔːfi", "a hot dark drink", "I drink coffee every morning.", "A1", "☕"],
    ["chicken", "pollo", "ˈtʃɪkɪn", "meat from a chicken", "I'd like chicken and rice.", "A1", "🍗"],
    ["rice", "arroz", "raɪs", "small white or brown grains you cook", "Rice is very popular in Ecuador.", "A1", "🍚"],
    ["apple", "manzana", "ˈæpl", "a round red or green fruit", "An apple a day keeps the doctor away.", "A1", "🍎"],
    ["breakfast", "desayuno", "ˈbrekfəst", "the first meal of the day", "What do you have for breakfast?", "A1", "🥞"],
    ["lunch", "almuerzo", "lʌntʃ", "the meal in the middle of the day", "Let's have lunch together.", "A1", "🥪"],
    ["dinner", "cena", "ˈdɪnər", "the main meal in the evening", "Dinner is at eight.", "A1", "🍝"],
    ["menu", "menú / carta", "ˈmenjuː", "a list of food in a restaurant", "Could I see the menu, please?", "A1", "📋"],
    ["bill", "cuenta", "bɪl", "the paper that shows how much to pay", "Can we have the bill, please?", "A2", "🧾", "check"],
    ["delicious", "delicioso", "dɪˈlɪʃəs", "tasting very good", "This soup is delicious!", "A2", "😋", "tasty", "disgusting"],
    ["vegetables", "verduras", "ˈvedʒtəblz", "plants you eat, like carrots", "Eat more vegetables.", "A1", "🥦"],
    ["spicy", "picante", "ˈspaɪsi", "with a strong, hot flavor", "Is this dish spicy?", "A2", "🌶️", "hot", "mild"],
  ]},
  travel: { title: "Travel", es: "Viajes", icon: "✈️", words: [
    ["airport", "aeropuerto", "ˈerpɔːrt", "a place where planes land and take off", "I'm at the airport now.", "A1", "🛫"],
    ["passport", "pasaporte", "ˈpæspɔːrt", "an official document for travel", "May I see your passport?", "A1", "🛂"],
    ["ticket", "boleto", "ˈtɪkɪt", "a paper that lets you travel or enter", "I bought a return ticket.", "A1", "🎫"],
    ["flight", "vuelo", "flaɪt", "a trip in a plane", "My flight is delayed.", "A1", "✈️"],
    ["hotel", "hotel", "hoʊˈtel", "a building where travelers pay to stay", "The hotel is near the beach.", "A1", "🏨"],
    ["luggage", "equipaje", "ˈlʌɡɪdʒ", "bags for travel (uncountable)", "How much luggage do you have?", "A2", "🧳", "baggage"],
    ["reservation", "reserva", "ˌrezərˈveɪʃn", "an arrangement to have a room or table", "I have a reservation for two nights.", "A2", "📅", "booking"],
    ["gate", "puerta de embarque", "ɡeɪt", "the place where you board a plane", "The flight leaves from gate 12.", "A2", "🚪"],
    ["boarding pass", "pase de abordar", "ˈbɔːrdɪŋ pæs", "a card that lets you get on a plane", "Please show your boarding pass.", "A2", "🎟️"],
    ["delay", "retraso", "dɪˈleɪ", "when something happens later than planned", "There's a two-hour delay.", "A2", "⏱️"],
    ["check in", "registrarse", "tʃek ɪn", "to arrive and register at a hotel or airport", "What time can we check in?", "A2", "🛎️", "", "check out"],
    ["sightseeing", "turismo", "ˈsaɪtsiːɪŋ", "visiting interesting places", "We went sightseeing in Lima.", "B1", "📸"],
    ["customs", "aduana", "ˈkʌstəmz", "the place where officials check bags", "We went through customs quickly.", "B1", "🛃"],
  ]},
  transport: { title: "Transportation", es: "Transporte", icon: "🚌", words: [
    ["bus", "autobús", "bʌs", "a large vehicle that carries passengers", "I take the bus to work.", "A1", "🚌"],
    ["car", "auto", "kɑːr", "a road vehicle with four wheels", "She drives a red car.", "A1", "🚗"],
    ["train", "tren", "treɪn", "a vehicle that runs on rails", "The train leaves at nine.", "A1", "🚆"],
    ["taxi", "taxi", "ˈtæksi", "a car you pay to take you somewhere", "Let's take a taxi.", "A1", "🚕", "cab"],
    ["station", "estación", "ˈsteɪʃn", "a place where trains or buses stop", "Where is the train station?", "A1", "🚉"],
    ["traffic", "tráfico", "ˈtræfɪk", "cars and vehicles on the road", "The traffic is terrible today.", "A2", "🚦"],
    ["subway", "metro", "ˈsʌbweɪ", "an underground train", "Take the subway to downtown.", "A2", "🚇", "metro", "", "underground"],
    ["driver", "conductor", "ˈdraɪvər", "a person who drives", "The driver was very friendly.", "A1", "🧑‍✈️"],
    ["route", "ruta", "ruːt", "the way from one place to another", "What's the fastest route?", "B1", "🗺️"],
    ["fare", "tarifa / pasaje", "fer", "the money you pay to travel", "How much is the bus fare?", "B1", "💲"],
  ]},
  work: { title: "Work", es: "Trabajo", icon: "💼", words: [
    ["job", "trabajo / empleo", "dʒɑːb", "the work you do for money", "I love my job.", "A1", "💼", "position"],
    ["office", "oficina", "ˈɔːfɪs", "a room or building where people work", "Our office is on the fifth floor.", "A1", "🏢"],
    ["boss", "jefe", "bɔːs", "the person in charge of you at work", "My boss is very organized.", "A1", "🧑‍💼", "manager", "employee"],
    ["colleague", "colega", "ˈkɑːliːɡ", "a person you work with", "My colleagues are great.", "A2", "🧑‍🤝‍🧑", "coworker"],
    ["salary", "salario", "ˈsæləri", "money you earn every month", "The salary is good.", "A2", "💰", "pay"],
    ["meeting", "reunión", "ˈmiːtɪŋ", "when people meet to discuss something", "We have a meeting at ten.", "A1", "📅"],
    ["deadline", "fecha límite", "ˈdedlaɪn", "the time by which something must be done", "The deadline is Friday.", "B1", "⏰"],
    ["task", "tarea", "tæsk", "a piece of work to do", "I have three tasks today.", "A2", "✅"],
    ["experience", "experiencia", "ɪkˈspɪriəns", "knowledge from doing something", "She has ten years of experience.", "A2", "🧠"],
    ["skill", "habilidad", "skɪl", "an ability to do something well", "Communication is an important skill.", "A2", "🛠️"],
    ["responsible", "responsable", "rɪˈspɑːnsəbl", "having the duty to deal with something", "Who is responsible for this project?", "B1", "🎯", "in charge"],
    ["shift", "turno", "ʃɪft", "a period of work", "I work the night shift.", "B1", "🌙"],
    ["hire", "contratar", "ˈhaɪər", "to give someone a job", "We're going to hire two engineers.", "B1", "🤝", "employ", "fire"],
  ]},
  university: { title: "University", es: "Universidad", icon: "🎓", words: [
    ["student", "estudiante", "ˈstuːdnt", "a person who studies", "I'm a student at the university.", "A1", "🧑‍🎓"],
    ["teacher", "profesor/a", "ˈtiːtʃər", "a person who teaches", "Our teacher is from Canada.", "A1", "🧑‍🏫"],
    ["class", "clase", "klæs", "a lesson or group of students", "The class starts at eight.", "A1", "🏫"],
    ["exam", "examen", "ɪɡˈzæm", "a test of knowledge", "I have an exam tomorrow.", "A1", "📝", "test"],
    ["degree", "título universitario", "dɪˈɡriː", "a qualification from a university", "She has a degree in engineering.", "B1", "📜"],
    ["homework", "tarea (escolar)", "ˈhoʊmwɜːrk", "work students do at home (uncountable)", "I do my homework after dinner.", "A1", "📚"],
    ["library", "biblioteca", "ˈlaɪbreri", "a place where you borrow books", "I study in the library.", "A2", "🏛️"],
    ["grade", "nota / calificación", "ɡreɪd", "a mark for your work", "I got a good grade.", "A2", "💯", "mark"],
    ["research", "investigación", "ˈriːsɜːrtʃ", "detailed study to find new facts", "She's doing research on solar energy.", "B1", "🔬"],
    ["scholarship", "beca", "ˈskɑːlərʃɪp", "money to pay for studies", "He got a scholarship to study abroad.", "B1", "🏅"],
  ]},
  nature: { title: "Nature", es: "Naturaleza", icon: "🌿", words: [
    ["tree", "árbol", "triː", "a tall plant with a trunk", "There's a big tree in the park.", "A1", "🌳"],
    ["river", "río", "ˈrɪvər", "a large natural flow of water", "The river is very long.", "A1", "🏞️"],
    ["mountain", "montaña", "ˈmaʊntn", "a very high hill", "Chimborazo is a famous mountain.", "A1", "⛰️"],
    ["sea", "mar", "siː", "the salt water that covers much of the earth", "I love swimming in the sea.", "A1", "🌊", "ocean"],
    ["beach", "playa", "biːtʃ", "an area of sand next to the sea", "We went to the beach.", "A1", "🏖️"],
    ["animal", "animal", "ˈænɪml", "a living creature", "What's your favorite animal?", "A1", "🐾"],
    ["forest", "bosque", "ˈfɔːrɪst", "a large area with many trees", "The Amazon is a huge forest.", "A2", "🌲"],
    ["environment", "medio ambiente", "ɪnˈvaɪrənmənt", "the natural world around us", "We must protect the environment.", "B1", "🌍"],
    ["pollution", "contaminación", "pəˈluːʃn", "harmful substances in air, water or soil", "Air pollution is a big problem.", "B1", "🏭"],
    ["island", "isla", "ˈaɪlənd", "land surrounded by water", "The Galápagos are famous islands.", "A2", "🏝️"],
  ]},
  weather: { title: "Weather", es: "Clima", icon: "🌦️", words: [
    ["sunny", "soleado", "ˈsʌni", "with a lot of sun", "It's sunny today.", "A1", "☀️", "", "cloudy"],
    ["rain", "lluvia / llover", "reɪn", "water that falls from clouds", "It's going to rain.", "A1", "🌧️"],
    ["cold", "frío", "koʊld", "with a low temperature", "It's very cold in the mountains.", "A1", "🥶", "chilly", "hot"],
    ["hot", "caluroso", "hɑːt", "with a high temperature", "It's hot in Guayaquil.", "A1", "🥵", "warm", "cold"],
    ["windy", "ventoso", "ˈwɪndi", "with a lot of wind", "It's windy on the platform.", "A2", "💨"],
    ["cloudy", "nublado", "ˈklaʊdi", "with many clouds", "The sky is cloudy.", "A2", "☁️", "", "sunny"],
    ["storm", "tormenta", "stɔːrm", "very bad weather with wind and rain", "The storm closed the port.", "A2", "⛈️"],
    ["forecast", "pronóstico", "ˈfɔːrkæst", "a prediction of the weather", "The forecast says it will rain.", "B1", "📡"],
    ["temperature", "temperatura", "ˈtemprətʃər", "how hot or cold something is", "The temperature is 25 degrees.", "A2", "🌡️"],
  ]},
  technology: { title: "Technology", es: "Tecnología", icon: "💻", words: [
    ["computer", "computadora", "kəmˈpjuːtər", "an electronic machine for work and data", "My computer is very slow.", "A1", "💻"],
    ["phone", "teléfono", "foʊn", "a device to call people", "Can I use your phone?", "A1", "📱"],
    ["email", "correo electrónico", "ˈiːmeɪl", "a message sent by computer", "I'll send you an email.", "A1", "📧"],
    ["password", "contraseña", "ˈpæswɜːrd", "a secret word to access something", "I forgot my password.", "A2", "🔐"],
    ["download", "descargar", "ˈdaʊnloʊd", "to copy data from the internet", "Download the file here.", "A2", "⬇️", "", "upload"],
    ["website", "sitio web", "ˈwebsaɪt", "a set of pages on the internet", "Visit our website.", "A2", "🌐"],
    ["software", "software", "ˈsɔːftwer", "programs used by a computer (uncountable)", "We use new software for reports.", "B1", "🧩"],
    ["update", "actualizar / actualización", "ˌʌpˈdeɪt", "to make something more modern or current", "Please update the app.", "B1", "🔄"],
    ["device", "dispositivo", "dɪˈvaɪs", "a machine or tool for a purpose", "Turn off all devices.", "B1", "📟"],
    ["data", "datos", "ˈdeɪtə", "facts and numbers", "We need more data.", "B1", "📊"],
    ["log in", "iniciar sesión", "lɔːɡ ɪn", "to enter a system with a password", "Log in with your email.", "A2", "🔑", "sign in", "log out"],
  ]},
  shopping: { title: "Shopping", es: "Compras", icon: "🛍️", words: [
    ["buy", "comprar", "baɪ", "to get something by paying", "I want to buy a jacket.", "A1", "🛒", "purchase", "sell"],
    ["price", "precio", "praɪs", "the money you pay for something", "What's the price?", "A1", "🏷️", "cost"],
    ["cheap", "barato", "tʃiːp", "not expensive", "This phone is cheap.", "A1", "🪙", "inexpensive", "expensive"],
    ["expensive", "caro", "ɪkˈspensɪv", "costing a lot of money", "The hotel is expensive.", "A1", "💎", "costly", "cheap"],
    ["size", "talla / tamaño", "saɪz", "how big something is", "What size are you?", "A1", "📏"],
    ["cash", "efectivo", "kæʃ", "money in coins or notes", "Do you accept cash?", "A2", "💵"],
    ["receipt", "recibo", "rɪˈsiːt", "a paper showing you paid", "Can I have a receipt?", "A2", "🧾"],
    ["discount", "descuento", "ˈdɪskaʊnt", "a lower price", "Is there a discount?", "B1", "🔖"],
    ["refund", "reembolso", "ˈriːfʌnd", "money given back to you", "I'd like a refund.", "B1", "↩️"],
  ]},
  clothes: { title: "Clothes", es: "Ropa", icon: "👕", words: [
    ["shirt", "camisa", "ʃɜːrt", "a piece of clothing for the upper body", "He's wearing a white shirt.", "A1", "👔"],
    ["shoes", "zapatos", "ʃuːz", "things you wear on your feet", "I need new shoes.", "A1", "👞"],
    ["jacket", "chaqueta", "ˈdʒækɪt", "a short coat", "Take a jacket. It's cold.", "A1", "🧥"],
    ["pants", "pantalones", "pænts", "clothing for the legs", "These pants are too long.", "A1", "👖", "", "", "trousers"],
    ["dress", "vestido", "dres", "a one-piece garment for women", "She's wearing a blue dress.", "A1", "👗"],
    ["wear", "llevar puesto", "wer", "to have clothes on your body", "You must wear safety boots.", "A2", "🥾"],
    ["uniform", "uniforme", "ˈjuːnɪfɔːrm", "special clothes for a job or school", "Workers wear a uniform.", "A2", "🦺"],
  ]},
  health: { title: "Health", es: "Salud", icon: "🩺", words: [
    ["doctor", "médico", "ˈdɑːktər", "a person who treats sick people", "I need to see a doctor.", "A1", "🧑‍⚕️"],
    ["sick", "enfermo", "sɪk", "not well; ill", "I'm sick today.", "A1", "🤒", "ill", "healthy"],
    ["headache", "dolor de cabeza", "ˈhedeɪk", "a pain in your head", "I have a headache.", "A2", "🤕"],
    ["medicine", "medicina", "ˈmedɪsn", "something you take to get better", "Take this medicine twice a day.", "A1", "💊"],
    ["hospital", "hospital", "ˈhɑːspɪtl", "a place where sick people get care", "She works in a hospital.", "A1", "🏥"],
    ["appointment", "cita", "əˈpɔɪntmənt", "an arranged meeting at a time", "I have a doctor's appointment.", "A2", "📆"],
    ["pain", "dolor", "peɪn", "the feeling when you are hurt", "Where is the pain?", "A2", "😣"],
    ["injury", "lesión", "ˈɪndʒəri", "damage to the body", "Report every injury immediately.", "B1", "🩹"],
    ["prescription", "receta médica", "prɪˈskrɪpʃn", "a doctor's written order for medicine", "You need a prescription.", "B1", "📝"],
  ]},
  sports: { title: "Sports", es: "Deportes", icon: "⚽", words: [
    ["soccer", "fútbol", "ˈsɑːkər", "a game where two teams kick a ball", "We play soccer on Sundays.", "A1", "⚽", "", "", "football"],
    ["run", "correr", "rʌn", "to move fast on your feet", "I run every morning.", "A1", "🏃"],
    ["swim", "nadar", "swɪm", "to move through water", "Can you swim?", "A1", "🏊"],
    ["team", "equipo", "tiːm", "a group that plays or works together", "Our team won!", "A1", "🧑‍🤝‍🧑"],
    ["win", "ganar", "wɪn", "to be first in a game", "Who will win the match?", "A2", "🏆", "", "lose"],
    ["gym", "gimnasio", "dʒɪm", "a place for exercise", "I go to the gym three times a week.", "A2", "🏋️"],
    ["match", "partido", "mætʃ", "a sports competition between two teams", "The match starts at eight.", "A2", "🏟️", "game"],
  ]},
  emotions: { title: "Emotions", es: "Emociones", icon: "💛", words: [
    ["happy", "feliz", "ˈhæpi", "feeling good and pleased", "I'm happy with the results.", "A1", "😄", "glad", "sad"],
    ["sad", "triste", "sæd", "feeling unhappy", "Why are you sad?", "A1", "😢", "unhappy", "happy"],
    ["tired", "cansado", "ˈtaɪərd", "needing rest", "I'm tired after work.", "A1", "😴", "exhausted"],
    ["angry", "enojado", "ˈæŋɡri", "feeling strong displeasure", "The client was angry.", "A2", "😠", "upset", "calm"],
    ["worried", "preocupado", "ˈwɜːrid", "feeling anxious about something", "I'm worried about the exam.", "A2", "😟", "anxious", "relaxed"],
    ["excited", "emocionado", "ɪkˈsaɪtɪd", "very happy and enthusiastic", "I'm excited about the trip.", "A2", "🤩"],
    ["bored", "aburrido (sentir)", "bɔːrd", "feeling that something is not interesting", "I'm bored. Let's go out.", "A2", "🥱", "", "interested"],
    ["embarrassed", "avergonzado", "ɪmˈbærəst", "feeling ashamed or uncomfortable", "I was embarrassed by my mistake.", "B1", "😳"],
    ["proud", "orgulloso", "praʊd", "pleased with an achievement", "I'm proud of my team.", "B1", "😌", "", "ashamed"],
    ["stressed", "estresado", "strest", "feeling worried because of pressure", "I feel stressed before deadlines.", "B1", "😩", "", "relaxed"],
  ]},
  time: { title: "Time & basics", es: "Tiempo y básicos", icon: "🕒", words: [
    ["today", "hoy", "təˈdeɪ", "this day", "What are you doing today?", "A1", "📅"],
    ["tomorrow", "mañana", "təˈmɑːroʊ", "the day after today", "See you tomorrow.", "A1", "➡️", "", "yesterday"],
    ["yesterday", "ayer", "ˈjestərdeɪ", "the day before today", "I called you yesterday.", "A1", "⬅️", "", "tomorrow"],
    ["week", "semana", "wiːk", "seven days", "I work five days a week.", "A1", "🗓️"],
    ["morning", "mañana (parte del día)", "ˈmɔːrnɪŋ", "the early part of the day", "I study in the morning.", "A1", "🌅"],
    ["hour", "hora", "ˈaʊər", "sixty minutes", "The meeting takes an hour.", "A1", "⌛"],
    ["early", "temprano", "ˈɜːrli", "before the usual time", "I get up early.", "A1", "🐓", "", "late"],
    ["late", "tarde", "leɪt", "after the usual or expected time", "Sorry I'm late.", "A1", "🕰️", "", "early"],
    ["always", "siempre", "ˈɔːlweɪz", "all the time", "She always arrives on time.", "A1", "♾️", "", "never"],
    ["usually", "normalmente", "ˈjuːʒuəli", "most of the time", "I usually take the bus.", "A1", "🔁", "normally"],
  ]},
  business: { title: "Business", es: "Negocios", icon: "📈", words: [
    ["company", "empresa", "ˈkʌmpəni", "a business organization", "I work for an oil company.", "A1", "🏢", "firm"],
    ["customer", "cliente", "ˈkʌstəmər", "a person who buys goods or services", "The customer is always right.", "A2", "🧑", "client"],
    ["sales", "ventas", "seɪlz", "the number of things sold", "Sales increased by 10%.", "A2", "📈"],
    ["profit", "ganancia", "ˈprɑːfɪt", "money you make after costs", "The company made a profit.", "B1", "💹", "gain", "loss"],
    ["budget", "presupuesto", "ˈbʌdʒɪt", "a plan for how to spend money", "We are over budget.", "B1", "💼"],
    ["invoice", "factura", "ˈɪnvɔɪs", "a document asking for payment", "Please send the invoice.", "B1", "🧾", "bill"],
    ["supplier", "proveedor", "səˈplaɪər", "a company that provides goods", "We changed our supplier.", "B1", "🚚", "vendor"],
    ["market", "mercado", "ˈmɑːrkɪt", "the area of trade for a product", "The market is very competitive.", "A2", "🏪"],
    ["competitor", "competidor", "kəmˈpetɪtər", "a company that sells similar products", "Our competitor lowered prices.", "B1", "🥊"],
    ["growth", "crecimiento", "ɡroʊθ", "an increase in size or amount", "We expect strong growth.", "B1", "🌱", "increase", "decline"],
    ["strategy", "estrategia", "ˈstrætədʒi", "a plan to achieve a goal", "What's our strategy for next year?", "B1", "♟️"],
    ["stakeholder", "parte interesada", "ˈsteɪkhoʊldər", "a person with an interest in a project", "We must inform all stakeholders.", "B2", "👥"],
  ]},
  meetings: { title: "Meetings", es: "Reuniones", icon: "🗓️", words: [
    ["agenda", "orden del día", "əˈdʒendə", "a list of topics for a meeting", "Let's look at the agenda.", "B1", "📋"],
    ["minutes", "acta", "ˈmɪnɪts", "a written record of a meeting", "Who is taking the minutes?", "B1", "📝"],
    ["schedule", "programar / cronograma", "ˈskedʒuːl", "a plan of times and dates", "Let's schedule a call.", "A2", "🗓️"],
    ["postpone", "posponer", "poʊstˈpoʊn", "to move to a later time", "We need to postpone the meeting.", "B1", "⏭️", "put off", "bring forward"],
    ["attend", "asistir", "əˈtend", "to be present at an event", "Ten people attended the meeting.", "B1", "🙋", "", "miss"],
    ["summarize", "resumir", "ˈsʌməraɪz", "to give the main points", "Let me summarize the key points.", "B1", "🧾"],
    ["action item", "tarea asignada", "ˈækʃn ˈaɪtəm", "a task agreed in a meeting", "Who owns this action item?", "B2", "📌"],
    ["proposal", "propuesta", "prəˈpoʊzl", "a plan or suggestion", "Let's discuss the proposal.", "B1", "📄"],
    ["agree", "estar de acuerdo", "əˈɡriː", "to have the same opinion", "I agree with you.", "A2", "👍", "", "disagree"],
    ["clarify", "aclarar", "ˈklærəfaɪ", "to make something clearer", "Could you clarify that point?", "B1", "🔍"],
  ]},
};

function slug(w) { return "w." + w.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }

export function buildWords(raw, area = "") {
  const words = [], topics = [];
  for (const [topic, t] of Object.entries(raw)) {
    const ids = [];
    t.words.forEach((r, i) => {
      const [word, es, ipa, def, ex, cefr, emoji, syn = "", ant = "", uk = ""] = r;
      const id = slug(word);
      ids.push(id);
      words.push({ id, word, es, ipa, def, ex, cefr, emoji, syn, ant, uk, topic, area: area || t.area || "", freq: i < 5 ? 1 : i < 10 ? 2 : 3 });
    });
    topics.push({ id: topic, concept: "v." + topic, title: t.title, es: t.es, icon: t.icon, area: area || t.area || "", level: t.level || "", words: ids });
  }
  return { words, topics };
}

const general = buildWords(RAW);
export const GENERAL_WORDS = general.words;
export const GENERAL_TOPICS = general.topics;
