// Vocabulario avanzado B2–C2. Mismo formato que vocab.js. Contenido original.
import { buildWords } from "./vocab.js";

const RAW = {
  society: { title: "Society & news", es: "Sociedad y noticias", icon: "📰", level: "B2", words: [
    ["issue", "tema / problema", "ˈɪʃuː", "an important topic or problem", "Unemployment is a serious issue.", "B2", "❗"],
    ["unemployment", "desempleo", "ˌʌnɪmˈplɔɪmənt", "the state of not having a job", "Unemployment fell last year.", "B2", "📉"],
    ["inequality", "desigualdad", "ˌɪnɪˈkwɑːləti", "an unfair difference between groups", "Income inequality is growing.", "B2", "⚖️"],
    ["government", "gobierno", "ˈɡʌvərnmənt", "the group that controls a country", "The government announced new measures.", "B2", "🏛️"],
    ["policy", "política (medida)", "ˈpɑːləsi", "a plan of action by an organisation", "The new tax policy is controversial.", "B2", "📜"],
    ["controversial", "polémico", "ˌkɑːntrəˈvɜːrʃl", "causing disagreement", "It's a controversial decision.", "B2", "🔥"],
    ["survey", "encuesta", "ˈsɜːrveɪ", "a set of questions to learn people's opinions", "A recent survey shows people prefer hybrid work.", "B2", "📋"],
    ["trend", "tendencia", "trend", "a general direction of change", "There's a trend towards electric cars.", "B2", "📈"],
    ["crisis", "crisis", "ˈkraɪsɪs", "a time of great danger or difficulty", "The economic crisis affected many families.", "B2", "🚨"],
    ["citizen", "ciudadano/a", "ˈsɪtɪzn", "a person who belongs to a country", "Every citizen has the right to vote.", "B2", "🧑"],
    ["headline", "titular", "ˈhedlaɪn", "the title of a news story", "The story made the headlines.", "B2", "🗞️"],
    ["affordable", "asequible", "əˈfɔːrdəbl", "cheap enough for people to buy", "We need more affordable housing.", "B2", "🏠", "reasonable", "unaffordable"],
  ]},
  environment: { title: "Environment & climate", es: "Medio ambiente y clima", icon: "🌎", level: "B2", words: [
    ["climate change", "cambio climático", "ˈklaɪmət tʃeɪndʒ", "long-term change in the Earth's weather", "Climate change affects agriculture.", "B2", "🌡️"],
    ["emissions", "emisiones", "iˈmɪʃnz", "gases sent into the air", "We must reduce carbon emissions.", "B2", "🏭"],
    ["greenhouse gas", "gas de efecto invernadero", "ˈɡriːnhaʊs ɡæs", "a gas that traps heat in the atmosphere", "Methane is a greenhouse gas.", "B2", "☁️"],
    ["recycle", "reciclar", "ˌriːˈsaɪkl", "to use materials again", "We recycle paper and plastic.", "B2", "♻️"],
    ["waste", "residuos / desperdiciar", "weɪst", "material that is thrown away", "Reduce waste in the plant.", "B2", "🗑️"],
    ["drought", "sequía", "draʊt", "a long period without rain", "The drought damaged the crops.", "B2", "🏜️"],
    ["flood", "inundación", "flʌd", "a large amount of water covering land", "The flood closed the road.", "B2", "🌊"],
    ["endangered", "en peligro de extinción", "ɪnˈdeɪndʒərd", "at risk of disappearing", "Many species are endangered.", "B2", "🐼"],
    ["footprint", "huella (de carbono)", "ˈfʊtprɪnt", "the impact of an activity on the environment", "Flying increases your carbon footprint.", "B2", "👣"],
    ["deforestation", "deforestación", "diːˌfɔːrɪˈsteɪʃn", "cutting down forests", "Deforestation threatens the Amazon.", "C1", "🪓"],
    ["biodiversity", "biodiversidad", "ˌbaɪoʊdaɪˈvɜːrsəti", "the variety of life in an area", "Ecuador has amazing biodiversity.", "C1", "🦜"],
  ]},
  academic: { title: "Academic English", es: "Inglés académico", icon: "🎓", level: "C1", words: [
    ["analyze", "analizar", "ˈænəlaɪz", "to examine something in detail", "We analyzed the data carefully.", "B2", "🔬", "examine", "", "analyse"],
    ["assess", "evaluar", "əˈses", "to judge the quality or value of something", "We need to assess the risks.", "C1", "📏", "evaluate"],
    ["significant", "significativo", "sɪɡˈnɪfɪkənt", "important or large enough to notice", "There was a significant increase in sales.", "B2", "📊", "considerable", "insignificant"],
    ["evidence-based", "basado en evidencia", "ˈevɪdəns beɪst", "supported by facts and research", "We need evidence-based decisions.", "C1", "🧾"],
    ["hypothesis", "hipótesis", "haɪˈpɑːθəsɪs", "an idea that can be tested", "The results support our hypothesis.", "C1", "💭"],
    ["approach", "enfoque", "əˈproʊtʃ", "a way of dealing with something", "We need a different approach.", "B2", "🧭", "method"],
    ["framework", "marco", "ˈfreɪmwɜːrk", "a structure of ideas or rules", "The framework guides our decisions.", "C1", "🧱"],
    ["outcome", "resultado", "ˈaʊtkʌm", "the final result", "The outcome was positive.", "C1", "🎯", "result"],
    ["implication", "implicación", "ˌɪmplɪˈkeɪʃn", "a possible effect of an action or decision", "What are the implications of this policy?", "C1", "🔗"],
    ["consistent", "coherente / constante", "kənˈsɪstənt", "always behaving in the same way", "The results were consistent.", "B2", "🔁", "", "inconsistent"],
    ["relevant", "pertinente", "ˈreləvənt", "connected to what is being discussed", "Please include only relevant information.", "B2", "✅", "", "irrelevant"],
    ["thereby", "de ese modo", "ˌðerˈbaɪ", "as a result of that (formal)", "We automated the process, thereby reducing errors.", "C2", "➡️"],
  ]},
  "business-adv": { title: "Advanced business", es: "Negocios avanzados", icon: "🏦", level: "C1", words: [
    ["leverage", "aprovechar", "ˈlevərɪdʒ", "to use something to get the maximum advantage", "We can leverage our experience in Peru.", "C1", "🏗️"],
    ["benchmark", "referente / comparar", "ˈbentʃmɑːrk", "a standard used for comparison", "We benchmark our prices against competitors.", "C1", "📐"],
    ["streamline", "simplificar / optimizar", "ˈstriːmlaɪn", "to make a process simpler and more efficient", "We streamlined the approval process.", "C1", "〰️"],
    ["stakeholder buy-in", "apoyo de las partes interesadas", "ˈsteɪkhoʊldər ˈbaɪ ɪn", "agreement and support from key people", "We need stakeholder buy-in before launching.", "C1", "🤝"],
    ["bottleneck", "cuello de botella", "ˈbɑːtlnek", "a point where a process slows down", "Approvals are the main bottleneck.", "C1", "🍾"],
    ["revenue stream", "fuente de ingresos", "ˈrevənuː striːm", "a source of income", "Maintenance contracts are a new revenue stream.", "C1", "💧"],
    ["scalable", "escalable", "ˈskeɪləbl", "able to grow easily", "The model is scalable to other regions.", "C1", "📈"],
    ["due diligence", "debida diligencia", "duː ˈdɪlɪdʒəns", "careful investigation before a deal", "Due diligence took three months.", "C1", "🔍"],
    ["turnover", "facturación / rotación", "ˈtɜːrnoʊvər", "total sales; also rate of staff leaving", "Staff turnover is too high.", "C1", "🔄"],
    ["contingency plan", "plan de contingencia", "kənˈtɪndʒənsi plæn", "a plan for a possible future problem", "We have a contingency plan for delays.", "C1", "🛟"],
    ["mitigate", "mitigar", "ˈmɪtɪɡeɪt", "to make something less serious", "These measures mitigate the risk.", "C1", "🛡️"],
    ["headcount", "número de empleados", "ˈhedkaʊnt", "the number of people employed", "We can't increase headcount this year.", "C1", "👥"],
  ]},
  "c1-verbs": { title: "C1 power verbs", es: "Verbos clave C1", icon: "⚡", level: "C1", words: [
    ["undermine", "socavar", "ˌʌndərˈmaɪn", "to gradually weaken something", "Delays undermine client trust.", "C1", "⛏️"],
    ["foster", "fomentar", "ˈfɔːstər", "to encourage something to develop", "We want to foster innovation.", "C1", "🌱"],
    ["enhance", "mejorar / potenciar", "ɪnˈhæns", "to improve quality or value", "The upgrade will enhance performance.", "C1", "✨"],
    ["tackle", "abordar", "ˈtækl", "to deal with a difficult problem", "We need to tackle absenteeism.", "C1", "🏉"],
    ["overlook", "pasar por alto", "ˌoʊvərˈlʊk", "to fail to notice something", "The inspector overlooked a small crack.", "C1", "👀"],
    ["comply", "cumplir (normas)", "kəmˈplaɪ", "to obey a rule or law", "All suppliers must comply with the standard.", "C1", "✔️"],
    ["allocate", "asignar", "ˈæləkeɪt", "to give resources for a purpose", "We allocated more budget to training.", "C1", "📦"],
    ["prioritize", "priorizar", "praɪˈɔːrətaɪz", "to decide what is most important", "Prioritize safety over speed.", "B2", "🔝", "", "", "prioritise"],
    ["outline", "esbozar / resumir", "ˈaʊtlaɪn", "to describe the main points", "Let me outline the plan.", "B2", "📝"],
    ["endorse", "respaldar", "ɪnˈdɔːrs", "to publicly support", "The board endorsed the proposal.", "C1", "👍"],
    ["refine", "perfeccionar", "rɪˈfaɪn", "to improve by making small changes", "We refined the design after testing.", "C1", "🔧"],
    ["anticipate", "prever", "ænˈtɪsɪpeɪt", "to expect and prepare for something", "We anticipate strong demand.", "C1", "🔮"],
  ]},
  "c2-words": { title: "C2 precision words", es: "Palabras de precisión C2", icon: "💎", level: "C2", words: [
    ["nuanced", "matizado", "ˈnuːɑːnst", "showing subtle differences", "She gave a nuanced answer.", "C2", "🎨"],
    ["ubiquitous", "omnipresente", "juːˈbɪkwɪtəs", "found everywhere", "Smartphones are ubiquitous.", "C2", "🌐"],
    ["pragmatic", "pragmático", "præɡˈmætɪk", "practical rather than theoretical", "We need a pragmatic solution.", "C1", "🛠️", "practical", "idealistic"],
    ["meticulous", "meticuloso", "məˈtɪkjələs", "very careful about details", "She's meticulous about documentation.", "C2", "🔎", "thorough", "careless"],
    ["detrimental", "perjudicial", "ˌdetrɪˈmentl", "causing harm", "Stress is detrimental to health.", "C2", "⚠️", "harmful", "beneficial"],
    ["unprecedented", "sin precedentes", "ʌnˈpresɪdentɪd", "never done or known before", "Demand reached unprecedented levels.", "C2", "🚀"],
    ["scrutinize", "examinar minuciosamente", "ˈskruːtənaɪz", "to examine very carefully", "Investors scrutinize every report.", "C2", "🧐", "", "", "scrutinise"],
    ["discrepancy", "discrepancia", "dɪˈskrepənsi", "a difference between things that should match", "There's a discrepancy in the figures.", "C2", "❓"],
    ["inherent", "inherente", "ɪnˈhɪrənt", "existing as a natural part of something", "Every project has inherent risks.", "C2", "🧬"],
    ["paramount", "primordial", "ˈpærəmaʊnt", "more important than anything else", "Safety is paramount.", "C2", "🏔️"],
    ["mitigating", "atenuante", "ˈmɪtɪɡeɪtɪŋ", "making something less severe", "There were mitigating circumstances.", "C2", "🪶"],
    ["corroborate", "corroborar", "kəˈrɑːbəreɪt", "to confirm with evidence", "The data corroborate our findings.", "C2", "✅"],
  ]},
};

const built = buildWords(RAW);
export const ADV_WORDS = built.words;
export const ADV_TOPICS = built.topics;
